// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPRESETEDIT_H
#define UI_SCREENPRESETEDIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPresetEdit
extern void ui_ScreenPresetEdit_screen_init(void);
extern void ui_ScreenPresetEdit_screen_destroy(void);
extern lv_obj_t * ui_ScreenPresetEdit;
extern lv_obj_t * ui_HeaderBewerkenBackground;
extern lv_obj_t * ui_HeaderBewerken;
extern lv_obj_t * ui_EditPresetBackground;
extern lv_obj_t * ui_EditPreset;
extern lv_obj_t * ui_EditCosmeticLine;
extern lv_obj_t * ui_EditNamePreset;
extern lv_obj_t * ui_EditPresetHoogteM1;
extern lv_obj_t * ui_EditPresetHoogteM2;
extern void ui_event_ButtonResetPreset(lv_event_t * e);
extern lv_obj_t * ui_ButtonResetPreset;
extern lv_obj_t * ui_TextButtonResetPreset;
extern void ui_event_ButtonOpslaan(lv_event_t * e);
extern lv_obj_t * ui_ButtonOpslaan;
extern lv_obj_t * ui_TextButtonOpslaan;
extern void ui_event_ButtonVolgende(lv_event_t * e);
extern lv_obj_t * ui_ButtonVolgende;
extern lv_obj_t * ui_TextButtonVolgende;
extern void ui_event_ButtonVorige(lv_event_t * e);
extern lv_obj_t * ui_ButtonVorige;
extern lv_obj_t * ui_TextButtonVorige;
extern void ui_event_ButtonGoToPresets2(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToPresets2;
extern lv_obj_t * ui_TextButtonGoToPresets2;
extern lv_obj_t * ui_InsertNameBackground;
extern lv_obj_t * ui_InsertNameText;
extern void ui_event_InsertNameTextArea(lv_event_t * e);
extern lv_obj_t * ui_InsertNameTextArea;
extern lv_obj_t * ui_InsertM1Background;
extern lv_obj_t * ui_InsertM1Text;
extern void ui_event_InsertM1TextArea(lv_event_t * e);
extern lv_obj_t * ui_InsertM1TextArea;
extern lv_obj_t * ui_InsertM2Background;
extern lv_obj_t * ui_InsertM2Text;
extern void ui_event_InsertM2TextArea(lv_event_t * e);
extern lv_obj_t * ui_InsertM2TextArea;
extern void ui_event_InsertNameKeyboard(lv_event_t * e);
extern lv_obj_t * ui_InsertNameKeyboard;
extern void ui_event_InsertM1Keyboard(lv_event_t * e);
extern lv_obj_t * ui_InsertM1Keyboard;
extern void ui_event_InsertM2Keyboard(lv_event_t * e);
extern lv_obj_t * ui_InsertM2Keyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

