// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPRESETSSELECT_H
#define UI_SCREENPRESETSSELECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPresetsSelect
extern void ui_ScreenPresetsSelect_screen_init(void);
extern void ui_ScreenPresetsSelect_screen_destroy(void);
extern lv_obj_t * ui_ScreenPresetsSelect;
extern lv_obj_t * ui_HeaderPresetsBackground;
extern lv_obj_t * ui_HeaderPresets;
extern lv_obj_t * ui_Preset1Background;
extern lv_obj_t * ui_Preset1;
extern lv_obj_t * ui_CosmeticLine1;
extern lv_obj_t * ui_NamePreset1;
extern lv_obj_t * ui_Preset1HoogteM1;
extern lv_obj_t * ui_Preset1HoogteM2;
extern void ui_event_ButtonSelectPreset1(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectPreset1;
extern lv_obj_t * ui_TextButtonSelectPreset1;
extern lv_obj_t * ui_Preset2Background;
extern lv_obj_t * ui_Preset2;
extern lv_obj_t * ui_CosmeticLine2;
extern lv_obj_t * ui_NamePreset2;
extern lv_obj_t * ui_Preset2HoogteM1;
extern lv_obj_t * ui_Preset2HoogteM2;
extern void ui_event_ButtonSelectPreset2(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectPreset2;
extern lv_obj_t * ui_TextButtonSelectPreset2;
extern lv_obj_t * ui_Preset2Background1;
extern lv_obj_t * ui_Preset3;
extern lv_obj_t * ui_CosmeticLine3;
extern lv_obj_t * ui_NamePreset3;
extern lv_obj_t * ui_Preset3HoogteM1;
extern lv_obj_t * ui_Preset3HoogteM2;
extern void ui_event_ButtonSelectPreset3(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectPreset3;
extern lv_obj_t * ui_TextButtonSelectPreset3;
extern lv_obj_t * ui_Preset2Background2;
extern lv_obj_t * ui_Preset4;
extern lv_obj_t * ui_CosmeticLine4;
extern lv_obj_t * ui_NamePreset4;
extern lv_obj_t * ui_Preset4HoogteM1;
extern lv_obj_t * ui_Preset4HoogteM2;
extern void ui_event_ButtonSelectPreset4(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectPreset4;
extern lv_obj_t * ui_TextButtonSelectPreset4;
extern void ui_event_ButtonToepassen(lv_event_t * e);
extern lv_obj_t * ui_ButtonToepassen;
extern lv_obj_t * ui_TextButtonToepassen;
extern void ui_event_ButtonGoToBewerken(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToBewerken;
extern lv_obj_t * ui_TextButtonGoToBewerken;
extern lv_obj_t * ui_ButtonEmpty;
extern lv_obj_t * ui_TextButtonEmpty;
extern void ui_event_ButtonGoToHome(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToHome;
extern lv_obj_t * ui_TextButtonGoToHome;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

