// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_HeaderHomeBackground;
extern lv_obj_t * ui_HeaderHome;
extern lv_obj_t * ui_InfoModule1;
extern lv_obj_t * ui_HeaderModule1;
extern lv_obj_t * ui_Module1Connected;
extern lv_obj_t * ui_HoogteModule1;
extern lv_obj_t * ui_DoelModule1;
extern lv_obj_t * ui_InfoModule2;
extern lv_obj_t * ui_HeaderModule2;
extern lv_obj_t * ui_Module2Connected;
extern lv_obj_t * ui_HoogteModule2;
extern lv_obj_t * ui_DoelModule2;
extern lv_obj_t * ui_LowerBackground;
extern void ui_event_ButtonSelectModule1(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectModule1;
extern lv_obj_t * ui_TextButtonSelectModule1;
extern void ui_event_ButtonSelectSync(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectSync;
extern lv_obj_t * ui_TextButtonSelectSync;
extern void ui_event_ButtonSelectModule2(lv_event_t * e);
extern lv_obj_t * ui_ButtonSelectModule2;
extern lv_obj_t * ui_TextButtonSelectModule2;
extern void ui_event_ButtonGoToPresets(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToPresets;
extern lv_obj_t * ui_TextButtonGoToPresets;
extern void ui_event_ButtonGoToSettings(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToSettings;
extern lv_obj_t * ui_TextButtonGoToPresets1;
extern void ui_event_ButtonStap(lv_event_t * e);
extern lv_obj_t * ui_ButtonStap;
extern lv_obj_t * ui_TextButtonStap;
extern void ui_event_ButtonKalibreer(lv_event_t * e);
extern lv_obj_t * ui_ButtonKalibreer;
extern lv_obj_t * ui_TextButtonKalibreer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

