// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenPresetEdit = NULL;
lv_obj_t * ui_HeaderBewerkenBackground = NULL;
lv_obj_t * ui_HeaderBewerken = NULL;
lv_obj_t * ui_EditPresetBackground = NULL;
lv_obj_t * ui_EditPreset = NULL;
lv_obj_t * ui_EditCosmeticLine = NULL;
lv_obj_t * ui_EditNamePreset = NULL;
lv_obj_t * ui_EditPresetHoogteM1 = NULL;
lv_obj_t * ui_EditPresetHoogteM2 = NULL;
lv_obj_t * ui_ButtonResetPreset = NULL;
lv_obj_t * ui_TextButtonResetPreset = NULL;
lv_obj_t * ui_ButtonOpslaan = NULL;
lv_obj_t * ui_TextButtonOpslaan = NULL;
lv_obj_t * ui_ButtonVolgende = NULL;
lv_obj_t * ui_TextButtonVolgende = NULL;
lv_obj_t * ui_ButtonVorige = NULL;
lv_obj_t * ui_TextButtonVorige = NULL;
lv_obj_t * ui_ButtonGoToPresets2 = NULL;
lv_obj_t * ui_TextButtonGoToPresets2 = NULL;
lv_obj_t * ui_InsertNameBackground = NULL;
lv_obj_t * ui_InsertNameText = NULL;
lv_obj_t * ui_InsertNameTextArea = NULL;
lv_obj_t * ui_InsertM1Background = NULL;
lv_obj_t * ui_InsertM1Text = NULL;
lv_obj_t * ui_InsertM1TextArea = NULL;
lv_obj_t * ui_InsertM2Background = NULL;
lv_obj_t * ui_InsertM2Text = NULL;
lv_obj_t * ui_InsertM2TextArea = NULL;
lv_obj_t * ui_InsertNameKeyboard = NULL;
lv_obj_t * ui_InsertM1Keyboard = NULL;
lv_obj_t * ui_InsertM2Keyboard = NULL;
// event funtions
void ui_event_ButtonResetPreset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ResetPreset(e);
    }
}

void ui_event_ButtonOpslaan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SavePreset(e);
    }
}

void ui_event_ButtonVolgende(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectNextFunction(e);
    }
}

void ui_event_ButtonVorige(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectPreviousFunction(e);
    }
}

void ui_event_ButtonGoToPresets2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPresetsSelect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPresetsSelect_screen_init);
    }
}

void ui_event_InsertNameTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_InsertNameKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_InsertM1Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_InsertM2Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_InsertM1TextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_InsertM1Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_InsertNameKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_InsertM2Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_InsertM2TextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_InsertM2Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_InsertNameKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_InsertM1Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_InsertNameKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_InsertNameKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_InsertM1Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_InsertM1Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_InsertM2Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_InsertM2Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_ScreenPresetEdit_screen_init(void)
{
    ui_ScreenPresetEdit = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPresetEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderBewerkenBackground = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_HeaderBewerkenBackground, 800);
    lv_obj_set_height(ui_HeaderBewerkenBackground, 50);
    lv_obj_clear_flag(ui_HeaderBewerkenBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_HeaderBewerkenBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaderBewerkenBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_HeaderBewerkenBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_HeaderBewerken = lv_label_create(ui_HeaderBewerkenBackground);
    lv_obj_set_width(ui_HeaderBewerken, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_HeaderBewerken, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_HeaderBewerken, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeaderBewerken, "Bewerken");
    lv_obj_set_style_text_color(ui_HeaderBewerken, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderBewerken, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderBewerken, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditPresetBackground = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_EditPresetBackground, 780);
    lv_obj_set_height(ui_EditPresetBackground, 60);
    lv_obj_set_x(ui_EditPresetBackground, 5);
    lv_obj_set_y(ui_EditPresetBackground, 70);
    lv_obj_add_flag(ui_EditPresetBackground, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_EditPresetBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_EditPresetBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_EditPresetBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_EditPreset = lv_label_create(ui_EditPresetBackground);
    lv_obj_set_width(ui_EditPreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EditPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EditPreset, 1);
    lv_obj_set_y(ui_EditPreset, 5);
    lv_label_set_text(ui_EditPreset, "1");
    ui_object_set_themeable_style_property(ui_EditPreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_EditPreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_EditPreset, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditCosmeticLine = lv_btn_create(ui_EditPresetBackground);
    lv_obj_set_width(ui_EditCosmeticLine, 5);
    lv_obj_set_height(ui_EditCosmeticLine, 50);
    lv_obj_set_x(ui_EditCosmeticLine, 42);
    lv_obj_set_y(ui_EditCosmeticLine, -6);
    lv_obj_clear_flag(ui_EditCosmeticLine,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_EditCosmeticLine, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_EditCosmeticLine, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_EditCosmeticLine, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Grey);

    ui_EditNamePreset = lv_label_create(ui_EditPresetBackground);
    lv_obj_set_width(ui_EditNamePreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EditNamePreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EditNamePreset, 55);
    lv_obj_set_y(ui_EditNamePreset, -2);
    lv_label_set_text(ui_EditNamePreset, "Placeholder_NamePreset1");
    lv_obj_set_style_text_color(ui_EditNamePreset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EditNamePreset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EditPresetHoogteM1 = lv_label_create(ui_EditPresetBackground);
    lv_obj_set_width(ui_EditPresetHoogteM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EditPresetHoogteM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EditPresetHoogteM1, 55);
    lv_obj_set_y(ui_EditPresetHoogteM1, 20);
    lv_label_set_text(ui_EditPresetHoogteM1, "Placeholder_Preset1HoogteM1");

    ui_EditPresetHoogteM2 = lv_label_create(ui_EditPresetBackground);
    lv_obj_set_width(ui_EditPresetHoogteM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EditPresetHoogteM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EditPresetHoogteM2, 448);
    lv_obj_set_y(ui_EditPresetHoogteM2, 20);
    lv_label_set_text(ui_EditPresetHoogteM2, "Placeholder_Preset1HoogteM2");

    ui_ButtonResetPreset = lv_btn_create(ui_EditPresetBackground);
    lv_obj_set_width(ui_ButtonResetPreset, 150);
    lv_obj_set_height(ui_ButtonResetPreset, 50);
    lv_obj_set_x(ui_ButtonResetPreset, 595);
    lv_obj_set_y(ui_ButtonResetPreset, -6);
    lv_obj_add_flag(ui_ButtonResetPreset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonResetPreset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonResetPreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonResetPreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonResetPreset = lv_label_create(ui_ButtonResetPreset);
    lv_obj_set_width(ui_TextButtonResetPreset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonResetPreset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonResetPreset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonResetPreset, "Reset");
    ui_object_set_themeable_style_property(ui_TextButtonResetPreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonResetPreset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_ButtonOpslaan = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_ButtonOpslaan, 200);
    lv_obj_set_height(ui_ButtonOpslaan, 57);
    lv_obj_set_x(ui_ButtonOpslaan, 0);
    lv_obj_set_y(ui_ButtonOpslaan, 423);
    lv_obj_add_flag(ui_ButtonOpslaan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonOpslaan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonOpslaan, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonOpslaan, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonOpslaan = lv_label_create(ui_ButtonOpslaan);
    lv_obj_set_width(ui_TextButtonOpslaan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonOpslaan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonOpslaan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonOpslaan, "Opslaan");
    ui_object_set_themeable_style_property(ui_TextButtonOpslaan, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonOpslaan, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonOpslaan, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonVolgende = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_ButtonVolgende, 200);
    lv_obj_set_height(ui_ButtonVolgende, 57);
    lv_obj_set_x(ui_ButtonVolgende, 200);
    lv_obj_set_y(ui_ButtonVolgende, 423);
    lv_obj_add_flag(ui_ButtonVolgende, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonVolgende, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonVolgende, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonVolgende, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonVolgende = lv_label_create(ui_ButtonVolgende);
    lv_obj_set_width(ui_TextButtonVolgende, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonVolgende, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonVolgende, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonVolgende, "Volgende");
    ui_object_set_themeable_style_property(ui_TextButtonVolgende, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonVolgende, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonVolgende, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonVorige = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_ButtonVorige, 200);
    lv_obj_set_height(ui_ButtonVorige, 57);
    lv_obj_set_x(ui_ButtonVorige, 400);
    lv_obj_set_y(ui_ButtonVorige, 423);
    lv_obj_add_flag(ui_ButtonVorige, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonVorige, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonVorige, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonVorige, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonVorige = lv_label_create(ui_ButtonVorige);
    lv_obj_set_width(ui_TextButtonVorige, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonVorige, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonVorige, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonVorige, "Vorige");
    ui_object_set_themeable_style_property(ui_TextButtonVorige, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonVorige, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonVorige, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToPresets2 = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_ButtonGoToPresets2, 200);
    lv_obj_set_height(ui_ButtonGoToPresets2, 57);
    lv_obj_set_x(ui_ButtonGoToPresets2, 600);
    lv_obj_set_y(ui_ButtonGoToPresets2, 423);
    lv_obj_add_flag(ui_ButtonGoToPresets2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToPresets2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonGoToPresets2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_ButtonGoToPresets2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_TextButtonGoToPresets2 = lv_label_create(ui_ButtonGoToPresets2);
    lv_obj_set_width(ui_TextButtonGoToPresets2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonGoToPresets2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonGoToPresets2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonGoToPresets2, "Terug");
    lv_obj_set_style_text_color(ui_TextButtonGoToPresets2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextButtonGoToPresets2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonGoToPresets2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InsertNameBackground = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_InsertNameBackground, 290);
    lv_obj_set_height(ui_InsertNameBackground, 50);
    lv_obj_set_x(ui_InsertNameBackground, 10);
    lv_obj_set_y(ui_InsertNameBackground, 133);
    lv_obj_add_flag(ui_InsertNameBackground, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InsertNameBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_InsertNameBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_InsertNameBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_InsertNameText = lv_label_create(ui_InsertNameBackground);
    lv_obj_set_width(ui_InsertNameText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InsertNameText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InsertNameText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_InsertNameText, "Naam:");
    ui_object_set_themeable_style_property(ui_InsertNameText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_InsertNameText, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_InsertNameTextArea = lv_textarea_create(ui_InsertNameBackground);
    lv_obj_set_width(ui_InsertNameTextArea, 215);
    lv_obj_set_height(ui_InsertNameTextArea, 40);
    lv_obj_set_x(ui_InsertNameTextArea, 50);
    lv_obj_set_y(ui_InsertNameTextArea, -6);
    lv_textarea_set_accepted_chars(ui_InsertNameTextArea,
                                   "0123456789 abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ");
    lv_textarea_set_placeholder_text(ui_InsertNameTextArea, "PresetX");

    ui_InsertM1Background = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_InsertM1Background, 225);
    lv_obj_set_height(ui_InsertM1Background, 50);
    lv_obj_set_x(ui_InsertM1Background, 320);
    lv_obj_set_y(ui_InsertM1Background, 133);
    lv_obj_add_flag(ui_InsertM1Background, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InsertM1Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_InsertM1Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_InsertM1Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_InsertM1Text = lv_label_create(ui_InsertM1Background);
    lv_obj_set_width(ui_InsertM1Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InsertM1Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InsertM1Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_InsertM1Text, "M1:");
    ui_object_set_themeable_style_property(ui_InsertM1Text, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_InsertM1Text, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_InsertM1TextArea = lv_textarea_create(ui_InsertM1Background);
    lv_obj_set_width(ui_InsertM1TextArea, 150);
    lv_obj_set_height(ui_InsertM1TextArea, 40);
    lv_obj_set_x(ui_InsertM1TextArea, 50);
    lv_obj_set_y(ui_InsertM1TextArea, -6);
    lv_textarea_set_accepted_chars(ui_InsertM1TextArea, "0123456789,.");
    lv_textarea_set_placeholder_text(ui_InsertM1TextArea, "--,-mm");

    ui_InsertM2Background = lv_btn_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_InsertM2Background, 225);
    lv_obj_set_height(ui_InsertM2Background, 50);
    lv_obj_set_x(ui_InsertM2Background, 565);
    lv_obj_set_y(ui_InsertM2Background, 133);
    lv_obj_add_flag(ui_InsertM2Background, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InsertM2Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_InsertM2Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_InsertM2Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_InsertM2Text = lv_label_create(ui_InsertM2Background);
    lv_obj_set_width(ui_InsertM2Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InsertM2Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InsertM2Text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_InsertM2Text, "M2:");
    ui_object_set_themeable_style_property(ui_InsertM2Text, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_InsertM2Text, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_InsertM2TextArea = lv_textarea_create(ui_InsertM2Background);
    lv_obj_set_width(ui_InsertM2TextArea, 150);
    lv_obj_set_height(ui_InsertM2TextArea, 40);
    lv_obj_set_x(ui_InsertM2TextArea, 50);
    lv_obj_set_y(ui_InsertM2TextArea, -6);
    lv_textarea_set_accepted_chars(ui_InsertM2TextArea, "0123456789,.");
    lv_textarea_set_placeholder_text(ui_InsertM2TextArea, "--,-mm");

    ui_InsertNameKeyboard = lv_keyboard_create(ui_ScreenPresetEdit);
    lv_obj_set_width(ui_InsertNameKeyboard, 800);
    lv_obj_set_height(ui_InsertNameKeyboard, 240);
    lv_obj_set_x(ui_InsertNameKeyboard, 0);
    lv_obj_set_y(ui_InsertNameKeyboard, -57);
    lv_obj_set_align(ui_InsertNameKeyboard, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_InsertNameKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_InsertM1Keyboard = lv_keyboard_create(ui_ScreenPresetEdit);
    lv_keyboard_set_mode(ui_InsertM1Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_InsertM1Keyboard, 800);
    lv_obj_set_height(ui_InsertM1Keyboard, 240);
    lv_obj_set_x(ui_InsertM1Keyboard, 0);
    lv_obj_set_y(ui_InsertM1Keyboard, -57);
    lv_obj_set_align(ui_InsertM1Keyboard, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_InsertM1Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_InsertM2Keyboard = lv_keyboard_create(ui_ScreenPresetEdit);
    lv_keyboard_set_mode(ui_InsertM2Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_InsertM2Keyboard, 800);
    lv_obj_set_height(ui_InsertM2Keyboard, 240);
    lv_obj_set_x(ui_InsertM2Keyboard, 0);
    lv_obj_set_y(ui_InsertM2Keyboard, -57);
    lv_obj_set_align(ui_InsertM2Keyboard, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_InsertM2Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_ButtonResetPreset, ui_event_ButtonResetPreset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonOpslaan, ui_event_ButtonOpslaan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonVolgende, ui_event_ButtonVolgende, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonVorige, ui_event_ButtonVorige, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToPresets2, ui_event_ButtonGoToPresets2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InsertNameTextArea, ui_event_InsertNameTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InsertM1TextArea, ui_event_InsertM1TextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InsertM2TextArea, ui_event_InsertM2TextArea, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_InsertNameKeyboard, ui_InsertNameTextArea);
    lv_obj_add_event_cb(ui_InsertNameKeyboard, ui_event_InsertNameKeyboard, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_InsertM1Keyboard, ui_InsertM1TextArea);
    lv_obj_add_event_cb(ui_InsertM1Keyboard, ui_event_InsertM1Keyboard, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_InsertM2Keyboard, ui_InsertM2TextArea);
    lv_obj_add_event_cb(ui_InsertM2Keyboard, ui_event_InsertM2Keyboard, LV_EVENT_ALL, NULL);

}

void ui_ScreenPresetEdit_screen_destroy(void)
{
    if(ui_ScreenPresetEdit) lv_obj_del(ui_ScreenPresetEdit);

    // NULL screen variables
    ui_ScreenPresetEdit = NULL;
    ui_HeaderBewerkenBackground = NULL;
    ui_HeaderBewerken = NULL;
    ui_EditPresetBackground = NULL;
    ui_EditPreset = NULL;
    ui_EditCosmeticLine = NULL;
    ui_EditNamePreset = NULL;
    ui_EditPresetHoogteM1 = NULL;
    ui_EditPresetHoogteM2 = NULL;
    ui_ButtonResetPreset = NULL;
    ui_TextButtonResetPreset = NULL;
    ui_ButtonOpslaan = NULL;
    ui_TextButtonOpslaan = NULL;
    ui_ButtonVolgende = NULL;
    ui_TextButtonVolgende = NULL;
    ui_ButtonVorige = NULL;
    ui_TextButtonVorige = NULL;
    ui_ButtonGoToPresets2 = NULL;
    ui_TextButtonGoToPresets2 = NULL;
    ui_InsertNameBackground = NULL;
    ui_InsertNameText = NULL;
    ui_InsertNameTextArea = NULL;
    ui_InsertM1Background = NULL;
    ui_InsertM1Text = NULL;
    ui_InsertM1TextArea = NULL;
    ui_InsertM2Background = NULL;
    ui_InsertM2Text = NULL;
    ui_InsertM2TextArea = NULL;
    ui_InsertNameKeyboard = NULL;
    ui_InsertM1Keyboard = NULL;
    ui_InsertM2Keyboard = NULL;

}
