// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenPresetselect = NULL;
lv_obj_t * ui_PSHeaderBg = NULL;
lv_obj_t * ui_PIMMLogo_PS = NULL;
lv_obj_t * ui_TitelPS = NULL;
lv_obj_t * ui_PSHintBg = NULL;
lv_obj_t * ui_PSHint = NULL;
lv_obj_t * ui_PSCard1Bg = NULL;
lv_obj_t * ui_PSCardNr1 = NULL;
lv_obj_t * ui_PSCardDiv1 = NULL;
lv_obj_t * ui_PSCardName1 = NULL;
lv_obj_t * ui_PSCardM11 = NULL;
lv_obj_t * ui_PSCardM21 = NULL;
lv_obj_t * ui_PSSelBtn1 = NULL;
lv_obj_t * ui_PSSelBtn1Text = NULL;
lv_obj_t * ui_PSCard2Bg = NULL;
lv_obj_t * ui_PSCardNr2 = NULL;
lv_obj_t * ui_PSCardDiv2 = NULL;
lv_obj_t * ui_PSCardName2 = NULL;
lv_obj_t * ui_PSCardM12 = NULL;
lv_obj_t * ui_PSCardM22 = NULL;
lv_obj_t * ui_PSSelBtn2 = NULL;
lv_obj_t * ui_PSSelBtn2Text = NULL;
lv_obj_t * ui_PSCard3Bg = NULL;
lv_obj_t * ui_PSCardNr3 = NULL;
lv_obj_t * ui_PSCardDiv3 = NULL;
lv_obj_t * ui_PSCardName3 = NULL;
lv_obj_t * ui_PSCardM1_3 = NULL;
lv_obj_t * ui_PSCardM23 = NULL;
lv_obj_t * ui_PSSelBtn3 = NULL;
lv_obj_t * ui_PSSelBtn3Text = NULL;
lv_obj_t * ui_PSCard4Bg = NULL;
lv_obj_t * ui_PSCardNr4 = NULL;
lv_obj_t * ui_PSCardDiv4 = NULL;
lv_obj_t * ui_PSCardName4 = NULL;
lv_obj_t * ui_PSCardM1_4 = NULL;
lv_obj_t * ui_PSCardM24 = NULL;
lv_obj_t * ui_PSSelBtn4 = NULL;
lv_obj_t * ui_PSSelBtn4Text = NULL;
lv_obj_t * ui_PSSelInfoBg = NULL;
lv_obj_t * ui_PSSelInfo = NULL;
lv_obj_t * ui_PSBtnBarBg = NULL;
lv_obj_t * ui_PSBtn1 = NULL;
lv_obj_t * ui_PSBtn1Text = NULL;
lv_obj_t * ui_PSBtn2 = NULL;
lv_obj_t * ui_PSBtn2Text = NULL;
lv_obj_t * ui_PSBtn3 = NULL;
lv_obj_t * ui_PSBtn3Text = NULL;
lv_obj_t * ui_PSBtn4 = NULL;
lv_obj_t * ui_PSBtn4Text = NULL;
// event funtions
void ui_event_PSSelBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_preset1(e);
    }
}

void ui_event_PSSelBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_preset2(e);
    }
}

void ui_event_PSSelBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_preset3(e);
    }
}

void ui_event_PSSelBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_preset4(e);
    }
}

void ui_event_PSBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_apply_preset(e);
    }
}

void ui_event_PSBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPresetedit, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenPresetedit_screen_init);
    }
}

void ui_event_PSBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_rename_preset(e);
    }
}

void ui_event_PSBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenHome_screen_init);
    }
}

// build funtions

void ui_ScreenPresetselect_screen_init(void)
{
    ui_ScreenPresetselect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPresetselect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PSHeaderBg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSHeaderBg, 800);
    lv_obj_set_height(ui_PSHeaderBg, 50);
    lv_label_set_text(ui_PSHeaderBg, "");
    lv_obj_set_style_text_color(ui_PSHeaderBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSHeaderBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSHeaderBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSHeaderBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSHeaderBg, lv_color_hex(0x002D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIMMLogo_PS = lv_img_create(ui_ScreenPresetselect);
    lv_img_set_src(ui_PIMMLogo_PS, &ui_img_pimm_logo_png);
    lv_obj_set_width(ui_PIMMLogo_PS, 1);
    lv_obj_set_height(ui_PIMMLogo_PS, 1);
    lv_obj_set_x(ui_PIMMLogo_PS, 1);
    lv_obj_set_y(ui_PIMMLogo_PS, 0);
    lv_obj_add_flag(ui_PIMMLogo_PS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PIMMLogo_PS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitelPS = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_TitelPS, 1);
    lv_obj_set_height(ui_TitelPS, 1);
    lv_obj_set_align(ui_TitelPS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitelPS, "PRESETS");
    lv_obj_set_style_text_color(ui_TitelPS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitelPS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitelPS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TitelPS, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitelPS, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitelPS, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitelPS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitelPS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitelPS, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitelPS, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitelPS, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitelPS, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSHintBg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSHintBg, 800);
    lv_obj_set_height(ui_PSHintBg, 30);
    lv_obj_set_x(ui_PSHintBg, 0);
    lv_obj_set_y(ui_PSHintBg, 54);
    lv_label_set_text(ui_PSHintBg, "");
    lv_obj_set_style_text_color(ui_PSHintBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSHintBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSHintBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSHintBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSHintBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSHintBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSHintBg, lv_color_hex(0x0C1628), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSHintBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSHintBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSHintBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSHintBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSHintBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSHint = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSHint, 788);
    lv_obj_set_height(ui_PSHint, 26);
    lv_obj_set_x(ui_PSHint, 6);
    lv_obj_set_y(ui_PSHint, 56);
    lv_label_set_text(ui_PSHint, "Selecteer een preset  –  druk Toepassen om te activeren");
    lv_obj_set_style_text_color(ui_PSHint, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSHint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSHint, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSHint, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSHint, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSHint, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSHint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSHint, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSHint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSHint, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSHint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCard1Bg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCard1Bg, 780);
    lv_obj_set_height(ui_PSCard1Bg, 76);
    lv_obj_set_x(ui_PSCard1Bg, 10);
    lv_obj_set_y(ui_PSCard1Bg, 88);
    lv_label_set_text(ui_PSCard1Bg, "");
    lv_obj_set_style_text_color(ui_PSCard1Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCard1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCard1Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCard1Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCard1Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCard1Bg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCard1Bg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCard1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCard1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCard1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCard1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCard1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardNr1 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardNr1, 52);
    lv_obj_set_height(ui_PSCardNr1, 56);
    lv_obj_set_x(ui_PSCardNr1, 16);
    lv_obj_set_y(ui_PSCardNr1, 98);
    lv_label_set_text(ui_PSCardNr1, "1");
    lv_obj_set_style_text_color(ui_PSCardNr1, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardNr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardNr1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardNr1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardNr1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardNr1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardNr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardDiv1 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardDiv1, 3);
    lv_obj_set_height(ui_PSCardDiv1, 56);
    lv_obj_set_x(ui_PSCardDiv1, 74);
    lv_obj_set_y(ui_PSCardDiv1, 98);
    lv_label_set_text(ui_PSCardDiv1, "");
    lv_obj_set_style_text_color(ui_PSCardDiv1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardDiv1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardDiv1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardDiv1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardDiv1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardDiv1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardDiv1, lv_color_hex(0x283C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardDiv1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardDiv1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardDiv1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardDiv1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardDiv1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardName1 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardName1, 280);
    lv_obj_set_height(ui_PSCardName1, 28);
    lv_obj_set_x(ui_PSCardName1, 86);
    lv_obj_set_y(ui_PSCardName1, 98);
    lv_label_set_text(ui_PSCardName1, "Preset 1");
    lv_obj_set_style_text_color(ui_PSCardName1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardName1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardName1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardName1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardName1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardName1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardName1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardName1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardName1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardName1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM11 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM11, 260);
    lv_obj_set_height(ui_PSCardM11, 22);
    lv_obj_set_x(ui_PSCardM11, 86);
    lv_obj_set_y(ui_PSCardM11, 130);
    lv_label_set_text(ui_PSCardM11, "M1:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM11, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM11, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM11, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM11, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM11, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM11, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM11, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM21 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM21, 220);
    lv_obj_set_height(ui_PSCardM21, 22);
    lv_obj_set_x(ui_PSCardM21, 350);
    lv_obj_set_y(ui_PSCardM21, 130);
    lv_label_set_text(ui_PSCardM21, "M2:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM21, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM21, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM21, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM21, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM21, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM21, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn1 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSSelBtn1, 200);
    lv_obj_set_height(ui_PSSelBtn1, 52);
    lv_obj_set_x(ui_PSSelBtn1, 580);
    lv_obj_set_y(ui_PSSelBtn1, 100);
    lv_obj_add_flag(ui_PSSelBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSSelBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSSelBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn1, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn1Text = lv_label_create(ui_PSSelBtn1);
    lv_obj_set_width(ui_PSSelBtn1Text, 200);
    lv_obj_set_height(ui_PSSelBtn1Text, 52);
    lv_obj_set_align(ui_PSSelBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSSelBtn1Text, "Selecteer");
    lv_obj_set_style_text_color(ui_PSSelBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSSelBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSSelBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSSelBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSSelBtn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSSelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSSelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSSelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSSelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSSelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCard2Bg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCard2Bg, 780);
    lv_obj_set_height(ui_PSCard2Bg, 76);
    lv_obj_set_x(ui_PSCard2Bg, 10);
    lv_obj_set_y(ui_PSCard2Bg, 171);
    lv_label_set_text(ui_PSCard2Bg, "");
    lv_obj_set_style_text_color(ui_PSCard2Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCard2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCard2Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCard2Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCard2Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCard2Bg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCard2Bg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCard2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCard2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCard2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCard2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCard2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardNr2 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardNr2, 52);
    lv_obj_set_height(ui_PSCardNr2, 56);
    lv_obj_set_x(ui_PSCardNr2, 16);
    lv_obj_set_y(ui_PSCardNr2, 181);
    lv_label_set_text(ui_PSCardNr2, "2");
    lv_obj_set_style_text_color(ui_PSCardNr2, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardNr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardNr2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardNr2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardNr2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardNr2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardNr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardDiv2 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardDiv2, 3);
    lv_obj_set_height(ui_PSCardDiv2, 56);
    lv_obj_set_x(ui_PSCardDiv2, 74);
    lv_obj_set_y(ui_PSCardDiv2, 181);
    lv_label_set_text(ui_PSCardDiv2, "");
    lv_obj_set_style_text_color(ui_PSCardDiv2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardDiv2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardDiv2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardDiv2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardDiv2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardDiv2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardDiv2, lv_color_hex(0x283C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardDiv2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardDiv2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardDiv2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardDiv2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardDiv2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardName2 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardName2, 280);
    lv_obj_set_height(ui_PSCardName2, 28);
    lv_obj_set_x(ui_PSCardName2, 86);
    lv_obj_set_y(ui_PSCardName2, 181);
    lv_label_set_text(ui_PSCardName2, "Preset 2");
    lv_obj_set_style_text_color(ui_PSCardName2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardName2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardName2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardName2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardName2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardName2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardName2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardName2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardName2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardName2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM12 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM12, 260);
    lv_obj_set_height(ui_PSCardM12, 22);
    lv_obj_set_x(ui_PSCardM12, 86);
    lv_obj_set_y(ui_PSCardM12, 213);
    lv_label_set_text(ui_PSCardM12, "M1:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM12, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM12, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM12, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM12, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM12, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM12, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM22 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM22, 220);
    lv_obj_set_height(ui_PSCardM22, 22);
    lv_obj_set_x(ui_PSCardM22, 350);
    lv_obj_set_y(ui_PSCardM22, 213);
    lv_label_set_text(ui_PSCardM22, "M2:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM22, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM22, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM22, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM22, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM22, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM22, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn2 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSSelBtn2, 200);
    lv_obj_set_height(ui_PSSelBtn2, 52);
    lv_obj_set_x(ui_PSSelBtn2, 580);
    lv_obj_set_y(ui_PSSelBtn2, 183);
    lv_obj_add_flag(ui_PSSelBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSSelBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSSelBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn2Text = lv_label_create(ui_PSSelBtn2);
    lv_obj_set_width(ui_PSSelBtn2Text, 200);
    lv_obj_set_height(ui_PSSelBtn2Text, 52);
    lv_obj_set_align(ui_PSSelBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSSelBtn2Text, "Selecteer");
    lv_obj_set_style_text_color(ui_PSSelBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSSelBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSSelBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSSelBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSSelBtn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSSelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSSelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSSelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSSelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSSelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCard3Bg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCard3Bg, 780);
    lv_obj_set_height(ui_PSCard3Bg, 76);
    lv_obj_set_x(ui_PSCard3Bg, 10);
    lv_obj_set_y(ui_PSCard3Bg, 254);
    lv_label_set_text(ui_PSCard3Bg, "");
    lv_obj_set_style_text_color(ui_PSCard3Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCard3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCard3Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCard3Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCard3Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCard3Bg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCard3Bg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCard3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCard3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCard3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCard3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCard3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardNr3 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardNr3, 52);
    lv_obj_set_height(ui_PSCardNr3, 56);
    lv_obj_set_x(ui_PSCardNr3, 16);
    lv_obj_set_y(ui_PSCardNr3, 264);
    lv_label_set_text(ui_PSCardNr3, "3");
    lv_obj_set_style_text_color(ui_PSCardNr3, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardNr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardNr3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardNr3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardNr3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardNr3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardNr3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardDiv3 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardDiv3, 3);
    lv_obj_set_height(ui_PSCardDiv3, 56);
    lv_obj_set_x(ui_PSCardDiv3, 74);
    lv_obj_set_y(ui_PSCardDiv3, 264);
    lv_label_set_text(ui_PSCardDiv3, "");
    lv_obj_set_style_text_color(ui_PSCardDiv3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardDiv3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardDiv3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardDiv3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardDiv3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardDiv3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardDiv3, lv_color_hex(0x283C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardDiv3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardDiv3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardDiv3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardDiv3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardDiv3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardName3 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardName3, 280);
    lv_obj_set_height(ui_PSCardName3, 28);
    lv_obj_set_x(ui_PSCardName3, 86);
    lv_obj_set_y(ui_PSCardName3, 264);
    lv_label_set_text(ui_PSCardName3, "Preset 3");
    lv_obj_set_style_text_color(ui_PSCardName3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardName3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardName3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardName3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardName3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardName3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardName3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardName3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardName3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardName3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardName3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM1_3 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM1_3, 260);
    lv_obj_set_height(ui_PSCardM1_3, 22);
    lv_obj_set_x(ui_PSCardM1_3, 86);
    lv_obj_set_y(ui_PSCardM1_3, 296);
    lv_label_set_text(ui_PSCardM1_3, "M1:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM1_3, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM1_3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM1_3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM1_3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM1_3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM1_3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM1_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM1_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM1_3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM1_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM1_3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM1_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM23 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM23, 220);
    lv_obj_set_height(ui_PSCardM23, 22);
    lv_obj_set_x(ui_PSCardM23, 350);
    lv_obj_set_y(ui_PSCardM23, 296);
    lv_label_set_text(ui_PSCardM23, "M2:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM23, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM23, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM23, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM23, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM23, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM23, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM23, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM23, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn3 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSSelBtn3, 200);
    lv_obj_set_height(ui_PSSelBtn3, 52);
    lv_obj_set_x(ui_PSSelBtn3, 580);
    lv_obj_set_y(ui_PSSelBtn3, 266);
    lv_obj_add_flag(ui_PSSelBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSSelBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSSelBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn3, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn3Text = lv_label_create(ui_PSSelBtn3);
    lv_obj_set_width(ui_PSSelBtn3Text, 200);
    lv_obj_set_height(ui_PSSelBtn3Text, 52);
    lv_obj_set_align(ui_PSSelBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSSelBtn3Text, "Selecteer");
    lv_obj_set_style_text_color(ui_PSSelBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSSelBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSSelBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSSelBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSSelBtn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSSelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSSelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSSelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSSelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSSelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCard4Bg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCard4Bg, 780);
    lv_obj_set_height(ui_PSCard4Bg, 76);
    lv_obj_set_x(ui_PSCard4Bg, 10);
    lv_obj_set_y(ui_PSCard4Bg, 337);
    lv_label_set_text(ui_PSCard4Bg, "");
    lv_obj_set_style_text_color(ui_PSCard4Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCard4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCard4Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCard4Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCard4Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCard4Bg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCard4Bg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCard4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCard4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCard4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCard4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCard4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardNr4 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardNr4, 52);
    lv_obj_set_height(ui_PSCardNr4, 56);
    lv_obj_set_x(ui_PSCardNr4, 16);
    lv_obj_set_y(ui_PSCardNr4, 347);
    lv_label_set_text(ui_PSCardNr4, "4");
    lv_obj_set_style_text_color(ui_PSCardNr4, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardNr4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardNr4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardNr4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardNr4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardNr4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardNr4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardDiv4 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardDiv4, 3);
    lv_obj_set_height(ui_PSCardDiv4, 56);
    lv_obj_set_x(ui_PSCardDiv4, 74);
    lv_obj_set_y(ui_PSCardDiv4, 347);
    lv_label_set_text(ui_PSCardDiv4, "");
    lv_obj_set_style_text_color(ui_PSCardDiv4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardDiv4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardDiv4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardDiv4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardDiv4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardDiv4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardDiv4, lv_color_hex(0x283C5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardDiv4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardDiv4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardDiv4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardDiv4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardDiv4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardName4 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardName4, 280);
    lv_obj_set_height(ui_PSCardName4, 28);
    lv_obj_set_x(ui_PSCardName4, 86);
    lv_obj_set_y(ui_PSCardName4, 347);
    lv_label_set_text(ui_PSCardName4, "Preset 4");
    lv_obj_set_style_text_color(ui_PSCardName4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardName4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardName4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardName4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardName4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardName4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardName4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardName4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardName4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardName4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardName4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardName4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM1_4 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM1_4, 260);
    lv_obj_set_height(ui_PSCardM1_4, 22);
    lv_obj_set_x(ui_PSCardM1_4, 86);
    lv_obj_set_y(ui_PSCardM1_4, 379);
    lv_label_set_text(ui_PSCardM1_4, "M1:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM1_4, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM1_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM1_4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM1_4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM1_4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM1_4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM1_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM1_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM1_4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM1_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM1_4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM1_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSCardM24 = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSCardM24, 220);
    lv_obj_set_height(ui_PSCardM24, 22);
    lv_obj_set_x(ui_PSCardM24, 350);
    lv_obj_set_y(ui_PSCardM24, 379);
    lv_label_set_text(ui_PSCardM24, "M2:  --.- mm");
    lv_obj_set_style_text_color(ui_PSCardM24, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSCardM24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSCardM24, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSCardM24, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSCardM24, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSCardM24, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSCardM24, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSCardM24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSCardM24, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSCardM24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSCardM24, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSCardM24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn4 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSSelBtn4, 200);
    lv_obj_set_height(ui_PSSelBtn4, 52);
    lv_obj_set_x(ui_PSSelBtn4, 580);
    lv_obj_set_y(ui_PSSelBtn4, 349);
    lv_obj_add_flag(ui_PSSelBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSSelBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSSelBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn4, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelBtn4Text = lv_label_create(ui_PSSelBtn4);
    lv_obj_set_width(ui_PSSelBtn4Text, 200);
    lv_obj_set_height(ui_PSSelBtn4Text, 52);
    lv_obj_set_align(ui_PSSelBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSSelBtn4Text, "Selecteer");
    lv_obj_set_style_text_color(ui_PSSelBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSSelBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSSelBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSSelBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSSelBtn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSSelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSSelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSSelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSSelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSSelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelInfoBg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSSelInfoBg, 780);
    lv_obj_set_height(ui_PSSelInfoBg, 22);
    lv_obj_set_x(ui_PSSelInfoBg, 10);
    lv_obj_set_y(ui_PSSelInfoBg, 393);
    lv_label_set_text(ui_PSSelInfoBg, "");
    lv_obj_set_style_text_color(ui_PSSelInfoBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSSelInfoBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSSelInfoBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSSelInfoBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSSelInfoBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSSelInfoBg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelInfoBg, lv_color_hex(0x0E1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelInfoBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSSelInfoBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSSelInfoBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSSelInfoBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSSelInfoBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSSelInfo = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSSelInfo, 770);
    lv_obj_set_height(ui_PSSelInfo, 18);
    lv_obj_set_x(ui_PSSelInfo, 14);
    lv_obj_set_y(ui_PSSelInfo, 395);
    lv_label_set_text(ui_PSSelInfo, "Huidig actief:  –  (geen)");
    lv_obj_set_style_text_color(ui_PSSelInfo, lv_color_hex(0xFFC850), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSSelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSSelInfo, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSSelInfo, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSSelInfo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSSelInfo, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSSelInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSSelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSSelInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSSelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSSelInfo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSSelInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtnBarBg = lv_label_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSBtnBarBg, 800);
    lv_obj_set_height(ui_PSBtnBarBg, 60);
    lv_obj_set_x(ui_PSBtnBarBg, 0);
    lv_obj_set_y(ui_PSBtnBarBg, 420);
    lv_label_set_text(ui_PSBtnBarBg, "");
    lv_obj_set_style_text_color(ui_PSBtnBarBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSBtnBarBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSBtnBarBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSBtnBarBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtnBarBg, lv_color_hex(0x080F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn1 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSBtn1, 200);
    lv_obj_set_height(ui_PSBtn1, 57);
    lv_obj_set_x(ui_PSBtn1, 0);
    lv_obj_set_y(ui_PSBtn1, 421);
    lv_obj_add_flag(ui_PSBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn1, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn1Text = lv_label_create(ui_PSBtn1);
    lv_obj_set_width(ui_PSBtn1Text, 200);
    lv_obj_set_height(ui_PSBtn1Text, 57);
    lv_obj_set_align(ui_PSBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSBtn1Text, "Toepassen");
    lv_obj_set_style_text_color(ui_PSBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSBtn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn2 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSBtn2, 200);
    lv_obj_set_height(ui_PSBtn2, 57);
    lv_obj_set_x(ui_PSBtn2, 200);
    lv_obj_set_y(ui_PSBtn2, 421);
    lv_obj_add_flag(ui_PSBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn2Text = lv_label_create(ui_PSBtn2);
    lv_obj_set_width(ui_PSBtn2Text, 200);
    lv_obj_set_height(ui_PSBtn2Text, 57);
    lv_obj_set_align(ui_PSBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSBtn2Text, "Bewerken");
    lv_obj_set_style_text_color(ui_PSBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSBtn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn3 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSBtn3, 200);
    lv_obj_set_height(ui_PSBtn3, 57);
    lv_obj_set_x(ui_PSBtn3, 400);
    lv_obj_set_y(ui_PSBtn3, 421);
    lv_obj_add_flag(ui_PSBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn3, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn3Text = lv_label_create(ui_PSBtn3);
    lv_obj_set_width(ui_PSBtn3Text, 200);
    lv_obj_set_height(ui_PSBtn3Text, 57);
    lv_obj_set_align(ui_PSBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSBtn3Text, "Hernoemen");
    lv_obj_set_style_text_color(ui_PSBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSBtn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn4 = lv_btn_create(ui_ScreenPresetselect);
    lv_obj_set_width(ui_PSBtn4, 200);
    lv_obj_set_height(ui_PSBtn4, 57);
    lv_obj_set_x(ui_PSBtn4, 600);
    lv_obj_set_y(ui_PSBtn4, 421);
    lv_obj_add_flag(ui_PSBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PSBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PSBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn4, lv_color_hex(0x233755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSBtn4Text = lv_label_create(ui_PSBtn4);
    lv_obj_set_width(ui_PSBtn4Text, 200);
    lv_obj_set_height(ui_PSBtn4Text, 57);
    lv_obj_set_align(ui_PSBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PSBtn4Text, "Terug");
    lv_obj_set_style_text_color(ui_PSBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PSBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PSBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PSBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PSBtn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PSBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PSBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PSBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PSBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PSBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PSBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PSBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PSSelBtn1, ui_event_PSSelBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSSelBtn2, ui_event_PSSelBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSSelBtn3, ui_event_PSSelBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSSelBtn4, ui_event_PSSelBtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSBtn1, ui_event_PSBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSBtn2, ui_event_PSBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSBtn3, ui_event_PSBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PSBtn4, ui_event_PSBtn4, LV_EVENT_ALL, NULL);

}

void ui_ScreenPresetselect_screen_destroy(void)
{
    if(ui_ScreenPresetselect) lv_obj_del(ui_ScreenPresetselect);

    // NULL screen variables
    ui_ScreenPresetselect = NULL;
    ui_PSHeaderBg = NULL;
    ui_PIMMLogo_PS = NULL;
    ui_TitelPS = NULL;
    ui_PSHintBg = NULL;
    ui_PSHint = NULL;
    ui_PSCard1Bg = NULL;
    ui_PSCardNr1 = NULL;
    ui_PSCardDiv1 = NULL;
    ui_PSCardName1 = NULL;
    ui_PSCardM11 = NULL;
    ui_PSCardM21 = NULL;
    ui_PSSelBtn1 = NULL;
    ui_PSSelBtn1Text = NULL;
    ui_PSCard2Bg = NULL;
    ui_PSCardNr2 = NULL;
    ui_PSCardDiv2 = NULL;
    ui_PSCardName2 = NULL;
    ui_PSCardM12 = NULL;
    ui_PSCardM22 = NULL;
    ui_PSSelBtn2 = NULL;
    ui_PSSelBtn2Text = NULL;
    ui_PSCard3Bg = NULL;
    ui_PSCardNr3 = NULL;
    ui_PSCardDiv3 = NULL;
    ui_PSCardName3 = NULL;
    ui_PSCardM1_3 = NULL;
    ui_PSCardM23 = NULL;
    ui_PSSelBtn3 = NULL;
    ui_PSSelBtn3Text = NULL;
    ui_PSCard4Bg = NULL;
    ui_PSCardNr4 = NULL;
    ui_PSCardDiv4 = NULL;
    ui_PSCardName4 = NULL;
    ui_PSCardM1_4 = NULL;
    ui_PSCardM24 = NULL;
    ui_PSSelBtn4 = NULL;
    ui_PSSelBtn4Text = NULL;
    ui_PSSelInfoBg = NULL;
    ui_PSSelInfo = NULL;
    ui_PSBtnBarBg = NULL;
    ui_PSBtn1 = NULL;
    ui_PSBtn1Text = NULL;
    ui_PSBtn2 = NULL;
    ui_PSBtn2Text = NULL;
    ui_PSBtn3 = NULL;
    ui_PSBtn3Text = NULL;
    ui_PSBtn4 = NULL;
    ui_PSBtn4Text = NULL;

}
