// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPROGRAMEDIT_H
#define UI_SCREENPROGRAMEDIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenProgramEdit
extern void ui_ScreenProgramEdit_screen_init(void);
extern void ui_ScreenProgramEdit_screen_destroy(void);
extern lv_obj_t * ui_ScreenProgramEdit;
extern lv_obj_t * ui_PrgEdHeaderBg;
extern lv_obj_t * ui_PIMMLogo_PrgEd;
extern lv_obj_t * ui_TitelPrgEd;
extern lv_obj_t * ui_PrgEdColBg;
extern lv_obj_t * ui_PrgEdColHdr;
extern lv_obj_t * ui_PrgEdRow1Bg;
extern lv_obj_t * ui_PrgEdNr1;
extern void ui_event_PrgEdM1Btn1(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM1Btn1;
extern lv_obj_t * ui_PrgEdM1Btn1Text;
extern void ui_event_PrgEdM2Btn1(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM2Btn1;
extern lv_obj_t * ui_PrgEdM2Btn1Text;
extern void ui_event_PrgEdDelBtn1(lv_event_t * e);
extern lv_obj_t * ui_PrgEdDelBtn1;
extern lv_obj_t * ui_PrgEdDelBtn1Text;
extern void ui_event_PrgEdActBtn1(lv_event_t * e);
extern lv_obj_t * ui_PrgEdActBtn1;
extern lv_obj_t * ui_PrgEdActBtn1Text;
extern lv_obj_t * ui_PrgEdRow2Bg;
extern lv_obj_t * ui_PrgEdNr2;
extern void ui_event_PrgEdM1Btn2(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM1Btn2;
extern lv_obj_t * ui_PrgEdM1Btn2Text;
extern void ui_event_PrgEdM2Btn2(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM2Btn2;
extern lv_obj_t * ui_PrgEdM2Btn2Text;
extern void ui_event_PrgEdDelBtn2(lv_event_t * e);
extern lv_obj_t * ui_PrgEdDelBtn2;
extern lv_obj_t * ui_PrgEdDelBtn2Text;
extern void ui_event_PrgEdActBtn2(lv_event_t * e);
extern lv_obj_t * ui_PrgEdActBtn2;
extern lv_obj_t * ui_PrgEdActBtn2Text;
extern lv_obj_t * ui_PrgEdRow3Bg;
extern lv_obj_t * ui_PrgEdNr3;
extern void ui_event_PrgEdM1Btn3(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM1Btn3;
extern lv_obj_t * ui_PrgEdM1Btn3Text;
extern void ui_event_PrgEdM2Btn3(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM2Btn3;
extern lv_obj_t * ui_PrgEdM2Btn3Text;
extern void ui_event_PrgEdDelBtn3(lv_event_t * e);
extern lv_obj_t * ui_PrgEdDelBtn3;
extern lv_obj_t * ui_PrgEdDelBtn3Text;
extern void ui_event_PrgEdActBtn3(lv_event_t * e);
extern lv_obj_t * ui_PrgEdActBtn3;
extern lv_obj_t * ui_PrgEdActBtn3Text;
extern lv_obj_t * ui_PrgEdRow4Bg;
extern lv_obj_t * ui_PrgEdNr4;
extern void ui_event_PrgEdM1Btn4(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM1Btn4;
extern lv_obj_t * ui_PrgEdM1Btn4Text;
extern void ui_event_PrgEdM2Btn4(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM2Btn4;
extern lv_obj_t * ui_PrgEdM2Btn4Text;
extern void ui_event_PrgEdDelBtn4(lv_event_t * e);
extern lv_obj_t * ui_PrgEdDelBtn4;
extern lv_obj_t * ui_PrgEdDelBtn4Text;
extern void ui_event_PrgEdActBtn4(lv_event_t * e);
extern lv_obj_t * ui_PrgEdActBtn4;
extern lv_obj_t * ui_PrgEdActBtn4Text;
extern lv_obj_t * ui_PrgEdRow5Bg;
extern lv_obj_t * ui_PrgEdNr5;
extern void ui_event_PrgEdM1Btn5(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM1Btn5;
extern lv_obj_t * ui_PrgEdM1Btn5Text;
extern void ui_event_PrgEdM2Btn5(lv_event_t * e);
extern lv_obj_t * ui_PrgEdM2Btn5;
extern lv_obj_t * ui_PrgEdM2Btn5Text;
extern void ui_event_PrgEdDelBtn5(lv_event_t * e);
extern lv_obj_t * ui_PrgEdDelBtn5;
extern lv_obj_t * ui_PrgEdDelBtn5Text;
extern void ui_event_PrgEdActBtn5(lv_event_t * e);
extern lv_obj_t * ui_PrgEdActBtn5;
extern lv_obj_t * ui_PrgEdActBtn5Text;
extern lv_obj_t * ui_PrgEdFocusBg;
extern lv_obj_t * ui_PrgEdFocusLbl;
extern lv_obj_t * ui_PrgEdBtnBarBg;
extern void ui_event_PrgEdBtn1(lv_event_t * e);
extern lv_obj_t * ui_PrgEdBtn1;
extern lv_obj_t * ui_PrgEdBtn1Text;
extern void ui_event_PrgEdBtn2(lv_event_t * e);
extern lv_obj_t * ui_PrgEdBtn2;
extern lv_obj_t * ui_PrgEdBtn2Text;
extern void ui_event_PrgEdBtn3(lv_event_t * e);
extern lv_obj_t * ui_PrgEdBtn3;
extern lv_obj_t * ui_PrgEdBtn3Text;
extern void ui_event_PrgEdBtn4(lv_event_t * e);
extern lv_obj_t * ui_PrgEdBtn4;
extern lv_obj_t * ui_PrgEdBtn4Text;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

