// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenProgram = NULL;
lv_obj_t * ui_ProgHeaderBg = NULL;
lv_obj_t * ui_PIMMLogo_Prog = NULL;
lv_obj_t * ui_TitelProg = NULL;
lv_obj_t * ui_ProgStepBg = NULL;
lv_obj_t * ui_LblStepNr = NULL;
lv_obj_t * ui_LblEncHintProg = NULL;
lv_obj_t * ui_LblStepM1 = NULL;
lv_obj_t * ui_LblStepM2 = NULL;
lv_obj_t * ui_ProgListHdrBg = NULL;
lv_obj_t * ui_ProgListHdr = NULL;
lv_obj_t * ui_ProgRow1Bg = NULL;
lv_obj_t * ui_ProgRow1 = NULL;
lv_obj_t * ui_ProgRow2Bg = NULL;
lv_obj_t * ui_ProgRow2 = NULL;
lv_obj_t * ui_ProgRow3Bg = NULL;
lv_obj_t * ui_ProgRow3 = NULL;
lv_obj_t * ui_ProgRow4Bg = NULL;
lv_obj_t * ui_ProgRow4 = NULL;
lv_obj_t * ui_ProgRow5Bg = NULL;
lv_obj_t * ui_ProgRow5 = NULL;
lv_obj_t * ui_ProgHint = NULL;
lv_obj_t * ui_ProgBtnBarBg = NULL;
lv_obj_t * ui_ProgBtn1 = NULL;
lv_obj_t * ui_ProgBtn1Text = NULL;
lv_obj_t * ui_ProgBtn2 = NULL;
lv_obj_t * ui_ProgBtn2Text = NULL;
lv_obj_t * ui_ProgBtn3 = NULL;
lv_obj_t * ui_ProgBtn3Text = NULL;
lv_obj_t * ui_ProgBtn4 = NULL;
lv_obj_t * ui_ProgBtn4Text = NULL;
// event funtions
void ui_event_ProgBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_prev_step(e);
    }
}

void ui_event_ProgBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_next_step(e);
    }
}

void ui_event_ProgBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenProgramEdit, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenProgramEdit_screen_init);
    }
}

void ui_event_ProgBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenHome_screen_init);
    }
}

// build funtions

void ui_ScreenProgram_screen_init(void)
{
    ui_ScreenProgram = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenProgram, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgHeaderBg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgHeaderBg, 800);
    lv_obj_set_height(ui_ProgHeaderBg, 50);
    lv_label_set_text(ui_ProgHeaderBg, "");
    lv_obj_set_style_text_color(ui_ProgHeaderBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgHeaderBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgHeaderBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgHeaderBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgHeaderBg, lv_color_hex(0x002D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIMMLogo_Prog = lv_img_create(ui_ScreenProgram);
    lv_img_set_src(ui_PIMMLogo_Prog, &ui_img_pimm_logo_png);
    lv_obj_set_width(ui_PIMMLogo_Prog, 1);
    lv_obj_set_height(ui_PIMMLogo_Prog, 1);
    lv_obj_set_x(ui_PIMMLogo_Prog, 1);
    lv_obj_set_y(ui_PIMMLogo_Prog, 0);
    lv_obj_add_flag(ui_PIMMLogo_Prog, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PIMMLogo_Prog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitelProg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_TitelProg, 1);
    lv_obj_set_height(ui_TitelProg, 1);
    lv_obj_set_align(ui_TitelProg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitelProg, "PROGRAMMA");
    lv_obj_set_style_text_color(ui_TitelProg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitelProg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitelProg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TitelProg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitelProg, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitelProg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitelProg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitelProg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitelProg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitelProg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitelProg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitelProg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgStepBg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgStepBg, 780);
    lv_obj_set_height(ui_ProgStepBg, 108);
    lv_obj_set_x(ui_ProgStepBg, 10);
    lv_obj_set_y(ui_ProgStepBg, 58);
    lv_label_set_text(ui_ProgStepBg, "");
    lv_obj_set_style_text_color(ui_ProgStepBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgStepBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgStepBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgStepBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgStepBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgStepBg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgStepBg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgStepBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgStepBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgStepBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgStepBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgStepBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblStepNr = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_LblStepNr, 340);
    lv_obj_set_height(ui_LblStepNr, 40);
    lv_obj_set_x(ui_LblStepNr, 20);
    lv_obj_set_y(ui_LblStepNr, 66);
    lv_label_set_text(ui_LblStepNr, "Stap: 1 / 5");
    lv_obj_set_style_text_color(ui_LblStepNr, lv_color_hex(0xFFC850), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblStepNr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblStepNr, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblStepNr, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblStepNr, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblStepNr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblStepNr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblStepNr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblStepNr, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblStepNr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblStepNr, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblStepNr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblEncHintProg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_LblEncHintProg, 430);
    lv_obj_set_height(ui_LblEncHintProg, 40);
    lv_obj_set_x(ui_LblEncHintProg, 360);
    lv_obj_set_y(ui_LblEncHintProg, 66);
    lv_label_set_text(ui_LblEncHintProg, "Enkoder = fijnafstelling huidig stap");
    lv_obj_set_style_text_color(ui_LblEncHintProg, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblEncHintProg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblEncHintProg, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblEncHintProg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblEncHintProg, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblEncHintProg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblEncHintProg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblEncHintProg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblEncHintProg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblEncHintProg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblEncHintProg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblEncHintProg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblStepM1 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_LblStepM1, 370);
    lv_obj_set_height(ui_LblStepM1, 34);
    lv_obj_set_x(ui_LblStepM1, 20);
    lv_obj_set_y(ui_LblStepM1, 116);
    lv_label_set_text(ui_LblStepM1, "Module 1:  ---.-- mm");
    lv_obj_set_style_text_color(ui_LblStepM1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblStepM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblStepM1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblStepM1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblStepM1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblStepM1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblStepM1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblStepM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblStepM1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblStepM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblStepM1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblStepM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblStepM2 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_LblStepM2, 370);
    lv_obj_set_height(ui_LblStepM2, 34);
    lv_obj_set_x(ui_LblStepM2, 410);
    lv_obj_set_y(ui_LblStepM2, 116);
    lv_label_set_text(ui_LblStepM2, "Module 2:  ---.-- mm");
    lv_obj_set_style_text_color(ui_LblStepM2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblStepM2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblStepM2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblStepM2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblStepM2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblStepM2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblStepM2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblStepM2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblStepM2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblStepM2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblStepM2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblStepM2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgListHdrBg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgListHdrBg, 780);
    lv_obj_set_height(ui_ProgListHdrBg, 34);
    lv_obj_set_x(ui_ProgListHdrBg, 10);
    lv_obj_set_y(ui_ProgListHdrBg, 176);
    lv_label_set_text(ui_ProgListHdrBg, "");
    lv_obj_set_style_text_color(ui_ProgListHdrBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgListHdrBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgListHdrBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgListHdrBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgListHdrBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgListHdrBg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgListHdrBg, lv_color_hex(0x00284B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgListHdrBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgListHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgListHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgListHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgListHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgListHdr = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgListHdr, 770);
    lv_obj_set_height(ui_ProgListHdr, 26);
    lv_obj_set_x(ui_ProgListHdr, 14);
    lv_obj_set_y(ui_ProgListHdr, 180);
    lv_label_set_text(ui_ProgListHdr, "  #     Module 1 (mm)       Module 2 (mm)       Status");
    lv_obj_set_style_text_color(ui_ProgListHdr, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgListHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgListHdr, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgListHdr, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgListHdr, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgListHdr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgListHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgListHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgListHdr, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgListHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgListHdr, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgListHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow1Bg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow1Bg, 780);
    lv_obj_set_height(ui_ProgRow1Bg, 36);
    lv_obj_set_x(ui_ProgRow1Bg, 10);
    lv_obj_set_y(ui_ProgRow1Bg, 214);
    lv_label_set_text(ui_ProgRow1Bg, "");
    lv_obj_set_style_text_color(ui_ProgRow1Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow1Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow1Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow1Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow1Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow1Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow1 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow1, 770);
    lv_obj_set_height(ui_ProgRow1, 28);
    lv_obj_set_x(ui_ProgRow1, 14);
    lv_obj_set_y(ui_ProgRow1, 218);
    lv_label_set_text(ui_ProgRow1, "  1       ---.-- mm            ---.-- mm");
    lv_obj_set_style_text_color(ui_ProgRow1, lv_color_hex(0xFFDC64), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow2Bg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow2Bg, 780);
    lv_obj_set_height(ui_ProgRow2Bg, 36);
    lv_obj_set_x(ui_ProgRow2Bg, 10);
    lv_obj_set_y(ui_ProgRow2Bg, 252);
    lv_label_set_text(ui_ProgRow2Bg, "");
    lv_obj_set_style_text_color(ui_ProgRow2Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow2Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow2Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow2Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow2Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow2Bg, lv_color_hex(0x16283E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow2 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow2, 770);
    lv_obj_set_height(ui_ProgRow2, 28);
    lv_obj_set_x(ui_ProgRow2, 14);
    lv_obj_set_y(ui_ProgRow2, 256);
    lv_label_set_text(ui_ProgRow2, "  2       ---.-- mm            ---.-- mm");
    lv_obj_set_style_text_color(ui_ProgRow2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow3Bg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow3Bg, 780);
    lv_obj_set_height(ui_ProgRow3Bg, 36);
    lv_obj_set_x(ui_ProgRow3Bg, 10);
    lv_obj_set_y(ui_ProgRow3Bg, 290);
    lv_label_set_text(ui_ProgRow3Bg, "");
    lv_obj_set_style_text_color(ui_ProgRow3Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow3Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow3Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow3Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow3Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow3Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow3 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow3, 770);
    lv_obj_set_height(ui_ProgRow3, 28);
    lv_obj_set_x(ui_ProgRow3, 14);
    lv_obj_set_y(ui_ProgRow3, 294);
    lv_label_set_text(ui_ProgRow3, "  3       ---.-- mm            ---.-- mm");
    lv_obj_set_style_text_color(ui_ProgRow3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow4Bg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow4Bg, 780);
    lv_obj_set_height(ui_ProgRow4Bg, 36);
    lv_obj_set_x(ui_ProgRow4Bg, 10);
    lv_obj_set_y(ui_ProgRow4Bg, 328);
    lv_label_set_text(ui_ProgRow4Bg, "");
    lv_obj_set_style_text_color(ui_ProgRow4Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow4Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow4Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow4Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow4Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow4Bg, lv_color_hex(0x16283E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow4 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow4, 770);
    lv_obj_set_height(ui_ProgRow4, 28);
    lv_obj_set_x(ui_ProgRow4, 14);
    lv_obj_set_y(ui_ProgRow4, 332);
    lv_label_set_text(ui_ProgRow4, "  4       ---.-- mm            ---.-- mm");
    lv_obj_set_style_text_color(ui_ProgRow4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow4, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow5Bg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow5Bg, 780);
    lv_obj_set_height(ui_ProgRow5Bg, 36);
    lv_obj_set_x(ui_ProgRow5Bg, 10);
    lv_obj_set_y(ui_ProgRow5Bg, 366);
    lv_label_set_text(ui_ProgRow5Bg, "");
    lv_obj_set_style_text_color(ui_ProgRow5Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow5Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow5Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow5Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow5Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow5Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow5Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow5Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgRow5 = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgRow5, 770);
    lv_obj_set_height(ui_ProgRow5, 28);
    lv_obj_set_x(ui_ProgRow5, 14);
    lv_obj_set_y(ui_ProgRow5, 370);
    lv_label_set_text(ui_ProgRow5, "  5       ---.-- mm            ---.-- mm");
    lv_obj_set_style_text_color(ui_ProgRow5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgRow5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgRow5, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgRow5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgRow5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgRow5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgRow5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgRow5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgRow5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgRow5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgRow5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgRow5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgHint = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgHint, 780);
    lv_obj_set_height(ui_ProgHint, 26);
    lv_obj_set_x(ui_ProgHint, 10);
    lv_obj_set_y(ui_ProgHint, 408);
    lv_label_set_text(ui_ProgHint, "Gebruik fysieke knoppen of raak de balk hieronder aan");
    lv_obj_set_style_text_color(ui_ProgHint, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgHint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgHint, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgHint, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgHint, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgHint, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgHint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgHint, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgHint, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtnBarBg = lv_label_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgBtnBarBg, 800);
    lv_obj_set_height(ui_ProgBtnBarBg, 60);
    lv_obj_set_x(ui_ProgBtnBarBg, 0);
    lv_obj_set_y(ui_ProgBtnBarBg, 420);
    lv_label_set_text(ui_ProgBtnBarBg, "");
    lv_obj_set_style_text_color(ui_ProgBtnBarBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgBtnBarBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgBtnBarBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgBtnBarBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtnBarBg, lv_color_hex(0x080F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn1 = lv_btn_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgBtn1, 200);
    lv_obj_set_height(ui_ProgBtn1, 57);
    lv_obj_set_x(ui_ProgBtn1, 0);
    lv_obj_set_y(ui_ProgBtn1, 421);
    lv_obj_add_flag(ui_ProgBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProgBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn1, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn1Text = lv_label_create(ui_ProgBtn1);
    lv_obj_set_width(ui_ProgBtn1Text, 200);
    lv_obj_set_height(ui_ProgBtn1Text, 57);
    lv_obj_set_align(ui_ProgBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgBtn1Text, "< Vorige Stap");
    lv_obj_set_style_text_color(ui_ProgBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgBtn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn2 = lv_btn_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgBtn2, 200);
    lv_obj_set_height(ui_ProgBtn2, 57);
    lv_obj_set_x(ui_ProgBtn2, 200);
    lv_obj_set_y(ui_ProgBtn2, 421);
    lv_obj_add_flag(ui_ProgBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProgBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn2Text = lv_label_create(ui_ProgBtn2);
    lv_obj_set_width(ui_ProgBtn2Text, 200);
    lv_obj_set_height(ui_ProgBtn2Text, 57);
    lv_obj_set_align(ui_ProgBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgBtn2Text, "Volgende Stap >");
    lv_obj_set_style_text_color(ui_ProgBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgBtn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn3 = lv_btn_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgBtn3, 200);
    lv_obj_set_height(ui_ProgBtn3, 57);
    lv_obj_set_x(ui_ProgBtn3, 400);
    lv_obj_set_y(ui_ProgBtn3, 421);
    lv_obj_add_flag(ui_ProgBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProgBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn3, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn3Text = lv_label_create(ui_ProgBtn3);
    lv_obj_set_width(ui_ProgBtn3Text, 200);
    lv_obj_set_height(ui_ProgBtn3Text, 57);
    lv_obj_set_align(ui_ProgBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgBtn3Text, "Bewerken");
    lv_obj_set_style_text_color(ui_ProgBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgBtn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn4 = lv_btn_create(ui_ScreenProgram);
    lv_obj_set_width(ui_ProgBtn4, 200);
    lv_obj_set_height(ui_ProgBtn4, 57);
    lv_obj_set_x(ui_ProgBtn4, 600);
    lv_obj_set_y(ui_ProgBtn4, 421);
    lv_obj_add_flag(ui_ProgBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ProgBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn4, lv_color_hex(0x233755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgBtn4Text = lv_label_create(ui_ProgBtn4);
    lv_obj_set_width(ui_ProgBtn4Text, 200);
    lv_obj_set_height(ui_ProgBtn4Text, 57);
    lv_obj_set_align(ui_ProgBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgBtn4Text, "Terug");
    lv_obj_set_style_text_color(ui_ProgBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProgBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProgBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_ProgBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProgBtn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ProgBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ProgBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProgBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ProgBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ProgBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ProgBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ProgBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ProgBtn1, ui_event_ProgBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProgBtn2, ui_event_ProgBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProgBtn3, ui_event_ProgBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProgBtn4, ui_event_ProgBtn4, LV_EVENT_ALL, NULL);

}

void ui_ScreenProgram_screen_destroy(void)
{
    if(ui_ScreenProgram) lv_obj_del(ui_ScreenProgram);

    // NULL screen variables
    ui_ScreenProgram = NULL;
    ui_ProgHeaderBg = NULL;
    ui_PIMMLogo_Prog = NULL;
    ui_TitelProg = NULL;
    ui_ProgStepBg = NULL;
    ui_LblStepNr = NULL;
    ui_LblEncHintProg = NULL;
    ui_LblStepM1 = NULL;
    ui_LblStepM2 = NULL;
    ui_ProgListHdrBg = NULL;
    ui_ProgListHdr = NULL;
    ui_ProgRow1Bg = NULL;
    ui_ProgRow1 = NULL;
    ui_ProgRow2Bg = NULL;
    ui_ProgRow2 = NULL;
    ui_ProgRow3Bg = NULL;
    ui_ProgRow3 = NULL;
    ui_ProgRow4Bg = NULL;
    ui_ProgRow4 = NULL;
    ui_ProgRow5Bg = NULL;
    ui_ProgRow5 = NULL;
    ui_ProgHint = NULL;
    ui_ProgBtnBarBg = NULL;
    ui_ProgBtn1 = NULL;
    ui_ProgBtn1Text = NULL;
    ui_ProgBtn2 = NULL;
    ui_ProgBtn2Text = NULL;
    ui_ProgBtn3 = NULL;
    ui_ProgBtn3Text = NULL;
    ui_ProgBtn4 = NULL;
    ui_ProgBtn4Text = NULL;

}
