// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

extern int module1Height; //to use this data on screen

lv_obj_t * ui_ScreenHome = NULL;
lv_obj_t * ui_HomeHeaderBg = NULL;
lv_obj_t * ui_PIMMLogo1 = NULL;
lv_obj_t * ui_TitelHome = NULL;
lv_obj_t * ui_PanelMod1Bg = NULL;
lv_obj_t * ui_LblMod1Title = NULL;
lv_obj_t * ui_LblMod1Height = NULL;
lv_obj_t * ui_LblMod1Sub = NULL;
lv_obj_t * ui_LblMod1Tgt = NULL;
lv_obj_t * ui_PanelGap = NULL;
lv_obj_t * ui_PanelMod2Bg = NULL;
lv_obj_t * ui_LblMod2Title = NULL;
lv_obj_t * ui_LblMod2Height = NULL;
lv_obj_t * ui_LblMod2Sub = NULL;
lv_obj_t * ui_LblMod2Tgt = NULL;
lv_obj_t * ui_SelRowBg = NULL;
lv_obj_t * ui_LblEnkoder = NULL;
lv_obj_t * ui_BtnSelMod1 = NULL;
lv_obj_t * ui_BtnSelMod1Text = NULL;
lv_obj_t * ui_BtnSelBoth = NULL;
lv_obj_t * ui_BtnSelBothText = NULL;
lv_obj_t * ui_BtnSelMod2 = NULL;
lv_obj_t * ui_BtnSelMod2Text = NULL;
lv_obj_t * ui_StatusBg = NULL;
lv_obj_t * ui_LblSyncStatus = NULL;
lv_obj_t * ui_LblProgInfo = NULL;
lv_obj_t * ui_HomeBtnBarBg = NULL;
lv_obj_t * ui_HomeBtn1 = NULL;
lv_obj_t * ui_HomeBtn1Text = NULL;
lv_obj_t * ui_HomeBtn2 = NULL;
lv_obj_t * ui_HomeBtn2Text = NULL;
lv_obj_t * ui_HomeBtn3 = NULL;
lv_obj_t * ui_HomeBtn3Text = NULL;
lv_obj_t * ui_HomeBtn4 = NULL;
lv_obj_t * ui_HomeBtn4Text = NULL;
// event funtions
void ui_event_BtnSelMod1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_module1(e);
    }
}

void ui_event_BtnSelBoth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_both(e);
    }
}

void ui_event_BtnSelMod2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_select_module2(e);
    }
}

void ui_event_HomeBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPresetselect, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenPresetselect_screen_init);
    }
}

void ui_event_HomeBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenProgram, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenProgram_screen_init);
    }
}

void ui_event_HomeBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_toggle_sync(e);
    }
}

void ui_event_HomeBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_power_off(e);
    }
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HomeHeaderBg = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeHeaderBg, 800);
    lv_obj_set_height(ui_HomeHeaderBg, 50);
    lv_label_set_text(ui_HomeHeaderBg, "");
    lv_obj_set_style_text_color(ui_HomeHeaderBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeHeaderBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HomeHeaderBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeHeaderBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HomeHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeHeaderBg, lv_color_hex(0x002D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIMMLogo1 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_PIMMLogo1, &ui_img_pimm_logo_png);
    lv_obj_set_width(ui_PIMMLogo1, 1);
    lv_obj_set_height(ui_PIMMLogo1, 1);
    lv_obj_set_x(ui_PIMMLogo1, 1);
    lv_obj_set_y(ui_PIMMLogo1, 0);
    lv_obj_add_flag(ui_PIMMLogo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PIMMLogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitelHome = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_TitelHome, 1);
    lv_obj_set_height(ui_TitelHome, 1);
    lv_obj_set_align(ui_TitelHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitelHome, "PIMM  –  Hoogte Regeling");
    lv_obj_set_style_text_color(ui_TitelHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitelHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitelHome, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TitelHome, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitelHome, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitelHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitelHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitelHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitelHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitelHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitelHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitelHome, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMod1Bg = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelMod1Bg, 370);
    lv_obj_set_height(ui_PanelMod1Bg, 220);
    lv_obj_set_x(ui_PanelMod1Bg, 10);
    lv_obj_set_y(ui_PanelMod1Bg, 55);
    lv_label_set_text(ui_PanelMod1Bg, "");
    lv_obj_set_style_text_color(ui_PanelMod1Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelMod1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PanelMod1Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PanelMod1Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelMod1Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PanelMod1Bg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelMod1Bg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMod1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelMod1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelMod1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelMod1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelMod1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod1Title = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod1Title, 370);
    lv_obj_set_height(ui_LblMod1Title, 28);
    lv_obj_set_x(ui_LblMod1Title, 10);
    lv_obj_set_y(ui_LblMod1Title, 61);
    lv_label_set_text(ui_LblMod1Title, "MODULE 1");
    lv_obj_set_style_text_color(ui_LblMod1Title, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod1Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod1Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod1Title, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod1Title, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod1Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod1Title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod1Title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod1Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod1Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod1Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod1Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod1Height = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod1Height, 370);
    lv_obj_set_height(ui_LblMod1Height, 90);
    lv_obj_set_x(ui_LblMod1Height, 10);
    lv_obj_set_y(ui_LblMod1Height, 98);
  char buf[16];
snprintf(buf, sizeof(buf), "%d.%d mm", module1Height / 10, module1Height % 10);
lv_label_set_text(ui_LblMod1Height, buf);
    lv_obj_set_style_text_color(ui_LblMod1Height, lv_color_hex(0x64DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod1Height, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod1Height, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod1Height, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod1Height, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod1Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod1Height, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod1Height, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod1Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod1Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod1Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod1Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod1Sub = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod1Sub, 370);
    lv_obj_set_height(ui_LblMod1Sub, 22);
    lv_obj_set_x(ui_LblMod1Sub, 10);
    lv_obj_set_y(ui_LblMod1Sub, 196);
    lv_label_set_text(ui_LblMod1Sub, "Huidige hoogte");
    lv_obj_set_style_text_color(ui_LblMod1Sub, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod1Sub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod1Sub, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod1Sub, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod1Sub, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod1Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod1Sub, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod1Sub, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod1Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod1Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod1Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod1Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod1Tgt = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod1Tgt, 370);
    lv_obj_set_height(ui_LblMod1Tgt, 22);
    lv_obj_set_x(ui_LblMod1Tgt, 10);
    lv_obj_set_y(ui_LblMod1Tgt, 222);
    lv_label_set_text(ui_LblMod1Tgt, "Doel: --.- mm");
    lv_obj_set_style_text_color(ui_LblMod1Tgt, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod1Tgt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod1Tgt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod1Tgt, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod1Tgt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod1Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod1Tgt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod1Tgt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod1Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod1Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod1Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod1Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGap = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelGap, 24);
    lv_obj_set_height(ui_PanelGap, 220);
    lv_obj_set_x(ui_PanelGap, 388);
    lv_obj_set_y(ui_PanelGap, 55);
    lv_label_set_text(ui_PanelGap, "");
    lv_obj_set_style_text_color(ui_PanelGap, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelGap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PanelGap, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PanelGap, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelGap, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PanelGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelGap, lv_color_hex(0x080F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGap, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelGap, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMod2Bg = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelMod2Bg, 370);
    lv_obj_set_height(ui_PanelMod2Bg, 220);
    lv_obj_set_x(ui_PanelMod2Bg, 420);
    lv_obj_set_y(ui_PanelMod2Bg, 55);
    lv_label_set_text(ui_PanelMod2Bg, "");
    lv_obj_set_style_text_color(ui_PanelMod2Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelMod2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PanelMod2Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PanelMod2Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelMod2Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PanelMod2Bg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelMod2Bg, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMod2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelMod2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelMod2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelMod2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelMod2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod2Title = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod2Title, 370);
    lv_obj_set_height(ui_LblMod2Title, 28);
    lv_obj_set_x(ui_LblMod2Title, 420);
    lv_obj_set_y(ui_LblMod2Title, 61);
    lv_label_set_text(ui_LblMod2Title, "MODULE 2");
    lv_obj_set_style_text_color(ui_LblMod2Title, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod2Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod2Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod2Title, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod2Title, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod2Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod2Title, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod2Title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod2Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod2Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod2Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod2Title, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod2Height = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod2Height, 370);
    lv_obj_set_height(ui_LblMod2Height, 90);
    lv_obj_set_x(ui_LblMod2Height, 420);
    lv_obj_set_y(ui_LblMod2Height, 98);
    lv_label_set_text(ui_LblMod2Height, "00.0 mm");
    lv_obj_set_style_text_color(ui_LblMod2Height, lv_color_hex(0x64DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod2Height, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod2Height, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod2Height, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod2Height, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod2Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod2Height, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod2Height, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod2Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod2Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod2Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod2Height, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod2Sub = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod2Sub, 370);
    lv_obj_set_height(ui_LblMod2Sub, 22);
    lv_obj_set_x(ui_LblMod2Sub, 420);
    lv_obj_set_y(ui_LblMod2Sub, 196);
    lv_label_set_text(ui_LblMod2Sub, "Huidige hoogte");
    lv_obj_set_style_text_color(ui_LblMod2Sub, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod2Sub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod2Sub, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod2Sub, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod2Sub, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod2Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod2Sub, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod2Sub, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod2Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod2Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod2Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod2Sub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMod2Tgt = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblMod2Tgt, 370);
    lv_obj_set_height(ui_LblMod2Tgt, 22);
    lv_obj_set_x(ui_LblMod2Tgt, 420);
    lv_obj_set_y(ui_LblMod2Tgt, 222);
    lv_label_set_text(ui_LblMod2Tgt, "Doel: --.- mm");
    lv_obj_set_style_text_color(ui_LblMod2Tgt, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMod2Tgt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblMod2Tgt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblMod2Tgt, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblMod2Tgt, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblMod2Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblMod2Tgt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblMod2Tgt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblMod2Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblMod2Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblMod2Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblMod2Tgt, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelRowBg = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_SelRowBg, 800);
    lv_obj_set_height(ui_SelRowBg, 68);
    lv_obj_set_x(ui_SelRowBg, 0);
    lv_obj_set_y(ui_SelRowBg, 280);
    lv_label_set_text(ui_SelRowBg, "");
    lv_obj_set_style_text_color(ui_SelRowBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SelRowBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SelRowBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SelRowBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelRowBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SelRowBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SelRowBg, lv_color_hex(0x0C162A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SelRowBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SelRowBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SelRowBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SelRowBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SelRowBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblEnkoder = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblEnkoder, 170);
    lv_obj_set_height(ui_LblEnkoder, 44);
    lv_obj_set_x(ui_LblEnkoder, 10);
    lv_obj_set_y(ui_LblEnkoder, 292);
    lv_label_set_text(ui_LblEnkoder, "Enkoder regelt:");
    lv_obj_set_style_text_color(ui_LblEnkoder, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblEnkoder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblEnkoder, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblEnkoder, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblEnkoder, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblEnkoder, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblEnkoder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblEnkoder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblEnkoder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblEnkoder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblEnkoder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblEnkoder, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSelMod1 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_BtnSelMod1, 178);
    lv_obj_set_height(ui_BtnSelMod1, 52);
    lv_obj_set_x(ui_BtnSelMod1, 190);
    lv_obj_set_y(ui_BtnSelMod1, 284);
    lv_obj_add_flag(ui_BtnSelMod1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSelMod1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnSelMod1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSelMod1, lv_color_hex(0x009646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSelMod1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSelMod1Text = lv_label_create(ui_BtnSelMod1);
    lv_obj_set_width(ui_BtnSelMod1Text, 178);
    lv_obj_set_height(ui_BtnSelMod1Text, 52);
    lv_obj_set_align(ui_BtnSelMod1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSelMod1Text, "Module 1");
    lv_obj_set_style_text_color(ui_BtnSelMod1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSelMod1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnSelMod1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_BtnSelMod1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnSelMod1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnSelMod1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSelMod1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSelMod1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BtnSelMod1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BtnSelMod1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BtnSelMod1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BtnSelMod1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSelBoth = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_BtnSelBoth, 218);
    lv_obj_set_height(ui_BtnSelBoth, 52);
    lv_obj_set_x(ui_BtnSelBoth, 378);
    lv_obj_set_y(ui_BtnSelBoth, 284);
    lv_obj_add_flag(ui_BtnSelBoth, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSelBoth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnSelBoth, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSelBoth, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSelBoth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSelBothText = lv_label_create(ui_BtnSelBoth);
    lv_obj_set_width(ui_BtnSelBothText, 218);
    lv_obj_set_height(ui_BtnSelBothText, 52);
    lv_obj_set_align(ui_BtnSelBothText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSelBothText, "Beide (Sync)");
    lv_obj_set_style_text_color(ui_BtnSelBothText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSelBothText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnSelBothText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_BtnSelBothText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnSelBothText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnSelBothText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSelBothText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSelBothText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BtnSelBothText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BtnSelBothText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BtnSelBothText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BtnSelBothText, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSelMod2 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_BtnSelMod2, 184);
    lv_obj_set_height(ui_BtnSelMod2, 52);
    lv_obj_set_x(ui_BtnSelMod2, 606);
    lv_obj_set_y(ui_BtnSelMod2, 284);
    lv_obj_add_flag(ui_BtnSelMod2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSelMod2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnSelMod2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSelMod2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSelMod2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSelMod2Text = lv_label_create(ui_BtnSelMod2);
    lv_obj_set_width(ui_BtnSelMod2Text, 184);
    lv_obj_set_height(ui_BtnSelMod2Text, 52);
    lv_obj_set_align(ui_BtnSelMod2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSelMod2Text, "Module 2");
    lv_obj_set_style_text_color(ui_BtnSelMod2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSelMod2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BtnSelMod2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_BtnSelMod2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnSelMod2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_BtnSelMod2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSelMod2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSelMod2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BtnSelMod2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BtnSelMod2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BtnSelMod2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BtnSelMod2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusBg = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_StatusBg, 800);
    lv_obj_set_height(ui_StatusBg, 66);
    lv_obj_set_x(ui_StatusBg, 0);
    lv_obj_set_y(ui_StatusBg, 353);
    lv_label_set_text(ui_StatusBg, "");
    lv_obj_set_style_text_color(ui_StatusBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_StatusBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_StatusBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StatusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusBg, lv_color_hex(0x0A1221), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_StatusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StatusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StatusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StatusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSyncStatus = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblSyncStatus, 190);
    lv_obj_set_height(ui_LblSyncStatus, 48);
    lv_obj_set_x(ui_LblSyncStatus, 10);
    lv_obj_set_y(ui_LblSyncStatus, 361);
    lv_label_set_text(ui_LblSyncStatus, "Sync: UIT");
    lv_obj_set_style_text_color(ui_LblSyncStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSyncStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblSyncStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblSyncStatus, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSyncStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblSyncStatus, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblSyncStatus, lv_color_hex(0x6E3700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblSyncStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblSyncStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblSyncStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblSyncStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblSyncStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblProgInfo = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LblProgInfo, 580);
    lv_obj_set_height(ui_LblProgInfo, 48);
    lv_obj_set_x(ui_LblProgInfo, 210);
    lv_obj_set_y(ui_LblProgInfo, 361);
    lv_label_set_text(ui_LblProgInfo, "Programma: Geen  /  Stap: -");
    lv_obj_set_style_text_color(ui_LblProgInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblProgInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LblProgInfo, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_LblProgInfo, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblProgInfo, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LblProgInfo, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblProgInfo, lv_color_hex(0x14233C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblProgInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LblProgInfo, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LblProgInfo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LblProgInfo, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LblProgInfo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtnBarBg = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeBtnBarBg, 800);
    lv_obj_set_height(ui_HomeBtnBarBg, 60);
    lv_obj_set_x(ui_HomeBtnBarBg, 0);
    lv_obj_set_y(ui_HomeBtnBarBg, 420);
    lv_label_set_text(ui_HomeBtnBarBg, "");
    lv_obj_set_style_text_color(ui_HomeBtnBarBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBtnBarBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HomeBtnBarBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBtnBarBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HomeBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtnBarBg, lv_color_hex(0x080F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn1 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeBtn1, 200);
    lv_obj_set_height(ui_HomeBtn1, 57);
    lv_obj_set_x(ui_HomeBtn1, 0);
    lv_obj_set_y(ui_HomeBtn1, 421);
    lv_obj_add_flag(ui_HomeBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn1, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn1Text = lv_label_create(ui_HomeBtn1);
    lv_obj_set_width(ui_HomeBtn1Text, 200);
    lv_obj_set_height(ui_HomeBtn1Text, 57);
    lv_obj_set_align(ui_HomeBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeBtn1Text, "Presets");
    lv_obj_set_style_text_color(ui_HomeBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HomeBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBtn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HomeBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn2 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeBtn2, 200);
    lv_obj_set_height(ui_HomeBtn2, 57);
    lv_obj_set_x(ui_HomeBtn2, 200);
    lv_obj_set_y(ui_HomeBtn2, 421);
    lv_obj_add_flag(ui_HomeBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn2Text = lv_label_create(ui_HomeBtn2);
    lv_obj_set_width(ui_HomeBtn2Text, 200);
    lv_obj_set_height(ui_HomeBtn2Text, 57);
    lv_obj_set_align(ui_HomeBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeBtn2Text, "Programma");
    lv_obj_set_style_text_color(ui_HomeBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HomeBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBtn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HomeBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn3 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeBtn3, 200);
    lv_obj_set_height(ui_HomeBtn3, 57);
    lv_obj_set_x(ui_HomeBtn3, 400);
    lv_obj_set_y(ui_HomeBtn3, 421);
    lv_obj_add_flag(ui_HomeBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn3, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn3Text = lv_label_create(ui_HomeBtn3);
    lv_obj_set_width(ui_HomeBtn3Text, 200);
    lv_obj_set_height(ui_HomeBtn3Text, 57);
    lv_obj_set_align(ui_HomeBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeBtn3Text, "Sync: UIT");
    lv_obj_set_style_text_color(ui_HomeBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HomeBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBtn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HomeBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn4 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_HomeBtn4, 200);
    lv_obj_set_height(ui_HomeBtn4, 57);
    lv_obj_set_x(ui_HomeBtn4, 600);
    lv_obj_set_y(ui_HomeBtn4, 421);
    lv_obj_add_flag(ui_HomeBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn4, lv_color_hex(0xA00023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HomeBtn4Text = lv_label_create(ui_HomeBtn4);
    lv_obj_set_width(ui_HomeBtn4Text, 200);
    lv_obj_set_height(ui_HomeBtn4Text, 57);
    lv_obj_set_align(ui_HomeBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HomeBtn4Text, "UIT");
    lv_obj_set_style_text_color(ui_HomeBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HomeBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HomeBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HomeBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HomeBtn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_HomeBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_HomeBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_HomeBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_HomeBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_HomeBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnSelMod1, ui_event_BtnSelMod1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSelBoth, ui_event_BtnSelBoth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSelMod2, ui_event_BtnSelMod2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn1, ui_event_HomeBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn2, ui_event_HomeBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn3, ui_event_HomeBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeBtn4, ui_event_HomeBtn4, LV_EVENT_ALL, NULL);

}

void ui_ScreenHome_screen_destroy(void)
{
    if(ui_ScreenHome) lv_obj_del(ui_ScreenHome);

    // NULL screen variables
    ui_ScreenHome = NULL;
    ui_HomeHeaderBg = NULL;
    ui_PIMMLogo1 = NULL;
    ui_TitelHome = NULL;
    ui_PanelMod1Bg = NULL;
    ui_LblMod1Title = NULL;
    ui_LblMod1Height = NULL;
    ui_LblMod1Sub = NULL;
    ui_LblMod1Tgt = NULL;
    ui_PanelGap = NULL;
    ui_PanelMod2Bg = NULL;
    ui_LblMod2Title = NULL;
    ui_LblMod2Height = NULL;
    ui_LblMod2Sub = NULL;
    ui_LblMod2Tgt = NULL;
    ui_SelRowBg = NULL;
    ui_LblEnkoder = NULL;
    ui_BtnSelMod1 = NULL;
    ui_BtnSelMod1Text = NULL;
    ui_BtnSelBoth = NULL;
    ui_BtnSelBothText = NULL;
    ui_BtnSelMod2 = NULL;
    ui_BtnSelMod2Text = NULL;
    ui_StatusBg = NULL;
    ui_LblSyncStatus = NULL;
    ui_LblProgInfo = NULL;
    ui_HomeBtnBarBg = NULL;
    ui_HomeBtn1 = NULL;
    ui_HomeBtn1Text = NULL;
    ui_HomeBtn2 = NULL;
    ui_HomeBtn2Text = NULL;
    ui_HomeBtn3 = NULL;
    ui_HomeBtn3Text = NULL;
    ui_HomeBtn4 = NULL;
    ui_HomeBtn4Text = NULL;

}
