// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenProgramEdit = NULL;
lv_obj_t * ui_PrgEdHeaderBg = NULL;
lv_obj_t * ui_PIMMLogo_PrgEd = NULL;
lv_obj_t * ui_TitelPrgEd = NULL;
lv_obj_t * ui_PrgEdColBg = NULL;
lv_obj_t * ui_PrgEdColHdr = NULL;
lv_obj_t * ui_PrgEdRow1Bg = NULL;
lv_obj_t * ui_PrgEdNr1 = NULL;
lv_obj_t * ui_PrgEdM1Btn1 = NULL;
lv_obj_t * ui_PrgEdM1Btn1Text = NULL;
lv_obj_t * ui_PrgEdM2Btn1 = NULL;
lv_obj_t * ui_PrgEdM2Btn1Text = NULL;
lv_obj_t * ui_PrgEdDelBtn1 = NULL;
lv_obj_t * ui_PrgEdDelBtn1Text = NULL;
lv_obj_t * ui_PrgEdActBtn1 = NULL;
lv_obj_t * ui_PrgEdActBtn1Text = NULL;
lv_obj_t * ui_PrgEdRow2Bg = NULL;
lv_obj_t * ui_PrgEdNr2 = NULL;
lv_obj_t * ui_PrgEdM1Btn2 = NULL;
lv_obj_t * ui_PrgEdM1Btn2Text = NULL;
lv_obj_t * ui_PrgEdM2Btn2 = NULL;
lv_obj_t * ui_PrgEdM2Btn2Text = NULL;
lv_obj_t * ui_PrgEdDelBtn2 = NULL;
lv_obj_t * ui_PrgEdDelBtn2Text = NULL;
lv_obj_t * ui_PrgEdActBtn2 = NULL;
lv_obj_t * ui_PrgEdActBtn2Text = NULL;
lv_obj_t * ui_PrgEdRow3Bg = NULL;
lv_obj_t * ui_PrgEdNr3 = NULL;
lv_obj_t * ui_PrgEdM1Btn3 = NULL;
lv_obj_t * ui_PrgEdM1Btn3Text = NULL;
lv_obj_t * ui_PrgEdM2Btn3 = NULL;
lv_obj_t * ui_PrgEdM2Btn3Text = NULL;
lv_obj_t * ui_PrgEdDelBtn3 = NULL;
lv_obj_t * ui_PrgEdDelBtn3Text = NULL;
lv_obj_t * ui_PrgEdActBtn3 = NULL;
lv_obj_t * ui_PrgEdActBtn3Text = NULL;
lv_obj_t * ui_PrgEdRow4Bg = NULL;
lv_obj_t * ui_PrgEdNr4 = NULL;
lv_obj_t * ui_PrgEdM1Btn4 = NULL;
lv_obj_t * ui_PrgEdM1Btn4Text = NULL;
lv_obj_t * ui_PrgEdM2Btn4 = NULL;
lv_obj_t * ui_PrgEdM2Btn4Text = NULL;
lv_obj_t * ui_PrgEdDelBtn4 = NULL;
lv_obj_t * ui_PrgEdDelBtn4Text = NULL;
lv_obj_t * ui_PrgEdActBtn4 = NULL;
lv_obj_t * ui_PrgEdActBtn4Text = NULL;
lv_obj_t * ui_PrgEdRow5Bg = NULL;
lv_obj_t * ui_PrgEdNr5 = NULL;
lv_obj_t * ui_PrgEdM1Btn5 = NULL;
lv_obj_t * ui_PrgEdM1Btn5Text = NULL;
lv_obj_t * ui_PrgEdM2Btn5 = NULL;
lv_obj_t * ui_PrgEdM2Btn5Text = NULL;
lv_obj_t * ui_PrgEdDelBtn5 = NULL;
lv_obj_t * ui_PrgEdDelBtn5Text = NULL;
lv_obj_t * ui_PrgEdActBtn5 = NULL;
lv_obj_t * ui_PrgEdActBtn5Text = NULL;
lv_obj_t * ui_PrgEdFocusBg = NULL;
lv_obj_t * ui_PrgEdFocusLbl = NULL;
lv_obj_t * ui_PrgEdBtnBarBg = NULL;
lv_obj_t * ui_PrgEdBtn1 = NULL;
lv_obj_t * ui_PrgEdBtn1Text = NULL;
lv_obj_t * ui_PrgEdBtn2 = NULL;
lv_obj_t * ui_PrgEdBtn2Text = NULL;
lv_obj_t * ui_PrgEdBtn3 = NULL;
lv_obj_t * ui_PrgEdBtn3Text = NULL;
lv_obj_t * ui_PrgEdBtn4 = NULL;
lv_obj_t * ui_PrgEdBtn4Text = NULL;
// event funtions
void ui_event_PrgEdM1Btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m1(e);
    }
}

void ui_event_PrgEdM2Btn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m2(e);
    }
}

void ui_event_PrgEdDelBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_delete_step(e);
    }
}

void ui_event_PrgEdActBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_set_step(e);
    }
}

void ui_event_PrgEdM1Btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m1(e);
    }
}

void ui_event_PrgEdM2Btn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m2(e);
    }
}

void ui_event_PrgEdDelBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_delete_step(e);
    }
}

void ui_event_PrgEdActBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_set_step(e);
    }
}

void ui_event_PrgEdM1Btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m1(e);
    }
}

void ui_event_PrgEdM2Btn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m2(e);
    }
}

void ui_event_PrgEdDelBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_delete_step(e);
    }
}

void ui_event_PrgEdActBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_set_step(e);
    }
}

void ui_event_PrgEdM1Btn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m1(e);
    }
}

void ui_event_PrgEdM2Btn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m2(e);
    }
}

void ui_event_PrgEdDelBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_delete_step(e);
    }
}

void ui_event_PrgEdActBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_set_step(e);
    }
}

void ui_event_PrgEdM1Btn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m1(e);
    }
}

void ui_event_PrgEdM2Btn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_prgedit_select_m2(e);
    }
}

void ui_event_PrgEdDelBtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_delete_step(e);
    }
}

void ui_event_PrgEdActBtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_set_step(e);
    }
}

void ui_event_PrgEdBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_add_step(e);
    }
}

void ui_event_PrgEdBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_delete_step(e);
    }
}

void ui_event_PrgEdBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_program_save(e);
    }
}

void ui_event_PrgEdBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenProgram, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenProgram_screen_init);
    }
}

// build funtions

void ui_ScreenProgramEdit_screen_init(void)
{
    ui_ScreenProgramEdit = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenProgramEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrgEdHeaderBg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdHeaderBg, 800);
    lv_obj_set_height(ui_PrgEdHeaderBg, 50);
    lv_label_set_text(ui_PrgEdHeaderBg, "");
    lv_obj_set_style_text_color(ui_PrgEdHeaderBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdHeaderBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdHeaderBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdHeaderBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdHeaderBg, lv_color_hex(0x002D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIMMLogo_PrgEd = lv_img_create(ui_ScreenProgramEdit);
    lv_img_set_src(ui_PIMMLogo_PrgEd, &ui_img_pimm_logo_png);
    lv_obj_set_width(ui_PIMMLogo_PrgEd, 1);
    lv_obj_set_height(ui_PIMMLogo_PrgEd, 1);
    lv_obj_set_x(ui_PIMMLogo_PrgEd, 1);
    lv_obj_set_y(ui_PIMMLogo_PrgEd, 0);
    lv_obj_add_flag(ui_PIMMLogo_PrgEd, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PIMMLogo_PrgEd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitelPrgEd = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_TitelPrgEd, 1);
    lv_obj_set_height(ui_TitelPrgEd, 1);
    lv_obj_set_align(ui_TitelPrgEd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitelPrgEd, "PROGRAMMA  BEWERKEN");
    lv_obj_set_style_text_color(ui_TitelPrgEd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitelPrgEd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitelPrgEd, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TitelPrgEd, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitelPrgEd, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitelPrgEd, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitelPrgEd, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitelPrgEd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitelPrgEd, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitelPrgEd, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitelPrgEd, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitelPrgEd, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdColBg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdColBg, 780);
    lv_obj_set_height(ui_PrgEdColBg, 32);
    lv_obj_set_x(ui_PrgEdColBg, 10);
    lv_obj_set_y(ui_PrgEdColBg, 57);
    lv_label_set_text(ui_PrgEdColBg, "");
    lv_obj_set_style_text_color(ui_PrgEdColBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdColBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdColBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdColBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdColBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdColBg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdColBg, lv_color_hex(0x002648), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdColBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdColBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdColBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdColBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdColBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdColHdr = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdColHdr, 770);
    lv_obj_set_height(ui_PrgEdColHdr, 24);
    lv_obj_set_x(ui_PrgEdColHdr, 14);
    lv_obj_set_y(ui_PrgEdColHdr, 61);
    lv_label_set_text(ui_PrgEdColHdr, "  Stap    Module 1 (mm)     Module 2 (mm)         Actie");
    lv_obj_set_style_text_color(ui_PrgEdColHdr, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdColHdr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdColHdr, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdColHdr, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdColHdr, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdColHdr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdColHdr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdColHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdColHdr, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdColHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdColHdr, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdColHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdRow1Bg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdRow1Bg, 780);
    lv_obj_set_height(ui_PrgEdRow1Bg, 56);
    lv_obj_set_x(ui_PrgEdRow1Bg, 10);
    lv_obj_set_y(ui_PrgEdRow1Bg, 95);
    lv_label_set_text(ui_PrgEdRow1Bg, "");
    lv_obj_set_style_text_color(ui_PrgEdRow1Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdRow1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdRow1Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdRow1Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdRow1Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdRow1Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdRow1Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdRow1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdRow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdNr1 = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdNr1, 40);
    lv_obj_set_height(ui_PrgEdNr1, 28);
    lv_obj_set_x(ui_PrgEdNr1, 18);
    lv_obj_set_y(ui_PrgEdNr1, 109);
    lv_label_set_text(ui_PrgEdNr1, "1");
    lv_obj_set_style_text_color(ui_PrgEdNr1, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdNr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdNr1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdNr1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdNr1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdNr1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdNr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn1 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM1Btn1, 190);
    lv_obj_set_height(ui_PrgEdM1Btn1, 40);
    lv_obj_set_x(ui_PrgEdM1Btn1, 62);
    lv_obj_set_y(ui_PrgEdM1Btn1, 103);
    lv_obj_add_flag(ui_PrgEdM1Btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM1Btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM1Btn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn1, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn1Text = lv_label_create(ui_PrgEdM1Btn1);
    lv_obj_set_width(ui_PrgEdM1Btn1Text, 190);
    lv_obj_set_height(ui_PrgEdM1Btn1Text, 40);
    lv_obj_set_align(ui_PrgEdM1Btn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM1Btn1Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM1Btn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM1Btn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM1Btn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM1Btn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM1Btn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM1Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM1Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM1Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM1Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM1Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn1 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM2Btn1, 190);
    lv_obj_set_height(ui_PrgEdM2Btn1, 40);
    lv_obj_set_x(ui_PrgEdM2Btn1, 260);
    lv_obj_set_y(ui_PrgEdM2Btn1, 103);
    lv_obj_add_flag(ui_PrgEdM2Btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM2Btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM2Btn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn1, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn1Text = lv_label_create(ui_PrgEdM2Btn1);
    lv_obj_set_width(ui_PrgEdM2Btn1Text, 190);
    lv_obj_set_height(ui_PrgEdM2Btn1Text, 40);
    lv_obj_set_align(ui_PrgEdM2Btn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM2Btn1Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM2Btn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM2Btn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM2Btn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM2Btn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM2Btn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM2Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM2Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM2Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM2Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM2Btn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn1 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdDelBtn1, 140);
    lv_obj_set_height(ui_PrgEdDelBtn1, 36);
    lv_obj_set_x(ui_PrgEdDelBtn1, 460);
    lv_obj_set_y(ui_PrgEdDelBtn1, 105);
    lv_obj_add_flag(ui_PrgEdDelBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdDelBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdDelBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn1, lv_color_hex(0xA00023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn1Text = lv_label_create(ui_PrgEdDelBtn1);
    lv_obj_set_width(ui_PrgEdDelBtn1Text, 140);
    lv_obj_set_height(ui_PrgEdDelBtn1Text, 36);
    lv_obj_set_align(ui_PrgEdDelBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdDelBtn1Text, "Verwijder");
    lv_obj_set_style_text_color(ui_PrgEdDelBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdDelBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdDelBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdDelBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdDelBtn1Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdDelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdDelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdDelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdDelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdDelBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn1 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdActBtn1, 140);
    lv_obj_set_height(ui_PrgEdActBtn1, 36);
    lv_obj_set_x(ui_PrgEdActBtn1, 610);
    lv_obj_set_y(ui_PrgEdActBtn1, 105);
    lv_obj_add_flag(ui_PrgEdActBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdActBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdActBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn1, lv_color_hex(0x005096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn1Text = lv_label_create(ui_PrgEdActBtn1);
    lv_obj_set_width(ui_PrgEdActBtn1Text, 140);
    lv_obj_set_height(ui_PrgEdActBtn1Text, 36);
    lv_obj_set_align(ui_PrgEdActBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdActBtn1Text, "Activeer");
    lv_obj_set_style_text_color(ui_PrgEdActBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdActBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdActBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdActBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdActBtn1Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdActBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdActBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdActBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdActBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdActBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdRow2Bg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdRow2Bg, 780);
    lv_obj_set_height(ui_PrgEdRow2Bg, 56);
    lv_obj_set_x(ui_PrgEdRow2Bg, 10);
    lv_obj_set_y(ui_PrgEdRow2Bg, 155);
    lv_label_set_text(ui_PrgEdRow2Bg, "");
    lv_obj_set_style_text_color(ui_PrgEdRow2Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdRow2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdRow2Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdRow2Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdRow2Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdRow2Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdRow2Bg, lv_color_hex(0x16283E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdRow2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdRow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdNr2 = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdNr2, 40);
    lv_obj_set_height(ui_PrgEdNr2, 28);
    lv_obj_set_x(ui_PrgEdNr2, 18);
    lv_obj_set_y(ui_PrgEdNr2, 169);
    lv_label_set_text(ui_PrgEdNr2, "2");
    lv_obj_set_style_text_color(ui_PrgEdNr2, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdNr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdNr2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdNr2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdNr2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdNr2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdNr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn2 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM1Btn2, 190);
    lv_obj_set_height(ui_PrgEdM1Btn2, 40);
    lv_obj_set_x(ui_PrgEdM1Btn2, 62);
    lv_obj_set_y(ui_PrgEdM1Btn2, 163);
    lv_obj_add_flag(ui_PrgEdM1Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM1Btn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM1Btn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn2, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn2Text = lv_label_create(ui_PrgEdM1Btn2);
    lv_obj_set_width(ui_PrgEdM1Btn2Text, 190);
    lv_obj_set_height(ui_PrgEdM1Btn2Text, 40);
    lv_obj_set_align(ui_PrgEdM1Btn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM1Btn2Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM1Btn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM1Btn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM1Btn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM1Btn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM1Btn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM1Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM1Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM1Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM1Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM1Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn2 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM2Btn2, 190);
    lv_obj_set_height(ui_PrgEdM2Btn2, 40);
    lv_obj_set_x(ui_PrgEdM2Btn2, 260);
    lv_obj_set_y(ui_PrgEdM2Btn2, 163);
    lv_obj_add_flag(ui_PrgEdM2Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM2Btn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM2Btn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn2, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn2Text = lv_label_create(ui_PrgEdM2Btn2);
    lv_obj_set_width(ui_PrgEdM2Btn2Text, 190);
    lv_obj_set_height(ui_PrgEdM2Btn2Text, 40);
    lv_obj_set_align(ui_PrgEdM2Btn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM2Btn2Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM2Btn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM2Btn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM2Btn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM2Btn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM2Btn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM2Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM2Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM2Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM2Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM2Btn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn2 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdDelBtn2, 140);
    lv_obj_set_height(ui_PrgEdDelBtn2, 36);
    lv_obj_set_x(ui_PrgEdDelBtn2, 460);
    lv_obj_set_y(ui_PrgEdDelBtn2, 165);
    lv_obj_add_flag(ui_PrgEdDelBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdDelBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdDelBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn2, lv_color_hex(0xA00023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn2Text = lv_label_create(ui_PrgEdDelBtn2);
    lv_obj_set_width(ui_PrgEdDelBtn2Text, 140);
    lv_obj_set_height(ui_PrgEdDelBtn2Text, 36);
    lv_obj_set_align(ui_PrgEdDelBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdDelBtn2Text, "Verwijder");
    lv_obj_set_style_text_color(ui_PrgEdDelBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdDelBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdDelBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdDelBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdDelBtn2Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdDelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdDelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdDelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdDelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdDelBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn2 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdActBtn2, 140);
    lv_obj_set_height(ui_PrgEdActBtn2, 36);
    lv_obj_set_x(ui_PrgEdActBtn2, 610);
    lv_obj_set_y(ui_PrgEdActBtn2, 165);
    lv_obj_add_flag(ui_PrgEdActBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdActBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdActBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn2, lv_color_hex(0x005096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn2Text = lv_label_create(ui_PrgEdActBtn2);
    lv_obj_set_width(ui_PrgEdActBtn2Text, 140);
    lv_obj_set_height(ui_PrgEdActBtn2Text, 36);
    lv_obj_set_align(ui_PrgEdActBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdActBtn2Text, "Activeer");
    lv_obj_set_style_text_color(ui_PrgEdActBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdActBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdActBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdActBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdActBtn2Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdActBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdActBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdActBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdActBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdActBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdRow3Bg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdRow3Bg, 780);
    lv_obj_set_height(ui_PrgEdRow3Bg, 56);
    lv_obj_set_x(ui_PrgEdRow3Bg, 10);
    lv_obj_set_y(ui_PrgEdRow3Bg, 215);
    lv_label_set_text(ui_PrgEdRow3Bg, "");
    lv_obj_set_style_text_color(ui_PrgEdRow3Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdRow3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdRow3Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdRow3Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdRow3Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdRow3Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdRow3Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdRow3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdRow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdNr3 = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdNr3, 40);
    lv_obj_set_height(ui_PrgEdNr3, 28);
    lv_obj_set_x(ui_PrgEdNr3, 18);
    lv_obj_set_y(ui_PrgEdNr3, 229);
    lv_label_set_text(ui_PrgEdNr3, "3");
    lv_obj_set_style_text_color(ui_PrgEdNr3, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdNr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdNr3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdNr3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdNr3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdNr3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdNr3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn3 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM1Btn3, 190);
    lv_obj_set_height(ui_PrgEdM1Btn3, 40);
    lv_obj_set_x(ui_PrgEdM1Btn3, 62);
    lv_obj_set_y(ui_PrgEdM1Btn3, 223);
    lv_obj_add_flag(ui_PrgEdM1Btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM1Btn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM1Btn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn3, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn3Text = lv_label_create(ui_PrgEdM1Btn3);
    lv_obj_set_width(ui_PrgEdM1Btn3Text, 190);
    lv_obj_set_height(ui_PrgEdM1Btn3Text, 40);
    lv_obj_set_align(ui_PrgEdM1Btn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM1Btn3Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM1Btn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM1Btn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM1Btn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM1Btn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM1Btn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM1Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM1Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM1Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM1Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM1Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn3 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM2Btn3, 190);
    lv_obj_set_height(ui_PrgEdM2Btn3, 40);
    lv_obj_set_x(ui_PrgEdM2Btn3, 260);
    lv_obj_set_y(ui_PrgEdM2Btn3, 223);
    lv_obj_add_flag(ui_PrgEdM2Btn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM2Btn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM2Btn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn3, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn3Text = lv_label_create(ui_PrgEdM2Btn3);
    lv_obj_set_width(ui_PrgEdM2Btn3Text, 190);
    lv_obj_set_height(ui_PrgEdM2Btn3Text, 40);
    lv_obj_set_align(ui_PrgEdM2Btn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM2Btn3Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM2Btn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM2Btn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM2Btn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM2Btn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM2Btn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM2Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM2Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM2Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM2Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM2Btn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn3 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdDelBtn3, 140);
    lv_obj_set_height(ui_PrgEdDelBtn3, 36);
    lv_obj_set_x(ui_PrgEdDelBtn3, 460);
    lv_obj_set_y(ui_PrgEdDelBtn3, 225);
    lv_obj_add_flag(ui_PrgEdDelBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdDelBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdDelBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn3, lv_color_hex(0xA00023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn3Text = lv_label_create(ui_PrgEdDelBtn3);
    lv_obj_set_width(ui_PrgEdDelBtn3Text, 140);
    lv_obj_set_height(ui_PrgEdDelBtn3Text, 36);
    lv_obj_set_align(ui_PrgEdDelBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdDelBtn3Text, "Verwijder");
    lv_obj_set_style_text_color(ui_PrgEdDelBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdDelBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdDelBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdDelBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdDelBtn3Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdDelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdDelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdDelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdDelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdDelBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn3 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdActBtn3, 140);
    lv_obj_set_height(ui_PrgEdActBtn3, 36);
    lv_obj_set_x(ui_PrgEdActBtn3, 610);
    lv_obj_set_y(ui_PrgEdActBtn3, 225);
    lv_obj_add_flag(ui_PrgEdActBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdActBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdActBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn3, lv_color_hex(0x005096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn3Text = lv_label_create(ui_PrgEdActBtn3);
    lv_obj_set_width(ui_PrgEdActBtn3Text, 140);
    lv_obj_set_height(ui_PrgEdActBtn3Text, 36);
    lv_obj_set_align(ui_PrgEdActBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdActBtn3Text, "Activeer");
    lv_obj_set_style_text_color(ui_PrgEdActBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdActBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdActBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdActBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdActBtn3Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdActBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdActBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdActBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdActBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdActBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdRow4Bg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdRow4Bg, 780);
    lv_obj_set_height(ui_PrgEdRow4Bg, 56);
    lv_obj_set_x(ui_PrgEdRow4Bg, 10);
    lv_obj_set_y(ui_PrgEdRow4Bg, 275);
    lv_label_set_text(ui_PrgEdRow4Bg, "");
    lv_obj_set_style_text_color(ui_PrgEdRow4Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdRow4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdRow4Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdRow4Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdRow4Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdRow4Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdRow4Bg, lv_color_hex(0x16283E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdRow4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdRow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdNr4 = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdNr4, 40);
    lv_obj_set_height(ui_PrgEdNr4, 28);
    lv_obj_set_x(ui_PrgEdNr4, 18);
    lv_obj_set_y(ui_PrgEdNr4, 289);
    lv_label_set_text(ui_PrgEdNr4, "4");
    lv_obj_set_style_text_color(ui_PrgEdNr4, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdNr4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdNr4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdNr4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdNr4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdNr4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdNr4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn4 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM1Btn4, 190);
    lv_obj_set_height(ui_PrgEdM1Btn4, 40);
    lv_obj_set_x(ui_PrgEdM1Btn4, 62);
    lv_obj_set_y(ui_PrgEdM1Btn4, 283);
    lv_obj_add_flag(ui_PrgEdM1Btn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM1Btn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM1Btn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn4, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn4Text = lv_label_create(ui_PrgEdM1Btn4);
    lv_obj_set_width(ui_PrgEdM1Btn4Text, 190);
    lv_obj_set_height(ui_PrgEdM1Btn4Text, 40);
    lv_obj_set_align(ui_PrgEdM1Btn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM1Btn4Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM1Btn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM1Btn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM1Btn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM1Btn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM1Btn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM1Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM1Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM1Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM1Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM1Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn4 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM2Btn4, 190);
    lv_obj_set_height(ui_PrgEdM2Btn4, 40);
    lv_obj_set_x(ui_PrgEdM2Btn4, 260);
    lv_obj_set_y(ui_PrgEdM2Btn4, 283);
    lv_obj_add_flag(ui_PrgEdM2Btn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM2Btn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM2Btn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn4, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn4Text = lv_label_create(ui_PrgEdM2Btn4);
    lv_obj_set_width(ui_PrgEdM2Btn4Text, 190);
    lv_obj_set_height(ui_PrgEdM2Btn4Text, 40);
    lv_obj_set_align(ui_PrgEdM2Btn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM2Btn4Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM2Btn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM2Btn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM2Btn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM2Btn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM2Btn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM2Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM2Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM2Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM2Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM2Btn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn4 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdDelBtn4, 140);
    lv_obj_set_height(ui_PrgEdDelBtn4, 36);
    lv_obj_set_x(ui_PrgEdDelBtn4, 460);
    lv_obj_set_y(ui_PrgEdDelBtn4, 285);
    lv_obj_add_flag(ui_PrgEdDelBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdDelBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdDelBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn4, lv_color_hex(0xA00023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn4Text = lv_label_create(ui_PrgEdDelBtn4);
    lv_obj_set_width(ui_PrgEdDelBtn4Text, 140);
    lv_obj_set_height(ui_PrgEdDelBtn4Text, 36);
    lv_obj_set_align(ui_PrgEdDelBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdDelBtn4Text, "Verwijder");
    lv_obj_set_style_text_color(ui_PrgEdDelBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdDelBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdDelBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdDelBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdDelBtn4Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdDelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdDelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdDelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdDelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdDelBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn4 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdActBtn4, 140);
    lv_obj_set_height(ui_PrgEdActBtn4, 36);
    lv_obj_set_x(ui_PrgEdActBtn4, 610);
    lv_obj_set_y(ui_PrgEdActBtn4, 285);
    lv_obj_add_flag(ui_PrgEdActBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdActBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdActBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn4, lv_color_hex(0x005096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn4Text = lv_label_create(ui_PrgEdActBtn4);
    lv_obj_set_width(ui_PrgEdActBtn4Text, 140);
    lv_obj_set_height(ui_PrgEdActBtn4Text, 36);
    lv_obj_set_align(ui_PrgEdActBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdActBtn4Text, "Activeer");
    lv_obj_set_style_text_color(ui_PrgEdActBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdActBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdActBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdActBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdActBtn4Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdActBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdActBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdActBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdActBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdActBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdRow5Bg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdRow5Bg, 780);
    lv_obj_set_height(ui_PrgEdRow5Bg, 56);
    lv_obj_set_x(ui_PrgEdRow5Bg, 10);
    lv_obj_set_y(ui_PrgEdRow5Bg, 335);
    lv_label_set_text(ui_PrgEdRow5Bg, "");
    lv_obj_set_style_text_color(ui_PrgEdRow5Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdRow5Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdRow5Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdRow5Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdRow5Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdRow5Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdRow5Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdRow5Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdRow5Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdNr5 = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdNr5, 40);
    lv_obj_set_height(ui_PrgEdNr5, 28);
    lv_obj_set_x(ui_PrgEdNr5, 18);
    lv_obj_set_y(ui_PrgEdNr5, 349);
    lv_label_set_text(ui_PrgEdNr5, "5");
    lv_obj_set_style_text_color(ui_PrgEdNr5, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdNr5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdNr5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdNr5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdNr5, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdNr5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdNr5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdNr5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdNr5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdNr5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdNr5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdNr5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn5 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM1Btn5, 190);
    lv_obj_set_height(ui_PrgEdM1Btn5, 40);
    lv_obj_set_x(ui_PrgEdM1Btn5, 62);
    lv_obj_set_y(ui_PrgEdM1Btn5, 343);
    lv_obj_add_flag(ui_PrgEdM1Btn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM1Btn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM1Btn5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn5, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM1Btn5Text = lv_label_create(ui_PrgEdM1Btn5);
    lv_obj_set_width(ui_PrgEdM1Btn5Text, 190);
    lv_obj_set_height(ui_PrgEdM1Btn5Text, 40);
    lv_obj_set_align(ui_PrgEdM1Btn5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM1Btn5Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM1Btn5Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM1Btn5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM1Btn5Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM1Btn5Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM1Btn5Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM1Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM1Btn5Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM1Btn5Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM1Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM1Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM1Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM1Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn5 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdM2Btn5, 190);
    lv_obj_set_height(ui_PrgEdM2Btn5, 40);
    lv_obj_set_x(ui_PrgEdM2Btn5, 260);
    lv_obj_set_y(ui_PrgEdM2Btn5, 343);
    lv_obj_add_flag(ui_PrgEdM2Btn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdM2Btn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdM2Btn5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn5, lv_color_hex(0x1C324E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdM2Btn5Text = lv_label_create(ui_PrgEdM2Btn5);
    lv_obj_set_width(ui_PrgEdM2Btn5Text, 190);
    lv_obj_set_height(ui_PrgEdM2Btn5Text, 40);
    lv_obj_set_align(ui_PrgEdM2Btn5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdM2Btn5Text, "  0.0");
    lv_obj_set_style_text_color(ui_PrgEdM2Btn5Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdM2Btn5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdM2Btn5Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdM2Btn5Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdM2Btn5Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdM2Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdM2Btn5Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdM2Btn5Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdM2Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdM2Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdM2Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdM2Btn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn5 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdDelBtn5, 140);
    lv_obj_set_height(ui_PrgEdDelBtn5, 36);
    lv_obj_set_x(ui_PrgEdDelBtn5, 460);
    lv_obj_set_y(ui_PrgEdDelBtn5, 345);
    lv_obj_add_flag(ui_PrgEdDelBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdDelBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdDelBtn5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn5, lv_color_hex(0xA00023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdDelBtn5Text = lv_label_create(ui_PrgEdDelBtn5);
    lv_obj_set_width(ui_PrgEdDelBtn5Text, 140);
    lv_obj_set_height(ui_PrgEdDelBtn5Text, 36);
    lv_obj_set_align(ui_PrgEdDelBtn5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdDelBtn5Text, "Verwijder");
    lv_obj_set_style_text_color(ui_PrgEdDelBtn5Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdDelBtn5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdDelBtn5Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdDelBtn5Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdDelBtn5Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdDelBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdDelBtn5Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdDelBtn5Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdDelBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdDelBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdDelBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdDelBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn5 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdActBtn5, 140);
    lv_obj_set_height(ui_PrgEdActBtn5, 36);
    lv_obj_set_x(ui_PrgEdActBtn5, 610);
    lv_obj_set_y(ui_PrgEdActBtn5, 345);
    lv_obj_add_flag(ui_PrgEdActBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdActBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdActBtn5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn5, lv_color_hex(0x005096), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdActBtn5Text = lv_label_create(ui_PrgEdActBtn5);
    lv_obj_set_width(ui_PrgEdActBtn5Text, 140);
    lv_obj_set_height(ui_PrgEdActBtn5Text, 36);
    lv_obj_set_align(ui_PrgEdActBtn5Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdActBtn5Text, "Activeer");
    lv_obj_set_style_text_color(ui_PrgEdActBtn5Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdActBtn5Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdActBtn5Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdActBtn5Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdActBtn5Text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdActBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdActBtn5Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdActBtn5Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdActBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdActBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdActBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdActBtn5Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdFocusBg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdFocusBg, 780);
    lv_obj_set_height(ui_PrgEdFocusBg, 22);
    lv_obj_set_x(ui_PrgEdFocusBg, 10);
    lv_obj_set_y(ui_PrgEdFocusBg, 396);
    lv_label_set_text(ui_PrgEdFocusBg, "");
    lv_obj_set_style_text_color(ui_PrgEdFocusBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdFocusBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdFocusBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdFocusBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdFocusBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdFocusBg, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdFocusBg, lv_color_hex(0x1E3250), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdFocusBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdFocusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdFocusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdFocusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdFocusBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdFocusLbl = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdFocusLbl, 770);
    lv_obj_set_height(ui_PrgEdFocusLbl, 18);
    lv_obj_set_x(ui_PrgEdFocusLbl, 14);
    lv_obj_set_y(ui_PrgEdFocusLbl, 398);
    lv_label_set_text(ui_PrgEdFocusLbl, "Geselecteerd: Stap 1  –  Module 1   |   Enkoder +/- past waarde aan");
    lv_obj_set_style_text_color(ui_PrgEdFocusLbl, lv_color_hex(0xFFC850), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdFocusLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdFocusLbl, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdFocusLbl, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdFocusLbl, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdFocusLbl, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdFocusLbl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdFocusLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdFocusLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdFocusLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdFocusLbl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdFocusLbl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtnBarBg = lv_label_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdBtnBarBg, 800);
    lv_obj_set_height(ui_PrgEdBtnBarBg, 60);
    lv_obj_set_x(ui_PrgEdBtnBarBg, 0);
    lv_obj_set_y(ui_PrgEdBtnBarBg, 420);
    lv_label_set_text(ui_PrgEdBtnBarBg, "");
    lv_obj_set_style_text_color(ui_PrgEdBtnBarBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdBtnBarBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdBtnBarBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdBtnBarBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtnBarBg, lv_color_hex(0x080F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn1 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdBtn1, 200);
    lv_obj_set_height(ui_PrgEdBtn1, 57);
    lv_obj_set_x(ui_PrgEdBtn1, 0);
    lv_obj_set_y(ui_PrgEdBtn1, 421);
    lv_obj_add_flag(ui_PrgEdBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn1, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn1Text = lv_label_create(ui_PrgEdBtn1);
    lv_obj_set_width(ui_PrgEdBtn1Text, 200);
    lv_obj_set_height(ui_PrgEdBtn1Text, 57);
    lv_obj_set_align(ui_PrgEdBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdBtn1Text, "Stap Toevoegen");
    lv_obj_set_style_text_color(ui_PrgEdBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdBtn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn2 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdBtn2, 200);
    lv_obj_set_height(ui_PrgEdBtn2, 57);
    lv_obj_set_x(ui_PrgEdBtn2, 200);
    lv_obj_set_y(ui_PrgEdBtn2, 421);
    lv_obj_add_flag(ui_PrgEdBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn2Text = lv_label_create(ui_PrgEdBtn2);
    lv_obj_set_width(ui_PrgEdBtn2Text, 200);
    lv_obj_set_height(ui_PrgEdBtn2Text, 57);
    lv_obj_set_align(ui_PrgEdBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdBtn2Text, "Stap Verwijderen");
    lv_obj_set_style_text_color(ui_PrgEdBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdBtn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn3 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdBtn3, 200);
    lv_obj_set_height(ui_PrgEdBtn3, 57);
    lv_obj_set_x(ui_PrgEdBtn3, 400);
    lv_obj_set_y(ui_PrgEdBtn3, 421);
    lv_obj_add_flag(ui_PrgEdBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn3, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn3Text = lv_label_create(ui_PrgEdBtn3);
    lv_obj_set_width(ui_PrgEdBtn3Text, 200);
    lv_obj_set_height(ui_PrgEdBtn3Text, 57);
    lv_obj_set_align(ui_PrgEdBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdBtn3Text, "Opslaan");
    lv_obj_set_style_text_color(ui_PrgEdBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdBtn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn4 = lv_btn_create(ui_ScreenProgramEdit);
    lv_obj_set_width(ui_PrgEdBtn4, 200);
    lv_obj_set_height(ui_PrgEdBtn4, 57);
    lv_obj_set_x(ui_PrgEdBtn4, 600);
    lv_obj_set_y(ui_PrgEdBtn4, 421);
    lv_obj_add_flag(ui_PrgEdBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrgEdBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrgEdBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn4, lv_color_hex(0x233755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrgEdBtn4Text = lv_label_create(ui_PrgEdBtn4);
    lv_obj_set_width(ui_PrgEdBtn4Text, 200);
    lv_obj_set_height(ui_PrgEdBtn4Text, 57);
    lv_obj_set_align(ui_PrgEdBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrgEdBtn4Text, "Terug");
    lv_obj_set_style_text_color(ui_PrgEdBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrgEdBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PrgEdBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PrgEdBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrgEdBtn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PrgEdBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrgEdBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrgEdBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrgEdBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrgEdBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrgEdBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrgEdBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PrgEdM1Btn1, ui_event_PrgEdM1Btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM2Btn1, ui_event_PrgEdM2Btn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdDelBtn1, ui_event_PrgEdDelBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdActBtn1, ui_event_PrgEdActBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM1Btn2, ui_event_PrgEdM1Btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM2Btn2, ui_event_PrgEdM2Btn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdDelBtn2, ui_event_PrgEdDelBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdActBtn2, ui_event_PrgEdActBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM1Btn3, ui_event_PrgEdM1Btn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM2Btn3, ui_event_PrgEdM2Btn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdDelBtn3, ui_event_PrgEdDelBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdActBtn3, ui_event_PrgEdActBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM1Btn4, ui_event_PrgEdM1Btn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM2Btn4, ui_event_PrgEdM2Btn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdDelBtn4, ui_event_PrgEdDelBtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdActBtn4, ui_event_PrgEdActBtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM1Btn5, ui_event_PrgEdM1Btn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdM2Btn5, ui_event_PrgEdM2Btn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdDelBtn5, ui_event_PrgEdDelBtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdActBtn5, ui_event_PrgEdActBtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdBtn1, ui_event_PrgEdBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdBtn2, ui_event_PrgEdBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdBtn3, ui_event_PrgEdBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrgEdBtn4, ui_event_PrgEdBtn4, LV_EVENT_ALL, NULL);

}

void ui_ScreenProgramEdit_screen_destroy(void)
{
    if(ui_ScreenProgramEdit) lv_obj_del(ui_ScreenProgramEdit);

    // NULL screen variables
    ui_ScreenProgramEdit = NULL;
    ui_PrgEdHeaderBg = NULL;
    ui_PIMMLogo_PrgEd = NULL;
    ui_TitelPrgEd = NULL;
    ui_PrgEdColBg = NULL;
    ui_PrgEdColHdr = NULL;
    ui_PrgEdRow1Bg = NULL;
    ui_PrgEdNr1 = NULL;
    ui_PrgEdM1Btn1 = NULL;
    ui_PrgEdM1Btn1Text = NULL;
    ui_PrgEdM2Btn1 = NULL;
    ui_PrgEdM2Btn1Text = NULL;
    ui_PrgEdDelBtn1 = NULL;
    ui_PrgEdDelBtn1Text = NULL;
    ui_PrgEdActBtn1 = NULL;
    ui_PrgEdActBtn1Text = NULL;
    ui_PrgEdRow2Bg = NULL;
    ui_PrgEdNr2 = NULL;
    ui_PrgEdM1Btn2 = NULL;
    ui_PrgEdM1Btn2Text = NULL;
    ui_PrgEdM2Btn2 = NULL;
    ui_PrgEdM2Btn2Text = NULL;
    ui_PrgEdDelBtn2 = NULL;
    ui_PrgEdDelBtn2Text = NULL;
    ui_PrgEdActBtn2 = NULL;
    ui_PrgEdActBtn2Text = NULL;
    ui_PrgEdRow3Bg = NULL;
    ui_PrgEdNr3 = NULL;
    ui_PrgEdM1Btn3 = NULL;
    ui_PrgEdM1Btn3Text = NULL;
    ui_PrgEdM2Btn3 = NULL;
    ui_PrgEdM2Btn3Text = NULL;
    ui_PrgEdDelBtn3 = NULL;
    ui_PrgEdDelBtn3Text = NULL;
    ui_PrgEdActBtn3 = NULL;
    ui_PrgEdActBtn3Text = NULL;
    ui_PrgEdRow4Bg = NULL;
    ui_PrgEdNr4 = NULL;
    ui_PrgEdM1Btn4 = NULL;
    ui_PrgEdM1Btn4Text = NULL;
    ui_PrgEdM2Btn4 = NULL;
    ui_PrgEdM2Btn4Text = NULL;
    ui_PrgEdDelBtn4 = NULL;
    ui_PrgEdDelBtn4Text = NULL;
    ui_PrgEdActBtn4 = NULL;
    ui_PrgEdActBtn4Text = NULL;
    ui_PrgEdRow5Bg = NULL;
    ui_PrgEdNr5 = NULL;
    ui_PrgEdM1Btn5 = NULL;
    ui_PrgEdM1Btn5Text = NULL;
    ui_PrgEdM2Btn5 = NULL;
    ui_PrgEdM2Btn5Text = NULL;
    ui_PrgEdDelBtn5 = NULL;
    ui_PrgEdDelBtn5Text = NULL;
    ui_PrgEdActBtn5 = NULL;
    ui_PrgEdActBtn5Text = NULL;
    ui_PrgEdFocusBg = NULL;
    ui_PrgEdFocusLbl = NULL;
    ui_PrgEdBtnBarBg = NULL;
    ui_PrgEdBtn1 = NULL;
    ui_PrgEdBtn1Text = NULL;
    ui_PrgEdBtn2 = NULL;
    ui_PrgEdBtn2Text = NULL;
    ui_PrgEdBtn3 = NULL;
    ui_PrgEdBtn3Text = NULL;
    ui_PrgEdBtn4 = NULL;
    ui_PrgEdBtn4Text = NULL;

}
