// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPROGRAM_H
#define UI_SCREENPROGRAM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenProgram
extern void ui_ScreenProgram_screen_init(void);
extern void ui_ScreenProgram_screen_destroy(void);
extern lv_obj_t * ui_ScreenProgram;
extern lv_obj_t * ui_ProgHeaderBg;
extern lv_obj_t * ui_PIMMLogo_Prog;
extern lv_obj_t * ui_TitelProg;
extern lv_obj_t * ui_ProgStepBg;
extern lv_obj_t * ui_LblStepNr;
extern lv_obj_t * ui_LblEncHintProg;
extern lv_obj_t * ui_LblStepM1;
extern lv_obj_t * ui_LblStepM2;
extern lv_obj_t * ui_ProgListHdrBg;
extern lv_obj_t * ui_ProgListHdr;
extern lv_obj_t * ui_ProgRow1Bg;
extern lv_obj_t * ui_ProgRow1;
extern lv_obj_t * ui_ProgRow2Bg;
extern lv_obj_t * ui_ProgRow2;
extern lv_obj_t * ui_ProgRow3Bg;
extern lv_obj_t * ui_ProgRow3;
extern lv_obj_t * ui_ProgRow4Bg;
extern lv_obj_t * ui_ProgRow4;
extern lv_obj_t * ui_ProgRow5Bg;
extern lv_obj_t * ui_ProgRow5;
extern lv_obj_t * ui_ProgHint;
extern lv_obj_t * ui_ProgBtnBarBg;
extern void ui_event_ProgBtn1(lv_event_t * e);
extern lv_obj_t * ui_ProgBtn1;
extern lv_obj_t * ui_ProgBtn1Text;
extern void ui_event_ProgBtn2(lv_event_t * e);
extern lv_obj_t * ui_ProgBtn2;
extern lv_obj_t * ui_ProgBtn2Text;
extern void ui_event_ProgBtn3(lv_event_t * e);
extern lv_obj_t * ui_ProgBtn3;
extern lv_obj_t * ui_ProgBtn3Text;
extern void ui_event_ProgBtn4(lv_event_t * e);
extern lv_obj_t * ui_ProgBtn4;
extern lv_obj_t * ui_ProgBtn4Text;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

