// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPRESETSELECT_H
#define UI_SCREENPRESETSELECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPresetselect
extern void ui_ScreenPresetselect_screen_init(void);
extern void ui_ScreenPresetselect_screen_destroy(void);
extern lv_obj_t * ui_ScreenPresetselect;
extern lv_obj_t * ui_PSHeaderBg;
extern lv_obj_t * ui_PIMMLogo_PS;
extern lv_obj_t * ui_TitelPS;
extern lv_obj_t * ui_PSHintBg;
extern lv_obj_t * ui_PSHint;
extern lv_obj_t * ui_PSCard1Bg;
extern lv_obj_t * ui_PSCardNr1;
extern lv_obj_t * ui_PSCardDiv1;
extern lv_obj_t * ui_PSCardName1;
extern lv_obj_t * ui_PSCardM11;
extern lv_obj_t * ui_PSCardM21;
extern void ui_event_PSSelBtn1(lv_event_t * e);
extern lv_obj_t * ui_PSSelBtn1;
extern lv_obj_t * ui_PSSelBtn1Text;
extern lv_obj_t * ui_PSCard2Bg;
extern lv_obj_t * ui_PSCardNr2;
extern lv_obj_t * ui_PSCardDiv2;
extern lv_obj_t * ui_PSCardName2;
extern lv_obj_t * ui_PSCardM12;
extern lv_obj_t * ui_PSCardM22;
extern void ui_event_PSSelBtn2(lv_event_t * e);
extern lv_obj_t * ui_PSSelBtn2;
extern lv_obj_t * ui_PSSelBtn2Text;
extern lv_obj_t * ui_PSCard3Bg;
extern lv_obj_t * ui_PSCardNr3;
extern lv_obj_t * ui_PSCardDiv3;
extern lv_obj_t * ui_PSCardName3;
extern lv_obj_t * ui_PSCardM1_3;
extern lv_obj_t * ui_PSCardM23;
extern void ui_event_PSSelBtn3(lv_event_t * e);
extern lv_obj_t * ui_PSSelBtn3;
extern lv_obj_t * ui_PSSelBtn3Text;
extern lv_obj_t * ui_PSCard4Bg;
extern lv_obj_t * ui_PSCardNr4;
extern lv_obj_t * ui_PSCardDiv4;
extern lv_obj_t * ui_PSCardName4;
extern lv_obj_t * ui_PSCardM1_4;
extern lv_obj_t * ui_PSCardM24;
extern void ui_event_PSSelBtn4(lv_event_t * e);
extern lv_obj_t * ui_PSSelBtn4;
extern lv_obj_t * ui_PSSelBtn4Text;
extern lv_obj_t * ui_PSSelInfoBg;
extern lv_obj_t * ui_PSSelInfo;
extern lv_obj_t * ui_PSBtnBarBg;
extern void ui_event_PSBtn1(lv_event_t * e);
extern lv_obj_t * ui_PSBtn1;
extern lv_obj_t * ui_PSBtn1Text;
extern void ui_event_PSBtn2(lv_event_t * e);
extern lv_obj_t * ui_PSBtn2;
extern lv_obj_t * ui_PSBtn2Text;
extern void ui_event_PSBtn3(lv_event_t * e);
extern lv_obj_t * ui_PSBtn3;
extern lv_obj_t * ui_PSBtn3Text;
extern void ui_event_PSBtn4(lv_event_t * e);
extern lv_obj_t * ui_PSBtn4;
extern lv_obj_t * ui_PSBtn4Text;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

