// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPRESETEDIT_H
#define UI_SCREENPRESETEDIT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPresetedit
extern void ui_ScreenPresetedit_screen_init(void);
extern void ui_ScreenPresetedit_screen_destroy(void);
extern lv_obj_t * ui_ScreenPresetedit;
extern lv_obj_t * ui_PEHeaderBg;
extern lv_obj_t * ui_PIMMLogo_PE;
extern lv_obj_t * ui_TitelPE;
extern lv_obj_t * ui_PELeftBg;
extern lv_obj_t * ui_PEColHdrBg;
extern lv_obj_t * ui_PEColHdrNr;
extern lv_obj_t * ui_PEColHdrM1;
extern lv_obj_t * ui_PEColHdrM2;
extern lv_obj_t * ui_PEColHdrSync;
extern lv_obj_t * ui_PERow1Bg;
extern lv_obj_t * ui_PERowNr1;
extern void ui_event_PEPreset1M1(lv_event_t * e);
extern lv_obj_t * ui_PEPreset1M1;
extern void ui_event_PEPreset1M2(lv_event_t * e);
extern lv_obj_t * ui_PEPreset1M2;
extern void ui_event_PESync1(lv_event_t * e);
extern lv_obj_t * ui_PESync1;
extern lv_obj_t * ui_PESync1Text;
extern lv_obj_t * ui_PERow2Bg;
extern lv_obj_t * ui_PERowNr2;
extern void ui_event_PEPreset2M1(lv_event_t * e);
extern lv_obj_t * ui_PEPreset2M1;
extern void ui_event_PEPreset2M2(lv_event_t * e);
extern lv_obj_t * ui_PEPreset2M2;
extern void ui_event_PESync2(lv_event_t * e);
extern lv_obj_t * ui_PESync2;
extern lv_obj_t * ui_PESync2Text;
extern lv_obj_t * ui_PERow3Bg;
extern lv_obj_t * ui_PERowNr3;
extern void ui_event_PEPreset3M1(lv_event_t * e);
extern lv_obj_t * ui_PEPreset3M1;
extern void ui_event_PEPreset3M2(lv_event_t * e);
extern lv_obj_t * ui_PEPreset3M2;
extern void ui_event_PESync3(lv_event_t * e);
extern lv_obj_t * ui_PESync3;
extern lv_obj_t * ui_PESync3Text;
extern lv_obj_t * ui_PERow4Bg;
extern lv_obj_t * ui_PERowNr4;
extern void ui_event_PEPreset4M1(lv_event_t * e);
extern lv_obj_t * ui_PEPreset4M1;
extern void ui_event_PEPreset4M2(lv_event_t * e);
extern lv_obj_t * ui_PEPreset4M2;
extern void ui_event_PESync4(lv_event_t * e);
extern lv_obj_t * ui_PESync4;
extern lv_obj_t * ui_PESync4Text;
extern lv_obj_t * ui_PEHint;
extern lv_obj_t * ui_KeyboardPresetedit;
extern lv_obj_t * ui_PEBtnBarBg;
extern void ui_event_PEBtn1(lv_event_t * e);
extern lv_obj_t * ui_PEBtn1;
extern lv_obj_t * ui_PEBtn1Text;
extern void ui_event_PEBtn2(lv_event_t * e);
extern lv_obj_t * ui_PEBtn2;
extern lv_obj_t * ui_PEBtn2Text;
extern void ui_event_PEBtn3(lv_event_t * e);
extern lv_obj_t * ui_PEBtn3;
extern lv_obj_t * ui_PEBtn3Text;
extern void ui_event_PEBtn4(lv_event_t * e);
extern lv_obj_t * ui_PEBtn4;
extern lv_obj_t * ui_PEBtn4Text;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

