// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenPresetedit = NULL;
lv_obj_t * ui_PEHeaderBg = NULL;
lv_obj_t * ui_PIMMLogo_PE = NULL;
lv_obj_t * ui_TitelPE = NULL;
lv_obj_t * ui_PELeftBg = NULL;
lv_obj_t * ui_PEColHdrBg = NULL;
lv_obj_t * ui_PEColHdrNr = NULL;
lv_obj_t * ui_PEColHdrM1 = NULL;
lv_obj_t * ui_PEColHdrM2 = NULL;
lv_obj_t * ui_PEColHdrSync = NULL;
lv_obj_t * ui_PERow1Bg = NULL;
lv_obj_t * ui_PERowNr1 = NULL;
lv_obj_t * ui_PEPreset1M1 = NULL;
lv_obj_t * ui_PEPreset1M2 = NULL;
lv_obj_t * ui_PESync1 = NULL;
lv_obj_t * ui_PESync1Text = NULL;
lv_obj_t * ui_PERow2Bg = NULL;
lv_obj_t * ui_PERowNr2 = NULL;
lv_obj_t * ui_PEPreset2M1 = NULL;
lv_obj_t * ui_PEPreset2M2 = NULL;
lv_obj_t * ui_PESync2 = NULL;
lv_obj_t * ui_PESync2Text = NULL;
lv_obj_t * ui_PERow3Bg = NULL;
lv_obj_t * ui_PERowNr3 = NULL;
lv_obj_t * ui_PEPreset3M1 = NULL;
lv_obj_t * ui_PEPreset3M2 = NULL;
lv_obj_t * ui_PESync3 = NULL;
lv_obj_t * ui_PESync3Text = NULL;
lv_obj_t * ui_PERow4Bg = NULL;
lv_obj_t * ui_PERowNr4 = NULL;
lv_obj_t * ui_PEPreset4M1 = NULL;
lv_obj_t * ui_PEPreset4M2 = NULL;
lv_obj_t * ui_PESync4 = NULL;
lv_obj_t * ui_PESync4Text = NULL;
lv_obj_t * ui_PEHint = NULL;
lv_obj_t * ui_KeyboardPresetedit = NULL;
lv_obj_t * ui_PEBtnBarBg = NULL;
lv_obj_t * ui_PEBtn1 = NULL;
lv_obj_t * ui_PEBtn1Text = NULL;
lv_obj_t * ui_PEBtn2 = NULL;
lv_obj_t * ui_PEBtn2Text = NULL;
lv_obj_t * ui_PEBtn3 = NULL;
lv_obj_t * ui_PEBtn3Text = NULL;
lv_obj_t * ui_PEBtn4 = NULL;
lv_obj_t * ui_PEBtn4Text = NULL;
// event funtions
void ui_event_PEPreset1M1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PEPreset1M2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PESync1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_toggle_preset_sync(e);
    }
}

void ui_event_PEPreset2M1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PEPreset2M2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PESync2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_toggle_preset_sync(e);
    }
}

void ui_event_PEPreset3M1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PEPreset3M2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PESync3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_toggle_preset_sync(e);
    }
}

void ui_event_PEPreset4M1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PEPreset4M2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_preset_focus_textarea(e);
    }
}

void ui_event_PESync4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_toggle_preset_sync(e);
    }
}

void ui_event_PEBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_save_presets(e);
    }
}

void ui_event_PEBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_clear_preset_field(e);
    }
}

void ui_event_PEBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pimm_restore_preset(e);
    }
}

void ui_event_PEBtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPresetselect, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenPresetselect_screen_init);
    }
}

// build funtions

void ui_ScreenPresetedit_screen_init(void)
{
    ui_ScreenPresetedit = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPresetedit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PEHeaderBg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEHeaderBg, 800);
    lv_obj_set_height(ui_PEHeaderBg, 50);
    lv_label_set_text(ui_PEHeaderBg, "");
    lv_obj_set_style_text_color(ui_PEHeaderBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEHeaderBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEHeaderBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEHeaderBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEHeaderBg, lv_color_hex(0x002D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEHeaderBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEHeaderBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PIMMLogo_PE = lv_img_create(ui_ScreenPresetedit);
    lv_img_set_src(ui_PIMMLogo_PE, &ui_img_pimm_logo_png);
    lv_obj_set_width(ui_PIMMLogo_PE, 1);
    lv_obj_set_height(ui_PIMMLogo_PE, 1);
    lv_obj_set_x(ui_PIMMLogo_PE, 1);
    lv_obj_set_y(ui_PIMMLogo_PE, 0);
    lv_obj_add_flag(ui_PIMMLogo_PE, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PIMMLogo_PE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TitelPE = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_TitelPE, 1);
    lv_obj_set_height(ui_TitelPE, 1);
    lv_obj_set_align(ui_TitelPE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitelPE, "PRESET BEWERKEN");
    lv_obj_set_style_text_color(ui_TitelPE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitelPE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitelPE, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TitelPE, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitelPE, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TitelPE, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TitelPE, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TitelPE, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TitelPE, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TitelPE, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TitelPE, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TitelPE, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PELeftBg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PELeftBg, 355);
    lv_obj_set_height(ui_PELeftBg, 363);
    lv_obj_set_x(ui_PELeftBg, 10);
    lv_obj_set_y(ui_PELeftBg, 55);
    lv_label_set_text(ui_PELeftBg, "");
    lv_obj_set_style_text_color(ui_PELeftBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PELeftBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PELeftBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PELeftBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PELeftBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PELeftBg, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PELeftBg, lv_color_hex(0x0C1628), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PELeftBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PELeftBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PELeftBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PELeftBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PELeftBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEColHdrBg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEColHdrBg, 355);
    lv_obj_set_height(ui_PEColHdrBg, 32);
    lv_obj_set_x(ui_PEColHdrBg, 10);
    lv_obj_set_y(ui_PEColHdrBg, 55);
    lv_label_set_text(ui_PEColHdrBg, "");
    lv_obj_set_style_text_color(ui_PEColHdrBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEColHdrBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEColHdrBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEColHdrBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEColHdrBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEColHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEColHdrBg, lv_color_hex(0x002D5A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEColHdrBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEColHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEColHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEColHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEColHdrBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEColHdrNr = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEColHdrNr, 26);
    lv_obj_set_height(ui_PEColHdrNr, 26);
    lv_obj_set_x(ui_PEColHdrNr, 10);
    lv_obj_set_y(ui_PEColHdrNr, 58);
    lv_label_set_text(ui_PEColHdrNr, "#");
    lv_obj_set_style_text_color(ui_PEColHdrNr, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEColHdrNr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEColHdrNr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEColHdrNr, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEColHdrNr, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEColHdrNr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEColHdrNr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEColHdrNr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEColHdrNr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEColHdrNr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEColHdrNr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEColHdrNr, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEColHdrM1 = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEColHdrM1, 118);
    lv_obj_set_height(ui_PEColHdrM1, 26);
    lv_obj_set_x(ui_PEColHdrM1, 40);
    lv_obj_set_y(ui_PEColHdrM1, 58);
    lv_label_set_text(ui_PEColHdrM1, "Module 1 (mm)");
    lv_obj_set_style_text_color(ui_PEColHdrM1, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEColHdrM1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEColHdrM1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEColHdrM1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEColHdrM1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEColHdrM1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEColHdrM1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEColHdrM1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEColHdrM1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEColHdrM1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEColHdrM1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEColHdrM1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEColHdrM2 = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEColHdrM2, 118);
    lv_obj_set_height(ui_PEColHdrM2, 26);
    lv_obj_set_x(ui_PEColHdrM2, 162);
    lv_obj_set_y(ui_PEColHdrM2, 58);
    lv_label_set_text(ui_PEColHdrM2, "Module 2 (mm)");
    lv_obj_set_style_text_color(ui_PEColHdrM2, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEColHdrM2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEColHdrM2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEColHdrM2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEColHdrM2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEColHdrM2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEColHdrM2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEColHdrM2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEColHdrM2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEColHdrM2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEColHdrM2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEColHdrM2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEColHdrSync = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEColHdrSync, 71);
    lv_obj_set_height(ui_PEColHdrSync, 26);
    lv_obj_set_x(ui_PEColHdrSync, 284);
    lv_obj_set_y(ui_PEColHdrSync, 58);
    lv_label_set_text(ui_PEColHdrSync, "Koppel");
    lv_obj_set_style_text_color(ui_PEColHdrSync, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEColHdrSync, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEColHdrSync, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEColHdrSync, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEColHdrSync, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEColHdrSync, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEColHdrSync, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEColHdrSync, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEColHdrSync, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEColHdrSync, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEColHdrSync, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEColHdrSync, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERow1Bg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERow1Bg, 355);
    lv_obj_set_height(ui_PERow1Bg, 68);
    lv_obj_set_x(ui_PERow1Bg, 10);
    lv_obj_set_y(ui_PERow1Bg, 89);
    lv_label_set_text(ui_PERow1Bg, "");
    lv_obj_set_style_text_color(ui_PERow1Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERow1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERow1Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERow1Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERow1Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERow1Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERow1Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERow1Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERow1Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERowNr1 = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERowNr1, 26);
    lv_obj_set_height(ui_PERowNr1, 52);
    lv_obj_set_x(ui_PERowNr1, 10);
    lv_obj_set_y(ui_PERowNr1, 97);
    lv_label_set_text(ui_PERowNr1, "1");
    lv_obj_set_style_text_color(ui_PERowNr1, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERowNr1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERowNr1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERowNr1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERowNr1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERowNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERowNr1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERowNr1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERowNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERowNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERowNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERowNr1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEPreset1M1 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset1M1, 118);
    lv_obj_set_height(ui_PEPreset1M1, 40);
    lv_obj_set_x(ui_PEPreset1M1, 40);
    lv_obj_set_y(ui_PEPreset1M1, 103);
    lv_textarea_set_placeholder_text(ui_PEPreset1M1, "0.0");

    ui_PEPreset1M2 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset1M2, 118);
    lv_obj_set_height(ui_PEPreset1M2, 40);
    lv_obj_set_x(ui_PEPreset1M2, 162);
    lv_obj_set_y(ui_PEPreset1M2, 103);
    lv_textarea_set_placeholder_text(ui_PEPreset1M2, "0.0");

    ui_PESync1 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PESync1, 71);
    lv_obj_set_height(ui_PESync1, 40);
    lv_obj_set_x(ui_PESync1, 284);
    lv_obj_set_y(ui_PESync1, 103);
    lv_obj_add_flag(ui_PESync1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PESync1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PESync1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync1, lv_color_hex(0x1C375A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PESync1Text = lv_label_create(ui_PESync1);
    lv_obj_set_width(ui_PESync1Text, 71);
    lv_obj_set_height(ui_PESync1Text, 40);
    lv_obj_set_align(ui_PESync1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PESync1Text, "=");
    lv_obj_set_style_text_color(ui_PESync1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PESync1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PESync1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PESync1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PESync1Text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PESync1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PESync1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PESync1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PESync1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PESync1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERow2Bg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERow2Bg, 355);
    lv_obj_set_height(ui_PERow2Bg, 68);
    lv_obj_set_x(ui_PERow2Bg, 10);
    lv_obj_set_y(ui_PERow2Bg, 159);
    lv_label_set_text(ui_PERow2Bg, "");
    lv_obj_set_style_text_color(ui_PERow2Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERow2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERow2Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERow2Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERow2Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERow2Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERow2Bg, lv_color_hex(0x182A40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERow2Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERow2Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERowNr2 = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERowNr2, 26);
    lv_obj_set_height(ui_PERowNr2, 52);
    lv_obj_set_x(ui_PERowNr2, 10);
    lv_obj_set_y(ui_PERowNr2, 167);
    lv_label_set_text(ui_PERowNr2, "2");
    lv_obj_set_style_text_color(ui_PERowNr2, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERowNr2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERowNr2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERowNr2, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERowNr2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERowNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERowNr2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERowNr2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERowNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERowNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERowNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERowNr2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEPreset2M1 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset2M1, 118);
    lv_obj_set_height(ui_PEPreset2M1, 40);
    lv_obj_set_x(ui_PEPreset2M1, 40);
    lv_obj_set_y(ui_PEPreset2M1, 173);
    lv_textarea_set_placeholder_text(ui_PEPreset2M1, "0.0");

    ui_PEPreset2M2 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset2M2, 118);
    lv_obj_set_height(ui_PEPreset2M2, 40);
    lv_obj_set_x(ui_PEPreset2M2, 162);
    lv_obj_set_y(ui_PEPreset2M2, 173);
    lv_textarea_set_placeholder_text(ui_PEPreset2M2, "0.0");

    ui_PESync2 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PESync2, 71);
    lv_obj_set_height(ui_PESync2, 40);
    lv_obj_set_x(ui_PESync2, 284);
    lv_obj_set_y(ui_PESync2, 173);
    lv_obj_add_flag(ui_PESync2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PESync2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PESync2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync2, lv_color_hex(0x1C375A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PESync2Text = lv_label_create(ui_PESync2);
    lv_obj_set_width(ui_PESync2Text, 71);
    lv_obj_set_height(ui_PESync2Text, 40);
    lv_obj_set_align(ui_PESync2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PESync2Text, "=");
    lv_obj_set_style_text_color(ui_PESync2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PESync2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PESync2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PESync2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PESync2Text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PESync2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PESync2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PESync2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PESync2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PESync2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERow3Bg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERow3Bg, 355);
    lv_obj_set_height(ui_PERow3Bg, 68);
    lv_obj_set_x(ui_PERow3Bg, 10);
    lv_obj_set_y(ui_PERow3Bg, 229);
    lv_label_set_text(ui_PERow3Bg, "");
    lv_obj_set_style_text_color(ui_PERow3Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERow3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERow3Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERow3Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERow3Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERow3Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERow3Bg, lv_color_hex(0x122034), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERow3Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERow3Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERowNr3 = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERowNr3, 26);
    lv_obj_set_height(ui_PERowNr3, 52);
    lv_obj_set_x(ui_PERowNr3, 10);
    lv_obj_set_y(ui_PERowNr3, 237);
    lv_label_set_text(ui_PERowNr3, "3");
    lv_obj_set_style_text_color(ui_PERowNr3, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERowNr3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERowNr3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERowNr3, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERowNr3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERowNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERowNr3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERowNr3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERowNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERowNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERowNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERowNr3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEPreset3M1 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset3M1, 118);
    lv_obj_set_height(ui_PEPreset3M1, 40);
    lv_obj_set_x(ui_PEPreset3M1, 40);
    lv_obj_set_y(ui_PEPreset3M1, 243);
    lv_textarea_set_placeholder_text(ui_PEPreset3M1, "0.0");

    ui_PEPreset3M2 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset3M2, 118);
    lv_obj_set_height(ui_PEPreset3M2, 40);
    lv_obj_set_x(ui_PEPreset3M2, 162);
    lv_obj_set_y(ui_PEPreset3M2, 243);
    lv_textarea_set_placeholder_text(ui_PEPreset3M2, "0.0");

    ui_PESync3 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PESync3, 71);
    lv_obj_set_height(ui_PESync3, 40);
    lv_obj_set_x(ui_PESync3, 284);
    lv_obj_set_y(ui_PESync3, 243);
    lv_obj_add_flag(ui_PESync3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PESync3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PESync3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync3, lv_color_hex(0x1C375A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PESync3Text = lv_label_create(ui_PESync3);
    lv_obj_set_width(ui_PESync3Text, 71);
    lv_obj_set_height(ui_PESync3Text, 40);
    lv_obj_set_align(ui_PESync3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PESync3Text, "=");
    lv_obj_set_style_text_color(ui_PESync3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PESync3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PESync3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PESync3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PESync3Text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PESync3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PESync3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PESync3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PESync3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PESync3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERow4Bg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERow4Bg, 355);
    lv_obj_set_height(ui_PERow4Bg, 68);
    lv_obj_set_x(ui_PERow4Bg, 10);
    lv_obj_set_y(ui_PERow4Bg, 299);
    lv_label_set_text(ui_PERow4Bg, "");
    lv_obj_set_style_text_color(ui_PERow4Bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERow4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERow4Bg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERow4Bg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERow4Bg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERow4Bg, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERow4Bg, lv_color_hex(0x182A40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERow4Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERow4Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PERowNr4 = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PERowNr4, 26);
    lv_obj_set_height(ui_PERowNr4, 52);
    lv_obj_set_x(ui_PERowNr4, 10);
    lv_obj_set_y(ui_PERowNr4, 307);
    lv_label_set_text(ui_PERowNr4, "4");
    lv_obj_set_style_text_color(ui_PERowNr4, lv_color_hex(0xAAB9D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PERowNr4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PERowNr4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PERowNr4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PERowNr4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PERowNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PERowNr4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PERowNr4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PERowNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PERowNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PERowNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PERowNr4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEPreset4M1 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset4M1, 118);
    lv_obj_set_height(ui_PEPreset4M1, 40);
    lv_obj_set_x(ui_PEPreset4M1, 40);
    lv_obj_set_y(ui_PEPreset4M1, 313);
    lv_textarea_set_placeholder_text(ui_PEPreset4M1, "0.0");

    ui_PEPreset4M2 = lv_textarea_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEPreset4M2, 118);
    lv_obj_set_height(ui_PEPreset4M2, 40);
    lv_obj_set_x(ui_PEPreset4M2, 162);
    lv_obj_set_y(ui_PEPreset4M2, 313);
    lv_textarea_set_placeholder_text(ui_PEPreset4M2, "0.0");

    ui_PESync4 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PESync4, 71);
    lv_obj_set_height(ui_PESync4, 40);
    lv_obj_set_x(ui_PESync4, 284);
    lv_obj_set_y(ui_PESync4, 313);
    lv_obj_add_flag(ui_PESync4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PESync4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PESync4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync4, lv_color_hex(0x1C375A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PESync4Text = lv_label_create(ui_PESync4);
    lv_obj_set_width(ui_PESync4Text, 71);
    lv_obj_set_height(ui_PESync4Text, 40);
    lv_obj_set_align(ui_PESync4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PESync4Text, "=");
    lv_obj_set_style_text_color(ui_PESync4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PESync4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PESync4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PESync4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PESync4Text, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PESync4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PESync4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PESync4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PESync4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PESync4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PESync4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PESync4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEHint = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEHint, 355);
    lv_obj_set_height(ui_PEHint, 20);
    lv_obj_set_x(ui_PEHint, 10);
    lv_obj_set_y(ui_PEHint, 372);
    lv_label_set_text(ui_PEHint, "Tik op een veld  |  '=' koppelt M1 en M2 aan elkaar");
    lv_obj_set_style_text_color(ui_PEHint, lv_color_hex(0x64789B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEHint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEHint, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEHint, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEHint, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEHint, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEHint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEHint, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEHint, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEHint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEHint, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEHint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardPresetedit = lv_keyboard_create(ui_ScreenPresetedit);
    lv_keyboard_set_mode(ui_KeyboardPresetedit, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardPresetedit, 415);
    lv_obj_set_height(ui_KeyboardPresetedit, 363);
    lv_obj_set_x(ui_KeyboardPresetedit, 375);
    lv_obj_set_y(ui_KeyboardPresetedit, 55);

    ui_PEBtnBarBg = lv_label_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEBtnBarBg, 800);
    lv_obj_set_height(ui_PEBtnBarBg, 60);
    lv_obj_set_x(ui_PEBtnBarBg, 0);
    lv_obj_set_y(ui_PEBtnBarBg, 420);
    lv_label_set_text(ui_PEBtnBarBg, "");
    lv_obj_set_style_text_color(ui_PEBtnBarBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEBtnBarBg, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEBtnBarBg, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEBtnBarBg, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtnBarBg, lv_color_hex(0x080F1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtnBarBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEBtnBarBg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn1 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEBtn1, 200);
    lv_obj_set_height(ui_PEBtn1, 57);
    lv_obj_set_x(ui_PEBtn1, 0);
    lv_obj_set_y(ui_PEBtn1, 421);
    lv_obj_add_flag(ui_PEBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PEBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PEBtn1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn1, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn1Text = lv_label_create(ui_PEBtn1);
    lv_obj_set_width(ui_PEBtn1Text, 200);
    lv_obj_set_height(ui_PEBtn1Text, 57);
    lv_obj_set_align(ui_PEBtn1Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PEBtn1Text, "Opslaan");
    lv_obj_set_style_text_color(ui_PEBtn1Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEBtn1Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEBtn1Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEBtn1Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEBtn1Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn1Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn1Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEBtn1Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn2 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEBtn2, 200);
    lv_obj_set_height(ui_PEBtn2, 57);
    lv_obj_set_x(ui_PEBtn2, 200);
    lv_obj_set_y(ui_PEBtn2, 421);
    lv_obj_add_flag(ui_PEBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PEBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PEBtn2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn2, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn2Text = lv_label_create(ui_PEBtn2);
    lv_obj_set_width(ui_PEBtn2Text, 200);
    lv_obj_set_height(ui_PEBtn2Text, 57);
    lv_obj_set_align(ui_PEBtn2Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PEBtn2Text, "Wissen");
    lv_obj_set_style_text_color(ui_PEBtn2Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEBtn2Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEBtn2Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEBtn2Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEBtn2Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn2Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn2Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEBtn2Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn3 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEBtn3, 200);
    lv_obj_set_height(ui_PEBtn3, 57);
    lv_obj_set_x(ui_PEBtn3, 400);
    lv_obj_set_y(ui_PEBtn3, 421);
    lv_obj_add_flag(ui_PEBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PEBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PEBtn3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn3, lv_color_hex(0x0064C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn3Text = lv_label_create(ui_PEBtn3);
    lv_obj_set_width(ui_PEBtn3Text, 200);
    lv_obj_set_height(ui_PEBtn3Text, 57);
    lv_obj_set_align(ui_PEBtn3Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PEBtn3Text, "Herstel");
    lv_obj_set_style_text_color(ui_PEBtn3Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEBtn3Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEBtn3Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEBtn3Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEBtn3Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn3Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn3Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEBtn3Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn4 = lv_btn_create(ui_ScreenPresetedit);
    lv_obj_set_width(ui_PEBtn4, 200);
    lv_obj_set_height(ui_PEBtn4, 57);
    lv_obj_set_x(ui_PEBtn4, 600);
    lv_obj_set_y(ui_PEBtn4, 421);
    lv_obj_add_flag(ui_PEBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PEBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PEBtn4, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn4, lv_color_hex(0x233755), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PEBtn4Text = lv_label_create(ui_PEBtn4);
    lv_obj_set_width(ui_PEBtn4Text, 200);
    lv_obj_set_height(ui_PEBtn4Text, 57);
    lv_obj_set_align(ui_PEBtn4Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PEBtn4Text, "Terug");
    lv_obj_set_style_text_color(ui_PEBtn4Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PEBtn4Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PEBtn4Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PEBtn4Text, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PEBtn4Text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PEBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PEBtn4Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PEBtn4Text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PEBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PEBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PEBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PEBtn4Text, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PEPreset1M1, ui_event_PEPreset1M1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset1M2, ui_event_PEPreset1M2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PESync1, ui_event_PESync1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset2M1, ui_event_PEPreset2M1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset2M2, ui_event_PEPreset2M2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PESync2, ui_event_PESync2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset3M1, ui_event_PEPreset3M1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset3M2, ui_event_PEPreset3M2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PESync3, ui_event_PESync3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset4M1, ui_event_PEPreset4M1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEPreset4M2, ui_event_PEPreset4M2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PESync4, ui_event_PESync4, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardPresetedit, ui_PEPreset1M1);
    lv_obj_add_event_cb(ui_PEBtn1, ui_event_PEBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEBtn2, ui_event_PEBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEBtn3, ui_event_PEBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PEBtn4, ui_event_PEBtn4, LV_EVENT_ALL, NULL);

}

void ui_ScreenPresetedit_screen_destroy(void)
{
    if(ui_ScreenPresetedit) lv_obj_del(ui_ScreenPresetedit);

    // NULL screen variables
    ui_ScreenPresetedit = NULL;
    ui_PEHeaderBg = NULL;
    ui_PIMMLogo_PE = NULL;
    ui_TitelPE = NULL;
    ui_PELeftBg = NULL;
    ui_PEColHdrBg = NULL;
    ui_PEColHdrNr = NULL;
    ui_PEColHdrM1 = NULL;
    ui_PEColHdrM2 = NULL;
    ui_PEColHdrSync = NULL;
    ui_PERow1Bg = NULL;
    ui_PERowNr1 = NULL;
    ui_PEPreset1M1 = NULL;
    ui_PEPreset1M2 = NULL;
    ui_PESync1 = NULL;
    ui_PESync1Text = NULL;
    ui_PERow2Bg = NULL;
    ui_PERowNr2 = NULL;
    ui_PEPreset2M1 = NULL;
    ui_PEPreset2M2 = NULL;
    ui_PESync2 = NULL;
    ui_PESync2Text = NULL;
    ui_PERow3Bg = NULL;
    ui_PERowNr3 = NULL;
    ui_PEPreset3M1 = NULL;
    ui_PEPreset3M2 = NULL;
    ui_PESync3 = NULL;
    ui_PESync3Text = NULL;
    ui_PERow4Bg = NULL;
    ui_PERowNr4 = NULL;
    ui_PEPreset4M1 = NULL;
    ui_PEPreset4M2 = NULL;
    ui_PESync4 = NULL;
    ui_PESync4Text = NULL;
    ui_PEHint = NULL;
    ui_KeyboardPresetedit = NULL;
    ui_PEBtnBarBg = NULL;
    ui_PEBtn1 = NULL;
    ui_PEBtn1Text = NULL;
    ui_PEBtn2 = NULL;
    ui_PEBtn2Text = NULL;
    ui_PEBtn3 = NULL;
    ui_PEBtn3Text = NULL;
    ui_PEBtn4 = NULL;
    ui_PEBtn4Text = NULL;

}
