// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENHOME_H
#define UI_SCREENHOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenHome
extern void ui_ScreenHome_screen_init(void);
extern void ui_ScreenHome_screen_destroy(void);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_HomeHeaderBg;
extern lv_obj_t * ui_PIMMLogo1;
extern lv_obj_t * ui_TitelHome;
extern lv_obj_t * ui_PanelMod1Bg;
extern lv_obj_t * ui_LblMod1Title;
extern lv_obj_t * ui_LblMod1Height;
extern lv_obj_t * ui_LblMod1Sub;
extern lv_obj_t * ui_LblMod1Tgt;
extern lv_obj_t * ui_PanelGap;
extern lv_obj_t * ui_PanelMod2Bg;
extern lv_obj_t * ui_LblMod2Title;
extern lv_obj_t * ui_LblMod2Height;
extern lv_obj_t * ui_LblMod2Sub;
extern lv_obj_t * ui_LblMod2Tgt;
extern lv_obj_t * ui_SelRowBg;
extern lv_obj_t * ui_LblEnkoder;
extern void ui_event_BtnSelMod1(lv_event_t * e);
extern lv_obj_t * ui_BtnSelMod1;
extern lv_obj_t * ui_BtnSelMod1Text;
extern void ui_event_BtnSelBoth(lv_event_t * e);
extern lv_obj_t * ui_BtnSelBoth;
extern lv_obj_t * ui_BtnSelBothText;
extern void ui_event_BtnSelMod2(lv_event_t * e);
extern lv_obj_t * ui_BtnSelMod2;
extern lv_obj_t * ui_BtnSelMod2Text;
extern lv_obj_t * ui_StatusBg;
extern lv_obj_t * ui_LblSyncStatus;
extern lv_obj_t * ui_LblProgInfo;
extern lv_obj_t * ui_HomeBtnBarBg;
extern void ui_event_HomeBtn1(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn1;
extern lv_obj_t * ui_HomeBtn1Text;
extern void ui_event_HomeBtn2(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn2;
extern lv_obj_t * ui_HomeBtn2Text;
extern void ui_event_HomeBtn3(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn3;
extern lv_obj_t * ui_HomeBtn3Text;
extern void ui_event_HomeBtn4(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn4;
extern lv_obj_t * ui_HomeBtn4Text;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

