// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SelectModule1(lv_event_t * e);
void ToggleSync(lv_event_t * e);
void SelectModule2(lv_event_t * e);
void ChangeStap(lv_event_t * e);
void Kalibreer(lv_event_t * e);
void SelectPreset1(lv_event_t * e);
void SelectPreset2(lv_event_t * e);
void SelectPreset3(lv_event_t * e);
void SelectPreset(lv_event_t * e);
void PresetToepassen(lv_event_t * e);
void ResetPreset(lv_event_t * e);
void SavePreset(lv_event_t * e);
void SelectNextFunction(lv_event_t * e);
void SelectPreviousFunction(lv_event_t * e);
void ChangeColorButtonToonAndVerberg(lv_event_t * e);
void SwitchEncoderknop(lv_event_t * e);
void ResetAlarm(lv_event_t * e);
void Kalibratie(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
