// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void SelectModule1(lv_event_t * e)
{
	// Your code here
}

void ToggleSync(lv_event_t * e)
{
	// Your code here
}

void SelectModule2(lv_event_t * e)
{
	// Your code here
}

void ChangeStap(lv_event_t * e)
{
	// Your code here
}

void Kalibreer(lv_event_t * e)
{
	// Your code here
}

void SelectPreset1(lv_event_t * e)
{
	// Your code here
}

void SelectPreset2(lv_event_t * e)
{
	// Your code here
}

void SelectPreset3(lv_event_t * e)
{
	// Your code here
}

void SelectPreset(lv_event_t * e)
{
	// Your code here
}

void PresetToepassen(lv_event_t * e)
{
	// Your code here
}

void ResetPreset(lv_event_t * e)
{
	// Your code here
}

void SavePreset(lv_event_t * e)
{
	// Your code here
}

void SelectNextFunction(lv_event_t * e)
{
	// Your code here
}

void SelectPreviousFunction(lv_event_t * e)
{
	// Your code here
}

void ChangeColorButtonToonAndVerberg(lv_event_t * e)
{
	// Your code here
}

void SwitchEncoderknop(lv_event_t * e)
{
	// Your code here
}

void ResetAlarm(lv_event_t * e)
{
	// Your code here
}

void Kalibratie(lv_event_t * e)
{
	// Your code here
}
