// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// Functions defined in main.cpp (extern "C").
extern void HandlePresetSelect(int preset_number);
extern void ApplyPreset(void);
extern void SaveCurrentEditPreset(void);
extern void ResetCurrentEditPreset(void);
extern void GoToNextEditPreset(void);
extern void GoToPreviousEditPreset(void);
extern void PreparePresetEditScreen(void);
extern void CalibrateAllMotors(void);
extern void HandleAlarmReset(void);
extern void HandleToonLink(void);
extern void HandleVerbergLink(void);
extern void HandleWisselenVanModule(void);
extern void HandleAanpassenVanDeStap(void);
extern void HandleEncoderKnopSwitch(void);

void SelectModule1(lv_event_t * e)
{
	// Your code here
	SetSelectedMotorController(0); // Select MotorController1 from the Home screen button.
}

void ToggleSync(lv_event_t * e)
{
	// Your code here
	ToggleSyncMode(); // Switch synchronized control on or off from the Home screen button.
}

void SelectModule2(lv_event_t * e)
{
	// Your code here
	SetSelectedMotorController(1); // Select MotorController2 from the Home screen button.
}

void ChangeStap(lv_event_t * e)
{
	// Your code here
	ToggleStepSizeMode(); // Switch the encoder step size when the Step button is pressed.
}

void Kalibreer(lv_event_t * e)
{
	SendCalibrateCommand(); // Send the calibration command to the currently selected motor controller.
}

void SelectPreset1(lv_event_t * e)
{
	HandlePresetSelect(1);
}

void SelectPreset2(lv_event_t * e)
{
	HandlePresetSelect(2);
}

void SelectPreset3(lv_event_t * e)
{
	HandlePresetSelect(3);
}

void SelectPreset(lv_event_t * e)
{
	HandlePresetSelect(4);
}

void PresetToepassen(lv_event_t * e)
{
	ApplyPreset();
}

void ResetPreset(lv_event_t * e)
{
	ResetCurrentEditPreset();
}

void SavePreset(lv_event_t * e)
{
	SaveCurrentEditPreset();
}

void SelectNextFunction(lv_event_t * e)
{
	GoToNextEditPreset();
}

void SelectPreviousFunction(lv_event_t * e)
{
	GoToPreviousEditPreset();
}

void ChangeColorButtonToonAndVerberg(lv_event_t * e)
{
	// Your code here
}

void SwitchEncoderknop(lv_event_t * e)
{
	HandleEncoderKnopSwitch();
}

void ResetAlarm(lv_event_t * e)
{
	HandleAlarmReset();
}

void Kalibratie(lv_event_t * e)
{
	CalibrateAllMotors();
}

void ChangeColorButtonToon(lv_event_t * e)
{
	HandleToonLink();
}

void ChangeColorButtonVerberg(lv_event_t * e)
{
	HandleVerbergLink();
}

void SwitchEncoderknopWisselenModule(lv_event_t * e)
{
	HandleWisselenVanModule();
}

void SwitchEncoderknopAanspassenStap(lv_event_t * e)
{
	HandleAanpassenVanDeStap();
}
