// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenPresetsSelect = NULL;
lv_obj_t * ui_HeaderPresetsBackground = NULL;
lv_obj_t * ui_HeaderPresets = NULL;
lv_obj_t * ui_Preset1Background = NULL;
lv_obj_t * ui_Preset1 = NULL;
lv_obj_t * ui_CosmeticLine1 = NULL;
lv_obj_t * ui_NamePreset1 = NULL;
lv_obj_t * ui_Preset1HoogteM1 = NULL;
lv_obj_t * ui_Preset1HoogteM2 = NULL;
lv_obj_t * ui_ButtonSelectPreset1 = NULL;
lv_obj_t * ui_TextButtonSelectPreset1 = NULL;
lv_obj_t * ui_Preset2Background = NULL;
lv_obj_t * ui_Preset2 = NULL;
lv_obj_t * ui_CosmeticLine2 = NULL;
lv_obj_t * ui_NamePreset2 = NULL;
lv_obj_t * ui_Preset2HoogteM1 = NULL;
lv_obj_t * ui_Preset2HoogteM2 = NULL;
lv_obj_t * ui_ButtonSelectPreset2 = NULL;
lv_obj_t * ui_TextButtonSelectPreset2 = NULL;
lv_obj_t * ui_Preset2Background1 = NULL;
lv_obj_t * ui_Preset3 = NULL;
lv_obj_t * ui_CosmeticLine3 = NULL;
lv_obj_t * ui_NamePreset3 = NULL;
lv_obj_t * ui_Preset3HoogteM1 = NULL;
lv_obj_t * ui_Preset3HoogteM2 = NULL;
lv_obj_t * ui_ButtonSelectPreset3 = NULL;
lv_obj_t * ui_TextButtonSelectPreset3 = NULL;
lv_obj_t * ui_Preset2Background2 = NULL;
lv_obj_t * ui_Preset4 = NULL;
lv_obj_t * ui_CosmeticLine4 = NULL;
lv_obj_t * ui_NamePreset4 = NULL;
lv_obj_t * ui_Preset4HoogteM1 = NULL;
lv_obj_t * ui_Preset4HoogteM2 = NULL;
lv_obj_t * ui_ButtonSelectPreset4 = NULL;
lv_obj_t * ui_TextButtonSelectPreset4 = NULL;
lv_obj_t * ui_ButtonToepassen = NULL;
lv_obj_t * ui_TextButtonToepassen = NULL;
lv_obj_t * ui_ButtonGoToBewerken = NULL;
lv_obj_t * ui_TextButtonGoToBewerken = NULL;
lv_obj_t * ui_ButtonEmpty = NULL;
lv_obj_t * ui_TextButtonEmpty = NULL;
lv_obj_t * ui_ButtonGoToHome = NULL;
lv_obj_t * ui_TextButtonGoToHome = NULL;
// event funtions
void ui_event_ButtonSelectPreset1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectPreset1(e);
    }
}

void ui_event_ButtonSelectPreset2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectPreset2(e);
    }
}

void ui_event_ButtonSelectPreset3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectPreset3(e);
    }
}

void ui_event_ButtonSelectPreset4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectPreset(e);
    }
}

void ui_event_ButtonToepassen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PresetToepassen(e);
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_ButtonGoToBewerken(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreparePresetEditScreen(); // MANUAL ADDITION: must be re-added after every SquareLine export.
        _ui_screen_change(&ui_ScreenPresetEdit, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPresetEdit_screen_init);
    }
}

void ui_event_ButtonGoToHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

// build funtions

void ui_ScreenPresetsSelect_screen_init(void)
{
    ui_ScreenPresetsSelect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPresetsSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderPresetsBackground = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_HeaderPresetsBackground, 800);
    lv_obj_set_height(ui_HeaderPresetsBackground, 50);
    lv_obj_clear_flag(ui_HeaderPresetsBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_HeaderPresetsBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaderPresetsBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_HeaderPresetsBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_HeaderPresets = lv_label_create(ui_HeaderPresetsBackground);
    lv_obj_set_width(ui_HeaderPresets, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_HeaderPresets, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_HeaderPresets, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeaderPresets, "Presets");
    lv_obj_set_style_text_color(ui_HeaderPresets, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderPresets, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderPresets, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset1Background = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_Preset1Background, 780);
    lv_obj_set_height(ui_Preset1Background, 60);
    lv_obj_set_x(ui_Preset1Background, 5);
    lv_obj_set_y(ui_Preset1Background, 70);
    lv_obj_add_flag(ui_Preset1Background, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Preset1Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Preset1Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_Preset1Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset1 = lv_label_create(ui_Preset1Background);
    lv_obj_set_width(ui_Preset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset1, 1);
    lv_obj_set_y(ui_Preset1, 5);
    lv_label_set_text(ui_Preset1, "1");
    ui_object_set_themeable_style_property(ui_Preset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_Preset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_Preset1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CosmeticLine1 = lv_btn_create(ui_Preset1Background);
    lv_obj_set_width(ui_CosmeticLine1, 5);
    lv_obj_set_height(ui_CosmeticLine1, 50);
    lv_obj_set_x(ui_CosmeticLine1, 42);
    lv_obj_set_y(ui_CosmeticLine1, -6);
    lv_obj_clear_flag(ui_CosmeticLine1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_CosmeticLine1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CosmeticLine1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_CosmeticLine1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Grey);

    ui_NamePreset1 = lv_label_create(ui_Preset1Background);
    lv_obj_set_width(ui_NamePreset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NamePreset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NamePreset1, 55);
    lv_obj_set_y(ui_NamePreset1, -2);
    lv_label_set_text(ui_NamePreset1, "Placeholder_NamePreset1");
    lv_obj_set_style_text_color(ui_NamePreset1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NamePreset1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset1HoogteM1 = lv_label_create(ui_Preset1Background);
    lv_obj_set_width(ui_Preset1HoogteM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset1HoogteM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset1HoogteM1, 55);
    lv_obj_set_y(ui_Preset1HoogteM1, 20);
    lv_label_set_text(ui_Preset1HoogteM1, "Placeholder_Preset1HoogteM1");

    ui_Preset1HoogteM2 = lv_label_create(ui_Preset1Background);
    lv_obj_set_width(ui_Preset1HoogteM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset1HoogteM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset1HoogteM2, 448);
    lv_obj_set_y(ui_Preset1HoogteM2, 20);
    lv_label_set_text(ui_Preset1HoogteM2, "Placeholder_Preset1HoogteM2");

    ui_ButtonSelectPreset1 = lv_btn_create(ui_Preset1Background);
    lv_obj_set_width(ui_ButtonSelectPreset1, 150);
    lv_obj_set_height(ui_ButtonSelectPreset1, 50);
    lv_obj_set_x(ui_ButtonSelectPreset1, 595);
    lv_obj_set_y(ui_ButtonSelectPreset1, -6);
    lv_obj_add_flag(ui_ButtonSelectPreset1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectPreset1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectPreset1 = lv_label_create(ui_ButtonSelectPreset1);
    lv_obj_set_width(ui_TextButtonSelectPreset1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonSelectPreset1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonSelectPreset1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectPreset1, "Selecteer");
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset2Background = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_Preset2Background, 780);
    lv_obj_set_height(ui_Preset2Background, 60);
    lv_obj_set_x(ui_Preset2Background, 5);
    lv_obj_set_y(ui_Preset2Background, 150);
    lv_obj_add_flag(ui_Preset2Background, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Preset2Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Preset2Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_Preset2Background, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset2 = lv_label_create(ui_Preset2Background);
    lv_obj_set_width(ui_Preset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset2, 1);
    lv_obj_set_y(ui_Preset2, 5);
    lv_label_set_text(ui_Preset2, "2");
    ui_object_set_themeable_style_property(ui_Preset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_Preset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_Preset2, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CosmeticLine2 = lv_btn_create(ui_Preset2Background);
    lv_obj_set_width(ui_CosmeticLine2, 5);
    lv_obj_set_height(ui_CosmeticLine2, 50);
    lv_obj_set_x(ui_CosmeticLine2, 42);
    lv_obj_set_y(ui_CosmeticLine2, -6);
    lv_obj_clear_flag(ui_CosmeticLine2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_CosmeticLine2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CosmeticLine2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_CosmeticLine2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Grey);

    ui_NamePreset2 = lv_label_create(ui_Preset2Background);
    lv_obj_set_width(ui_NamePreset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NamePreset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NamePreset2, 55);
    lv_obj_set_y(ui_NamePreset2, -2);
    lv_label_set_text(ui_NamePreset2, "Placeholder_NamePreset2");
    lv_obj_set_style_text_color(ui_NamePreset2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NamePreset2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset2HoogteM1 = lv_label_create(ui_Preset2Background);
    lv_obj_set_width(ui_Preset2HoogteM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset2HoogteM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset2HoogteM1, 55);
    lv_obj_set_y(ui_Preset2HoogteM1, 20);
    lv_label_set_text(ui_Preset2HoogteM1, "Placeholder_Preset2HoogteM1");

    ui_Preset2HoogteM2 = lv_label_create(ui_Preset2Background);
    lv_obj_set_width(ui_Preset2HoogteM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset2HoogteM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset2HoogteM2, 448);
    lv_obj_set_y(ui_Preset2HoogteM2, 20);
    lv_label_set_text(ui_Preset2HoogteM2, "Placeholder_Preset2HoogteM2");

    ui_ButtonSelectPreset2 = lv_btn_create(ui_Preset2Background);
    lv_obj_set_width(ui_ButtonSelectPreset2, 150);
    lv_obj_set_height(ui_ButtonSelectPreset2, 50);
    lv_obj_set_x(ui_ButtonSelectPreset2, 595);
    lv_obj_set_y(ui_ButtonSelectPreset2, -6);
    lv_obj_add_flag(ui_ButtonSelectPreset2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectPreset2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectPreset2 = lv_label_create(ui_ButtonSelectPreset2);
    lv_obj_set_width(ui_TextButtonSelectPreset2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonSelectPreset2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonSelectPreset2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectPreset2, "Selecteer");
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset2Background1 = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_Preset2Background1, 780);
    lv_obj_set_height(ui_Preset2Background1, 60);
    lv_obj_set_x(ui_Preset2Background1, 5);
    lv_obj_set_y(ui_Preset2Background1, 230);
    lv_obj_add_flag(ui_Preset2Background1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Preset2Background1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Preset2Background1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_Preset2Background1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset3 = lv_label_create(ui_Preset2Background1);
    lv_obj_set_width(ui_Preset3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset3, 1);
    lv_obj_set_y(ui_Preset3, 5);
    lv_label_set_text(ui_Preset3, "3");
    ui_object_set_themeable_style_property(ui_Preset3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_Preset3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_Preset3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CosmeticLine3 = lv_btn_create(ui_Preset2Background1);
    lv_obj_set_width(ui_CosmeticLine3, 5);
    lv_obj_set_height(ui_CosmeticLine3, 50);
    lv_obj_set_x(ui_CosmeticLine3, 42);
    lv_obj_set_y(ui_CosmeticLine3, -6);
    lv_obj_clear_flag(ui_CosmeticLine3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_CosmeticLine3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CosmeticLine3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_CosmeticLine3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Grey);

    ui_NamePreset3 = lv_label_create(ui_Preset2Background1);
    lv_obj_set_width(ui_NamePreset3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NamePreset3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NamePreset3, 55);
    lv_obj_set_y(ui_NamePreset3, -2);
    lv_label_set_text(ui_NamePreset3, "Placeholder_NamePreset2");
    lv_obj_set_style_text_color(ui_NamePreset3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NamePreset3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset3HoogteM1 = lv_label_create(ui_Preset2Background1);
    lv_obj_set_width(ui_Preset3HoogteM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset3HoogteM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset3HoogteM1, 55);
    lv_obj_set_y(ui_Preset3HoogteM1, 20);
    lv_label_set_text(ui_Preset3HoogteM1, "Placeholder_Preset3HoogteM1");

    ui_Preset3HoogteM2 = lv_label_create(ui_Preset2Background1);
    lv_obj_set_width(ui_Preset3HoogteM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset3HoogteM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset3HoogteM2, 448);
    lv_obj_set_y(ui_Preset3HoogteM2, 20);
    lv_label_set_text(ui_Preset3HoogteM2, "Placeholder_Preset3HoogteM2");

    ui_ButtonSelectPreset3 = lv_btn_create(ui_Preset2Background1);
    lv_obj_set_width(ui_ButtonSelectPreset3, 150);
    lv_obj_set_height(ui_ButtonSelectPreset3, 50);
    lv_obj_set_x(ui_ButtonSelectPreset3, 595);
    lv_obj_set_y(ui_ButtonSelectPreset3, -6);
    lv_obj_add_flag(ui_ButtonSelectPreset3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectPreset3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectPreset3 = lv_label_create(ui_ButtonSelectPreset3);
    lv_obj_set_width(ui_TextButtonSelectPreset3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonSelectPreset3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonSelectPreset3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectPreset3, "Selecteer");
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset2Background2 = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_Preset2Background2, 780);
    lv_obj_set_height(ui_Preset2Background2, 60);
    lv_obj_set_x(ui_Preset2Background2, 5);
    lv_obj_set_y(ui_Preset2Background2, 310);
    lv_obj_add_flag(ui_Preset2Background2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Preset2Background2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Preset2Background2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_Preset2Background2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Preset4 = lv_label_create(ui_Preset2Background2);
    lv_obj_set_width(ui_Preset4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset4, 1);
    lv_obj_set_y(ui_Preset4, 5);
    lv_label_set_text(ui_Preset4, "4");
    ui_object_set_themeable_style_property(ui_Preset4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_Preset4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_Preset4, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CosmeticLine4 = lv_btn_create(ui_Preset2Background2);
    lv_obj_set_width(ui_CosmeticLine4, 5);
    lv_obj_set_height(ui_CosmeticLine4, 50);
    lv_obj_set_x(ui_CosmeticLine4, 42);
    lv_obj_set_y(ui_CosmeticLine4, -6);
    lv_obj_clear_flag(ui_CosmeticLine4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_CosmeticLine4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CosmeticLine4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_CosmeticLine4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Grey);

    ui_NamePreset4 = lv_label_create(ui_Preset2Background2);
    lv_obj_set_width(ui_NamePreset4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NamePreset4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NamePreset4, 55);
    lv_obj_set_y(ui_NamePreset4, -2);
    lv_label_set_text(ui_NamePreset4, "Placeholder_NamePreset4");
    lv_obj_set_style_text_color(ui_NamePreset4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NamePreset4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preset4HoogteM1 = lv_label_create(ui_Preset2Background2);
    lv_obj_set_width(ui_Preset4HoogteM1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset4HoogteM1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset4HoogteM1, 55);
    lv_obj_set_y(ui_Preset4HoogteM1, 20);
    lv_label_set_text(ui_Preset4HoogteM1, "Placeholder_Preset1HoogteM1");

    ui_Preset4HoogteM2 = lv_label_create(ui_Preset2Background2);
    lv_obj_set_width(ui_Preset4HoogteM2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preset4HoogteM2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preset4HoogteM2, 448);
    lv_obj_set_y(ui_Preset4HoogteM2, 20);
    lv_label_set_text(ui_Preset4HoogteM2, "Placeholder_Preset1HoogteM2");

    ui_ButtonSelectPreset4 = lv_btn_create(ui_Preset2Background2);
    lv_obj_set_width(ui_ButtonSelectPreset4, 150);
    lv_obj_set_height(ui_ButtonSelectPreset4, 50);
    lv_obj_set_x(ui_ButtonSelectPreset4, 595);
    lv_obj_set_y(ui_ButtonSelectPreset4, -6);
    lv_obj_add_flag(ui_ButtonSelectPreset4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectPreset4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectPreset4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectPreset4 = lv_label_create(ui_ButtonSelectPreset4);
    lv_obj_set_width(ui_TextButtonSelectPreset4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonSelectPreset4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonSelectPreset4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectPreset4, "Selecteer");
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectPreset4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_ButtonToepassen = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_ButtonToepassen, 200);
    lv_obj_set_height(ui_ButtonToepassen, 57);
    lv_obj_set_x(ui_ButtonToepassen, 0);
    lv_obj_set_y(ui_ButtonToepassen, 423);
    lv_obj_add_flag(ui_ButtonToepassen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonToepassen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonToepassen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonToepassen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonToepassen = lv_label_create(ui_ButtonToepassen);
    lv_obj_set_width(ui_TextButtonToepassen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonToepassen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonToepassen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonToepassen, "Toepassen");
    ui_object_set_themeable_style_property(ui_TextButtonToepassen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_TextButtonToepassen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_TextButtonToepassen, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToBewerken = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_ButtonGoToBewerken, 200);
    lv_obj_set_height(ui_ButtonGoToBewerken, 57);
    lv_obj_set_x(ui_ButtonGoToBewerken, 200);
    lv_obj_set_y(ui_ButtonGoToBewerken, 423);
    lv_obj_add_flag(ui_ButtonGoToBewerken, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToBewerken, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonGoToBewerken, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonGoToBewerken, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonGoToBewerken = lv_label_create(ui_ButtonGoToBewerken);
    lv_obj_set_width(ui_TextButtonGoToBewerken, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonGoToBewerken, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonGoToBewerken, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonGoToBewerken, "Bewerken");
    ui_object_set_themeable_style_property(ui_TextButtonGoToBewerken, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_TextButtonGoToBewerken, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_TextButtonGoToBewerken, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEmpty = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_ButtonEmpty, 200);
    lv_obj_set_height(ui_ButtonEmpty, 57);
    lv_obj_set_x(ui_ButtonEmpty, 400);
    lv_obj_set_y(ui_ButtonEmpty, 423);
    lv_obj_add_flag(ui_ButtonEmpty, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEmpty, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonEmpty, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonEmpty, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonEmpty = lv_label_create(ui_ButtonEmpty);
    lv_obj_set_width(ui_TextButtonEmpty, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonEmpty, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonEmpty, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonEmpty, "");
    ui_object_set_themeable_style_property(ui_TextButtonEmpty, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonEmpty, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonEmpty, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToHome = lv_btn_create(ui_ScreenPresetsSelect);
    lv_obj_set_width(ui_ButtonGoToHome, 200);
    lv_obj_set_height(ui_ButtonGoToHome, 57);
    lv_obj_set_x(ui_ButtonGoToHome, 600);
    lv_obj_set_y(ui_ButtonGoToHome, 423);
    lv_obj_add_flag(ui_ButtonGoToHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonGoToHome, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_ButtonGoToHome, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_TextButtonGoToHome = lv_label_create(ui_ButtonGoToHome);
    lv_obj_set_width(ui_TextButtonGoToHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonGoToHome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonGoToHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonGoToHome, "Terug");
    lv_obj_set_style_text_color(ui_TextButtonGoToHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextButtonGoToHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonGoToHome, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonSelectPreset1, ui_event_ButtonSelectPreset1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSelectPreset2, ui_event_ButtonSelectPreset2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSelectPreset3, ui_event_ButtonSelectPreset3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSelectPreset4, ui_event_ButtonSelectPreset4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonToepassen, ui_event_ButtonToepassen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToBewerken, ui_event_ButtonGoToBewerken, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToHome, ui_event_ButtonGoToHome, LV_EVENT_ALL, NULL);

}

void ui_ScreenPresetsSelect_screen_destroy(void)
{
    if(ui_ScreenPresetsSelect) lv_obj_del(ui_ScreenPresetsSelect);

    // NULL screen variables
    ui_ScreenPresetsSelect = NULL;
    ui_HeaderPresetsBackground = NULL;
    ui_HeaderPresets = NULL;
    ui_Preset1Background = NULL;
    ui_Preset1 = NULL;
    ui_CosmeticLine1 = NULL;
    ui_NamePreset1 = NULL;
    ui_Preset1HoogteM1 = NULL;
    ui_Preset1HoogteM2 = NULL;
    ui_ButtonSelectPreset1 = NULL;
    ui_TextButtonSelectPreset1 = NULL;
    ui_Preset2Background = NULL;
    ui_Preset2 = NULL;
    ui_CosmeticLine2 = NULL;
    ui_NamePreset2 = NULL;
    ui_Preset2HoogteM1 = NULL;
    ui_Preset2HoogteM2 = NULL;
    ui_ButtonSelectPreset2 = NULL;
    ui_TextButtonSelectPreset2 = NULL;
    ui_Preset2Background1 = NULL;
    ui_Preset3 = NULL;
    ui_CosmeticLine3 = NULL;
    ui_NamePreset3 = NULL;
    ui_Preset3HoogteM1 = NULL;
    ui_Preset3HoogteM2 = NULL;
    ui_ButtonSelectPreset3 = NULL;
    ui_TextButtonSelectPreset3 = NULL;
    ui_Preset2Background2 = NULL;
    ui_Preset4 = NULL;
    ui_CosmeticLine4 = NULL;
    ui_NamePreset4 = NULL;
    ui_Preset4HoogteM1 = NULL;
    ui_Preset4HoogteM2 = NULL;
    ui_ButtonSelectPreset4 = NULL;
    ui_TextButtonSelectPreset4 = NULL;
    ui_ButtonToepassen = NULL;
    ui_TextButtonToepassen = NULL;
    ui_ButtonGoToBewerken = NULL;
    ui_TextButtonGoToBewerken = NULL;
    ui_ButtonEmpty = NULL;
    ui_TextButtonEmpty = NULL;
    ui_ButtonGoToHome = NULL;
    ui_TextButtonGoToHome = NULL;

}
