// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_HeaderSettingsBackground;
extern lv_obj_t * ui_HeaderSettings;
extern lv_obj_t * ui_SettingLinkNaarProjectBackground;
extern lv_obj_t * ui_LinkNaarProject;
extern void ui_event_ButtonToonLink(lv_event_t * e);
extern lv_obj_t * ui_ButtonToonLink;
extern lv_obj_t * ui_TextButtonToonLink;
extern void ui_event_ButtonVerbergLink(lv_event_t * e);
extern lv_obj_t * ui_ButtonVerbergLink;
extern lv_obj_t * ui_TextButtonVerbergLink;
extern lv_obj_t * ui_SettingEncoderknopBackground;
extern lv_obj_t * ui_EncoderknopRegelt;
extern void ui_event_ButtonWisselenVanModule(lv_event_t * e);
extern lv_obj_t * ui_ButtonWisselenVanModule;
extern lv_obj_t * ui_TextButtonWisselenVanModule;
extern void ui_event_ButtonAanpassenVanDeStap(lv_event_t * e);
extern lv_obj_t * ui_ButtonAanpassenVanDeStap;
extern lv_obj_t * ui_TextButtonAanpassenVanDeStap;
extern void ui_event_ButtonResetAlarm(lv_event_t * e);
extern lv_obj_t * ui_ButtonResetAlarm;
extern lv_obj_t * ui_TextButtonResetAlarm;
extern void ui_event_ButtonEncoderknop(lv_event_t * e);
extern lv_obj_t * ui_ButtonEncoderknop;
extern lv_obj_t * ui_TextButtonEncoderknop;
extern void ui_event_ButtonKalibreerBeide2(lv_event_t * e);
extern lv_obj_t * ui_ButtonKalibreerBeide2;
extern lv_obj_t * ui_TextButtonKalibreer2;
extern void ui_event_ButtonGoToHome2(lv_event_t * e);
extern lv_obj_t * ui_ButtonGoToHome2;
extern lv_obj_t * ui_TextButtonGoToHome2;
extern void ui_event_ButtonResetAlarm2(lv_event_t * e);
extern lv_obj_t * ui_ButtonResetAlarm2;
extern lv_obj_t * ui_TextButtonResetAlarm2;
extern lv_obj_t * ui_HeaderFoutcode;
extern lv_obj_t * ui_Foutcodes;
extern void ui_event_ButtonKalibreerBeide(lv_event_t * e);
extern lv_obj_t * ui_ButtonKalibreerBeide;
extern lv_obj_t * ui_TextButtonKalibreer3;
extern lv_obj_t * ui_TextButtonKalibreerExtra;
extern lv_obj_t * ui_LinkNaarProject2;
extern lv_obj_t * ui_TextLinkNaarProject;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

