// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenHome = NULL;
lv_obj_t * ui_HeaderHomeBackground = NULL;
lv_obj_t * ui_HeaderHome = NULL;
lv_obj_t * ui_InfoModule1 = NULL;
lv_obj_t * ui_HoogteModule1 = NULL;
lv_obj_t * ui_HeaderModule1 = NULL;
lv_obj_t * ui_Module1Connected = NULL;
lv_obj_t * ui_DoelModule1 = NULL;
lv_obj_t * ui_AlarmModule1 = NULL;
lv_obj_t * ui_TextActueleHoogteModule1 = NULL;
lv_obj_t * ui_InfoModule2 = NULL;
lv_obj_t * ui_HeaderModule2 = NULL;
lv_obj_t * ui_Module2Connected = NULL;
lv_obj_t * ui_HoogteModule2 = NULL;
lv_obj_t * ui_DoelModule2 = NULL;
lv_obj_t * ui_AlarmModule2 = NULL;
lv_obj_t * ui_TextActueleHoogteModule2 = NULL;
lv_obj_t * ui_LowerBackground = NULL;
lv_obj_t * ui_ButtonSelectModule1 = NULL;
lv_obj_t * ui_TextButtonSelectModule1 = NULL;
lv_obj_t * ui_ButtonSelectSync = NULL;
lv_obj_t * ui_TextButtonSelectSync = NULL;
lv_obj_t * ui_ButtonSelectModule2 = NULL;
lv_obj_t * ui_TextButtonSelectModule2 = NULL;
lv_obj_t * ui_ButtonGoToPresets = NULL;
lv_obj_t * ui_TextButtonGoToPresets = NULL;
lv_obj_t * ui_ButtonGoToSettings = NULL;
lv_obj_t * ui_TextButtonGoToPresets1 = NULL;
lv_obj_t * ui_ButtonStap = NULL;
lv_obj_t * ui_TextButtonStap = NULL;
lv_obj_t * ui_ButtonKalibreer = NULL;
lv_obj_t * ui_TextButtonKalibreer = NULL;
// event funtions
void ui_event_ButtonSelectModule1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectModule1(e);
        (e);
    }
}

void ui_event_ButtonSelectSync(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ToggleSync(e);
        (e);
    }
}

void ui_event_ButtonSelectModule2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SelectModule2(e);
        (e);
    }
}

void ui_event_ButtonGoToPresets(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenPresetsSelect, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenPresetsSelect_screen_init);
    }
}

void ui_event_ButtonGoToSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_ButtonStap(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ChangeStap(e);
    }
}

void ui_event_ButtonKalibreer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Kalibreer(e);
    }
}

// build funtions

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderHomeBackground = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_HeaderHomeBackground, 800);
    lv_obj_set_height(ui_HeaderHomeBackground, 50);
    lv_obj_clear_flag(ui_HeaderHomeBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_HeaderHomeBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaderHomeBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_HeaderHomeBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_HeaderHome = lv_label_create(ui_HeaderHomeBackground);
    lv_obj_set_width(ui_HeaderHome, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_HeaderHome, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_HeaderHome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeaderHome, "Home");
    lv_obj_set_style_text_color(ui_HeaderHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderHome, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoModule1 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_InfoModule1, 370);
    lv_obj_set_height(ui_InfoModule1, 220);
    lv_obj_set_x(ui_InfoModule1, 15);
    lv_obj_set_y(ui_InfoModule1, 55);
    lv_obj_add_flag(ui_InfoModule1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InfoModule1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_InfoModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_InfoModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);
    ui_object_set_themeable_style_property(ui_InfoModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_InfoModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_InfoModule1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HoogteModule1 = lv_label_create(ui_InfoModule1);
    lv_obj_set_width(ui_HoogteModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HoogteModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HoogteModule1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_HoogteModule1, "Niet gekend");
    ui_object_set_themeable_style_property(ui_HoogteModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_HoogteModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_align(ui_HoogteModule1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HoogteModule1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderModule1 = lv_label_create(ui_InfoModule1);
    lv_obj_set_width(ui_HeaderModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaderModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HeaderModule1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_HeaderModule1, "Module 1");
    lv_obj_set_style_text_color(ui_HeaderModule1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderModule1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HeaderModule1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderModule1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Module1Connected = lv_label_create(ui_InfoModule1);
    lv_obj_set_width(ui_Module1Connected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Module1Connected, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Module1Connected, "Verbonden");
    ui_object_set_themeable_style_property(ui_Module1Connected, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_Module1Connected, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Red);

    ui_DoelModule1 = lv_label_create(ui_InfoModule1);
    lv_obj_set_width(ui_DoelModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoelModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DoelModule1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoelModule1, "Placeholder_DoelModule1");
    ui_object_set_themeable_style_property(ui_DoelModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_DoelModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_LightBlue);
    lv_obj_set_style_text_font(ui_DoelModule1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmModule1 = lv_label_create(ui_InfoModule1);
    lv_obj_set_width(ui_AlarmModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AlarmModule1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_AlarmModule1, "Alarm");
    lv_obj_add_flag(ui_AlarmModule1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_AlarmModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_AlarmModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Red);

    ui_TextActueleHoogteModule1 = lv_label_create(ui_InfoModule1);
    lv_obj_set_width(ui_TextActueleHoogteModule1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextActueleHoogteModule1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextActueleHoogteModule1, 0);
    lv_obj_set_y(ui_TextActueleHoogteModule1, -25);
    lv_obj_set_align(ui_TextActueleHoogteModule1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_TextActueleHoogteModule1, "Actuele hoogte:");
    ui_object_set_themeable_style_property(ui_TextActueleHoogteModule1, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_TextActueleHoogteModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);

    ui_InfoModule2 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_InfoModule2, 370);
    lv_obj_set_height(ui_InfoModule2, 220);
    lv_obj_set_x(ui_InfoModule2, 415);
    lv_obj_set_y(ui_InfoModule2, 55);
    lv_obj_add_flag(ui_InfoModule2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InfoModule2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    ui_object_set_themeable_style_property(ui_InfoModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_InfoModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);
    ui_object_set_themeable_style_property(ui_InfoModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_InfoModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Green);
    lv_obj_set_style_border_width(ui_InfoModule2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InfoModule2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderModule2 = lv_label_create(ui_InfoModule2);
    lv_obj_set_width(ui_HeaderModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaderModule2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HeaderModule2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_HeaderModule2, "Module 2");
    lv_obj_set_style_text_color(ui_HeaderModule2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderModule2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HeaderModule2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderModule2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Module2Connected = lv_label_create(ui_InfoModule2);
    lv_obj_set_width(ui_Module2Connected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Module2Connected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Module2Connected, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Module2Connected, "Verbonden");
    ui_object_set_themeable_style_property(ui_Module2Connected, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_Module2Connected, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Red);

    ui_HoogteModule2 = lv_label_create(ui_InfoModule2);
    lv_obj_set_width(ui_HoogteModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HoogteModule2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HoogteModule2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_HoogteModule2, "Niet gekend");
    ui_object_set_themeable_style_property(ui_HoogteModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_HoogteModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);
    lv_obj_set_style_text_font(ui_HoogteModule2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoelModule2 = lv_label_create(ui_InfoModule2);
    lv_obj_set_width(ui_DoelModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoelModule2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DoelModule2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoelModule2, "Placeholder_DoelModule2");
    ui_object_set_themeable_style_property(ui_DoelModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_DoelModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_LightBlue);
    lv_obj_set_style_text_font(ui_DoelModule2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmModule2 = lv_label_create(ui_InfoModule2);
    lv_obj_set_width(ui_AlarmModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmModule2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_AlarmModule2, "Alarm");
    lv_obj_add_flag(ui_AlarmModule2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_AlarmModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Red);
    ui_object_set_themeable_style_property(ui_AlarmModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Red);

    ui_TextActueleHoogteModule2 = lv_label_create(ui_InfoModule2);
    lv_obj_set_width(ui_TextActueleHoogteModule2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextActueleHoogteModule2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TextActueleHoogteModule2, 0);
    lv_obj_set_y(ui_TextActueleHoogteModule2, -25);
    lv_obj_set_align(ui_TextActueleHoogteModule2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_TextActueleHoogteModule2, "Actuele hoogte:");
    ui_object_set_themeable_style_property(ui_TextActueleHoogteModule2, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_TextActueleHoogteModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);

    ui_LowerBackground = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_LowerBackground, 800);
    lv_obj_set_height(ui_LowerBackground, 194);
    lv_obj_set_x(ui_LowerBackground, 0);
    lv_obj_set_y(ui_LowerBackground, 286);
    lv_obj_clear_flag(ui_LowerBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_LowerBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_LowerBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_LowerBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_ButtonSelectModule1 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonSelectModule1, 254);
    lv_obj_set_height(ui_ButtonSelectModule1, 90);
    lv_obj_set_x(ui_ButtonSelectModule1, 15);
    lv_obj_set_y(ui_ButtonSelectModule1, 302);
    lv_obj_add_flag(ui_ButtonSelectModule1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectModule1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectModule1 = lv_label_create(ui_ButtonSelectModule1);
    lv_obj_set_width(ui_TextButtonSelectModule1, LV_SIZE_CONTENT);   /// 254
    lv_obj_set_height(ui_TextButtonSelectModule1, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_align(ui_TextButtonSelectModule1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectModule1, "Module 1");
    ui_object_set_themeable_style_property(ui_TextButtonSelectModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectModule1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_align(ui_TextButtonSelectModule1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonSelectModule1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSelectSync = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonSelectSync, 254);
    lv_obj_set_height(ui_ButtonSelectSync, 90);
    lv_obj_set_x(ui_ButtonSelectSync, 273);
    lv_obj_set_y(ui_ButtonSelectSync, 302);
    lv_obj_add_flag(ui_ButtonSelectSync, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectSync, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectSync, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectSync, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectSync = lv_label_create(ui_ButtonSelectSync);
    lv_obj_set_width(ui_TextButtonSelectSync, LV_SIZE_CONTENT);   /// 254
    lv_obj_set_height(ui_TextButtonSelectSync, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_align(ui_TextButtonSelectSync, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectSync, "Sync");
    ui_object_set_themeable_style_property(ui_TextButtonSelectSync, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectSync, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_align(ui_TextButtonSelectSync, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonSelectSync, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSelectModule2 = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonSelectModule2, 254);
    lv_obj_set_height(ui_ButtonSelectModule2, 90);
    lv_obj_set_x(ui_ButtonSelectModule2, 531);
    lv_obj_set_y(ui_ButtonSelectModule2, 302);
    lv_obj_add_flag(ui_ButtonSelectModule2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSelectModule2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonSelectModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonSelectModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonSelectModule2 = lv_label_create(ui_ButtonSelectModule2);
    lv_obj_set_width(ui_TextButtonSelectModule2, LV_SIZE_CONTENT);   /// 254
    lv_obj_set_height(ui_TextButtonSelectModule2, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_align(ui_TextButtonSelectModule2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonSelectModule2, "Module 2");
    ui_object_set_themeable_style_property(ui_TextButtonSelectModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonSelectModule2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_align(ui_TextButtonSelectModule2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonSelectModule2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToPresets = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonGoToPresets, 200);
    lv_obj_set_height(ui_ButtonGoToPresets, 57);
    lv_obj_set_x(ui_ButtonGoToPresets, 0);
    lv_obj_set_y(ui_ButtonGoToPresets, 423);
    lv_obj_add_flag(ui_ButtonGoToPresets, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToPresets, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonGoToPresets, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonGoToPresets, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonGoToPresets = lv_label_create(ui_ButtonGoToPresets);
    lv_obj_set_width(ui_TextButtonGoToPresets, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonGoToPresets, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonGoToPresets, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonGoToPresets, "Presets");
    ui_object_set_themeable_style_property(ui_TextButtonGoToPresets, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonGoToPresets, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonGoToPresets, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToSettings = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonGoToSettings, 200);
    lv_obj_set_height(ui_ButtonGoToSettings, 57);
    lv_obj_set_x(ui_ButtonGoToSettings, 200);
    lv_obj_set_y(ui_ButtonGoToSettings, 423);
    lv_obj_add_flag(ui_ButtonGoToSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonGoToSettings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonGoToSettings, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonGoToPresets1 = lv_label_create(ui_ButtonGoToSettings);
    lv_obj_set_width(ui_TextButtonGoToPresets1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonGoToPresets1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonGoToPresets1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonGoToPresets1, "Settings");
    ui_object_set_themeable_style_property(ui_TextButtonGoToPresets1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonGoToPresets1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonGoToPresets1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonStap = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonStap, 200);
    lv_obj_set_height(ui_ButtonStap, 57);
    lv_obj_set_x(ui_ButtonStap, 400);
    lv_obj_set_y(ui_ButtonStap, 423);
    lv_obj_add_flag(ui_ButtonStap, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonStap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonStap, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonStap, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonStap = lv_label_create(ui_ButtonStap);
    lv_obj_set_width(ui_TextButtonStap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonStap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonStap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonStap, "Stap: Placeholder_Stap");
    ui_object_set_themeable_style_property(ui_TextButtonStap, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonStap, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonStap, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKalibreer = lv_btn_create(ui_ScreenHome);
    lv_obj_set_width(ui_ButtonKalibreer, 200);
    lv_obj_set_height(ui_ButtonKalibreer, 57);
    lv_obj_set_x(ui_ButtonKalibreer, 600);
    lv_obj_set_y(ui_ButtonKalibreer, 423);
    lv_obj_add_flag(ui_ButtonKalibreer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonKalibreer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonKalibreer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonKalibreer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonKalibreer = lv_label_create(ui_ButtonKalibreer);
    lv_obj_set_width(ui_TextButtonKalibreer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonKalibreer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonKalibreer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonKalibreer, "Kalibreer\ngeselecteerde");
    ui_object_set_themeable_style_property(ui_TextButtonKalibreer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonKalibreer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_align(ui_TextButtonKalibreer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonKalibreer, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonSelectModule1, ui_event_ButtonSelectModule1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSelectSync, ui_event_ButtonSelectSync, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSelectModule2, ui_event_ButtonSelectModule2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToPresets, ui_event_ButtonGoToPresets, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToSettings, ui_event_ButtonGoToSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonStap, ui_event_ButtonStap, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonKalibreer, ui_event_ButtonKalibreer, LV_EVENT_ALL, NULL);

}

void ui_ScreenHome_screen_destroy(void)
{
    if(ui_ScreenHome) lv_obj_del(ui_ScreenHome);

    // NULL screen variables
    ui_ScreenHome = NULL;
    ui_HeaderHomeBackground = NULL;
    ui_HeaderHome = NULL;
    ui_InfoModule1 = NULL;
    ui_HoogteModule1 = NULL;
    ui_HeaderModule1 = NULL;
    ui_Module1Connected = NULL;
    ui_DoelModule1 = NULL;
    ui_AlarmModule1 = NULL;
    ui_TextActueleHoogteModule1 = NULL;
    ui_InfoModule2 = NULL;
    ui_HeaderModule2 = NULL;
    ui_Module2Connected = NULL;
    ui_HoogteModule2 = NULL;
    ui_DoelModule2 = NULL;
    ui_AlarmModule2 = NULL;
    ui_TextActueleHoogteModule2 = NULL;
    ui_LowerBackground = NULL;
    ui_ButtonSelectModule1 = NULL;
    ui_TextButtonSelectModule1 = NULL;
    ui_ButtonSelectSync = NULL;
    ui_TextButtonSelectSync = NULL;
    ui_ButtonSelectModule2 = NULL;
    ui_TextButtonSelectModule2 = NULL;
    ui_ButtonGoToPresets = NULL;
    ui_TextButtonGoToPresets = NULL;
    ui_ButtonGoToSettings = NULL;
    ui_TextButtonGoToPresets1 = NULL;
    ui_ButtonStap = NULL;
    ui_TextButtonStap = NULL;
    ui_ButtonKalibreer = NULL;
    ui_TextButtonKalibreer = NULL;

}
