// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_HeaderSettingsBackground = NULL;
lv_obj_t * ui_HeaderSettings = NULL;
lv_obj_t * ui_SettingLinkNaarProjectBackground = NULL;
lv_obj_t * ui_LinkNaarProject = NULL;
lv_obj_t * ui_ButtonToonLink = NULL;
lv_obj_t * ui_TextButtonToonLink = NULL;
lv_obj_t * ui_ButtonVerbergLink = NULL;
lv_obj_t * ui_TextButtonVerbergLink = NULL;
lv_obj_t * ui_SettingEncoderknopBackground = NULL;
lv_obj_t * ui_EncoderknopRegelt = NULL;
lv_obj_t * ui_ButtonWisselenVanModule = NULL;
lv_obj_t * ui_TextButtonWisselenVanModule = NULL;
lv_obj_t * ui_ButtonAanpassenVanDeStap = NULL;
lv_obj_t * ui_TextButtonAanpassenVanDeStap = NULL;
lv_obj_t * ui_ButtonResetAlarm = NULL;
lv_obj_t * ui_TextButtonResetAlarm = NULL;
lv_obj_t * ui_ButtonEncoderknop = NULL;
lv_obj_t * ui_TextButtonEncoderknop = NULL;
lv_obj_t * ui_ButtonKalibreerBeide2 = NULL;
lv_obj_t * ui_TextButtonKalibreer2 = NULL;
lv_obj_t * ui_ButtonGoToHome2 = NULL;
lv_obj_t * ui_TextButtonGoToHome2 = NULL;
lv_obj_t * ui_ButtonResetAlarm2 = NULL;
lv_obj_t * ui_TextButtonResetAlarm2 = NULL;
lv_obj_t * ui_HeaderFoutcode = NULL;
lv_obj_t * ui_Foutcodes = NULL;
lv_obj_t * ui_ButtonKalibreerBeide = NULL;
lv_obj_t * ui_TextButtonKalibreer3 = NULL;
lv_obj_t * ui_TextButtonKalibreerExtra = NULL;
lv_obj_t * ui_LinkNaarProject2 = NULL;
lv_obj_t * ui_TextLinkNaarProject = NULL;
// event funtions
void ui_event_ButtonToonLink(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_LinkNaarProject2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        ChangeColorButtonToon(e);
    }
}

void ui_event_ButtonVerbergLink(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_LinkNaarProject2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        ChangeColorButtonVerberg(e);
    }
}

void ui_event_ButtonWisselenVanModule(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SwitchEncoderknopWisselenModule(e);
    }
}

void ui_event_ButtonAanpassenVanDeStap(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SwitchEncoderknopAanspassenStap(e);
    }
}

void ui_event_ButtonResetAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ResetAlarm(e);
        (e);
    }
}

void ui_event_ButtonEncoderknop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SwitchEncoderknop(e);
    }
}

void ui_event_ButtonKalibreerBeide2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Kalibratie(e);
    }
}

void ui_event_ButtonGoToHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenHome_screen_init);
    }
}

void ui_event_ButtonResetAlarm2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ResetAlarm(e);
    }
}

void ui_event_ButtonKalibreerBeide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Kalibratie(e);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderSettingsBackground = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_HeaderSettingsBackground, 800);
    lv_obj_set_height(ui_HeaderSettingsBackground, 50);
    lv_obj_clear_flag(ui_HeaderSettingsBackground,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_HeaderSettingsBackground, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_HeaderSettingsBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_HeaderSettingsBackground, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_HeaderSettings = lv_label_create(ui_HeaderSettingsBackground);
    lv_obj_set_width(ui_HeaderSettings, LV_SIZE_CONTENT);   /// 44
    lv_obj_set_height(ui_HeaderSettings, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_HeaderSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeaderSettings, "Settings");
    lv_obj_set_style_text_color(ui_HeaderSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeaderSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeaderSettings, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingLinkNaarProjectBackground = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_SettingLinkNaarProjectBackground, 780);
    lv_obj_set_height(ui_SettingLinkNaarProjectBackground, 60);
    lv_obj_set_x(ui_SettingLinkNaarProjectBackground, 10);
    lv_obj_set_y(ui_SettingLinkNaarProjectBackground, 70);
    lv_obj_add_flag(ui_SettingLinkNaarProjectBackground, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingLinkNaarProjectBackground, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingLinkNaarProjectBackground, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_SettingLinkNaarProjectBackground, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_DarkBlue);

    ui_LinkNaarProject = lv_label_create(ui_SettingLinkNaarProjectBackground);
    lv_obj_set_width(ui_LinkNaarProject, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LinkNaarProject, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LinkNaarProject, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LinkNaarProject, "Link naar project");
    lv_obj_set_style_text_color(ui_LinkNaarProject, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LinkNaarProject, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonToonLink = lv_btn_create(ui_SettingLinkNaarProjectBackground);
    lv_obj_set_width(ui_ButtonToonLink, 185);
    lv_obj_set_height(ui_ButtonToonLink, 40);
    lv_obj_set_x(ui_ButtonToonLink, -100);
    lv_obj_set_y(ui_ButtonToonLink, 0);
    lv_obj_set_align(ui_ButtonToonLink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonToonLink, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonToonLink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonToonLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonToonLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonToonLink = lv_label_create(ui_ButtonToonLink);
    lv_obj_set_width(ui_TextButtonToonLink, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonToonLink, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonToonLink, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonToonLink, "Toon");
    ui_object_set_themeable_style_property(ui_TextButtonToonLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonToonLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_ButtonVerbergLink = lv_btn_create(ui_SettingLinkNaarProjectBackground);
    lv_obj_set_width(ui_ButtonVerbergLink, 185);
    lv_obj_set_height(ui_ButtonVerbergLink, 40);
    lv_obj_set_x(ui_ButtonVerbergLink, 150);
    lv_obj_set_y(ui_ButtonVerbergLink, 0);
    lv_obj_set_align(ui_ButtonVerbergLink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonVerbergLink, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonVerbergLink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonVerbergLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Green);
    ui_object_set_themeable_style_property(ui_ButtonVerbergLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Green);

    ui_TextButtonVerbergLink = lv_label_create(ui_ButtonVerbergLink);
    lv_obj_set_width(ui_TextButtonVerbergLink, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonVerbergLink, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonVerbergLink, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonVerbergLink, "Verberg");
    ui_object_set_themeable_style_property(ui_TextButtonVerbergLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonVerbergLink, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_SettingEncoderknopBackground = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_SettingEncoderknopBackground, 780);
    lv_obj_set_height(ui_SettingEncoderknopBackground, 60);
    lv_obj_set_x(ui_SettingEncoderknopBackground, 10);
    lv_obj_set_y(ui_SettingEncoderknopBackground, 140);
    lv_obj_add_flag(ui_SettingEncoderknopBackground, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingEncoderknopBackground, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingEncoderknopBackground, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_SettingEncoderknopBackground, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_DarkBlue);

    ui_EncoderknopRegelt = lv_label_create(ui_SettingEncoderknopBackground);
    lv_obj_set_width(ui_EncoderknopRegelt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EncoderknopRegelt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EncoderknopRegelt, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_EncoderknopRegelt, "Encoderknop regelt: ");
    lv_obj_set_style_text_color(ui_EncoderknopRegelt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EncoderknopRegelt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonWisselenVanModule = lv_btn_create(ui_SettingEncoderknopBackground);
    lv_obj_set_width(ui_ButtonWisselenVanModule, 185);
    lv_obj_set_height(ui_ButtonWisselenVanModule, 40);
    lv_obj_set_x(ui_ButtonWisselenVanModule, -100);
    lv_obj_set_y(ui_ButtonWisselenVanModule, 0);
    lv_obj_set_align(ui_ButtonWisselenVanModule, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonWisselenVanModule, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonWisselenVanModule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonWisselenVanModule, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonWisselenVanModule, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonWisselenVanModule = lv_label_create(ui_ButtonWisselenVanModule);
    lv_obj_set_width(ui_TextButtonWisselenVanModule, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonWisselenVanModule, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonWisselenVanModule, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonWisselenVanModule, "Wisselen van module");
    ui_object_set_themeable_style_property(ui_TextButtonWisselenVanModule, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonWisselenVanModule, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_DarkBlue);

    ui_ButtonAanpassenVanDeStap = lv_btn_create(ui_SettingEncoderknopBackground);
    lv_obj_set_width(ui_ButtonAanpassenVanDeStap, 185);
    lv_obj_set_height(ui_ButtonAanpassenVanDeStap, 40);
    lv_obj_set_x(ui_ButtonAanpassenVanDeStap, 150);
    lv_obj_set_y(ui_ButtonAanpassenVanDeStap, 0);
    lv_obj_set_align(ui_ButtonAanpassenVanDeStap, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAanpassenVanDeStap, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAanpassenVanDeStap, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonAanpassenVanDeStap, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonAanpassenVanDeStap, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonAanpassenVanDeStap = lv_label_create(ui_ButtonAanpassenVanDeStap);
    lv_obj_set_width(ui_TextButtonAanpassenVanDeStap, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonAanpassenVanDeStap, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonAanpassenVanDeStap, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonAanpassenVanDeStap, "Aanpassen van de stap");
    ui_object_set_themeable_style_property(ui_TextButtonAanpassenVanDeStap, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonAanpassenVanDeStap, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_DarkBlue);

    ui_ButtonResetAlarm = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonResetAlarm, 200);
    lv_obj_set_height(ui_ButtonResetAlarm, 57);
    lv_obj_set_x(ui_ButtonResetAlarm, 0);
    lv_obj_set_y(ui_ButtonResetAlarm, 423);
    lv_obj_add_flag(ui_ButtonResetAlarm, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonResetAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonResetAlarm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonResetAlarm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonResetAlarm = lv_label_create(ui_ButtonResetAlarm);
    lv_obj_set_width(ui_TextButtonResetAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonResetAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonResetAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonResetAlarm, "Reset alarm");
    ui_object_set_themeable_style_property(ui_TextButtonResetAlarm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonResetAlarm, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonResetAlarm, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonEncoderknop = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonEncoderknop, 200);
    lv_obj_set_height(ui_ButtonEncoderknop, 57);
    lv_obj_set_x(ui_ButtonEncoderknop, 200);
    lv_obj_set_y(ui_ButtonEncoderknop, 423);
    lv_obj_add_flag(ui_ButtonEncoderknop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonEncoderknop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonEncoderknop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonEncoderknop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonEncoderknop = lv_label_create(ui_ButtonEncoderknop);
    lv_obj_set_width(ui_TextButtonEncoderknop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonEncoderknop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonEncoderknop, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonEncoderknop, "Encoderknop");
    ui_object_set_themeable_style_property(ui_TextButtonEncoderknop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonEncoderknop, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonEncoderknop, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonKalibreerBeide2 = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonKalibreerBeide2, 200);
    lv_obj_set_height(ui_ButtonKalibreerBeide2, 57);
    lv_obj_set_x(ui_ButtonKalibreerBeide2, 400);
    lv_obj_set_y(ui_ButtonKalibreerBeide2, 423);
    lv_obj_add_flag(ui_ButtonKalibreerBeide2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonKalibreerBeide2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonKalibreerBeide2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonKalibreerBeide2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonKalibreer2 = lv_label_create(ui_ButtonKalibreerBeide2);
    lv_obj_set_width(ui_TextButtonKalibreer2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonKalibreer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonKalibreer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonKalibreer2, "Kalibreer 1 en 2");
    ui_object_set_themeable_style_property(ui_TextButtonKalibreer2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonKalibreer2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonKalibreer2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGoToHome2 = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonGoToHome2, 200);
    lv_obj_set_height(ui_ButtonGoToHome2, 57);
    lv_obj_set_x(ui_ButtonGoToHome2, 600);
    lv_obj_set_y(ui_ButtonGoToHome2, 423);
    lv_obj_add_flag(ui_ButtonGoToHome2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGoToHome2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonGoToHome2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_ButtonGoToHome2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_TextButtonGoToHome2 = lv_label_create(ui_ButtonGoToHome2);
    lv_obj_set_width(ui_TextButtonGoToHome2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonGoToHome2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonGoToHome2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextButtonGoToHome2, "Terug");
    lv_obj_set_style_text_color(ui_TextButtonGoToHome2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextButtonGoToHome2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextButtonGoToHome2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResetAlarm2 = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonResetAlarm2, 380);
    lv_obj_set_height(ui_ButtonResetAlarm2, 170);
    lv_obj_set_x(ui_ButtonResetAlarm2, 10);
    lv_obj_set_y(ui_ButtonResetAlarm2, 230);
    lv_obj_add_flag(ui_ButtonResetAlarm2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonResetAlarm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonResetAlarm2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonResetAlarm2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonResetAlarm2 = lv_label_create(ui_ButtonResetAlarm2);
    lv_obj_set_width(ui_TextButtonResetAlarm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonResetAlarm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonResetAlarm2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TextButtonResetAlarm2, "ResetAlarm");
    ui_object_set_themeable_style_property(ui_TextButtonResetAlarm2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonResetAlarm2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonResetAlarm2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderFoutcode = lv_label_create(ui_ButtonResetAlarm2);
    lv_obj_set_width(ui_HeaderFoutcode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeaderFoutcode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeaderFoutcode, 50);
    lv_obj_set_y(ui_HeaderFoutcode, 0);
    lv_obj_set_align(ui_HeaderFoutcode, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_HeaderFoutcode, "Foutcode:");
    ui_object_set_themeable_style_property(ui_HeaderFoutcode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_HeaderFoutcode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_Foutcodes = lv_label_create(ui_ButtonResetAlarm2);
    lv_obj_set_width(ui_Foutcodes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Foutcodes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Foutcodes, 70);
    lv_obj_set_y(ui_Foutcodes, 20);
    lv_obj_set_align(ui_Foutcodes, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Foutcodes, "Placeholder_Foutcode");
    ui_object_set_themeable_style_property(ui_Foutcodes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_Foutcodes, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_ButtonKalibreerBeide = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_ButtonKalibreerBeide, 380);
    lv_obj_set_height(ui_ButtonKalibreerBeide, 170);
    lv_obj_set_x(ui_ButtonKalibreerBeide, 410);
    lv_obj_set_y(ui_ButtonKalibreerBeide, 230);
    lv_obj_add_flag(ui_ButtonKalibreerBeide, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonKalibreerBeide, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ButtonKalibreerBeide, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_LightBlue);
    ui_object_set_themeable_style_property(ui_ButtonKalibreerBeide, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_LightBlue);

    ui_TextButtonKalibreer3 = lv_label_create(ui_ButtonKalibreerBeide);
    lv_obj_set_width(ui_TextButtonKalibreer3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonKalibreer3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonKalibreer3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_TextButtonKalibreer3, "Kalibreer 1 en 2");
    ui_object_set_themeable_style_property(ui_TextButtonKalibreer3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_TextButtonKalibreer3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_DarkBlue);
    lv_obj_set_style_text_font(ui_TextButtonKalibreer3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextButtonKalibreerExtra = lv_label_create(ui_ButtonKalibreerBeide);
    lv_obj_set_width(ui_TextButtonKalibreerExtra, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextButtonKalibreerExtra, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextButtonKalibreerExtra, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_TextButtonKalibreerExtra, "Aangeraden na elke opstart");
    ui_object_set_themeable_style_property(ui_TextButtonKalibreerExtra, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_TextButtonKalibreerExtra, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Grey);

    ui_LinkNaarProject2 = lv_btn_create(ui_ScreenSettings);
    lv_obj_set_width(ui_LinkNaarProject2, 780);
    lv_obj_set_height(ui_LinkNaarProject2, 60);
    lv_obj_set_x(ui_LinkNaarProject2, 10);
    lv_obj_set_y(ui_LinkNaarProject2, 140);
    lv_obj_add_flag(ui_LinkNaarProject2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LinkNaarProject2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_LinkNaarProject2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_DarkBlue);
    ui_object_set_themeable_style_property(ui_LinkNaarProject2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_DarkBlue);

    ui_TextLinkNaarProject = lv_label_create(ui_LinkNaarProject2);
    lv_obj_set_width(ui_TextLinkNaarProject, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextLinkNaarProject, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TextLinkNaarProject, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TextLinkNaarProject, "https://github.com/timverdcourt-a11y/Plooibank");
    lv_obj_set_style_text_color(ui_TextLinkNaarProject, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextLinkNaarProject, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextLinkNaarProject, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonToonLink, ui_event_ButtonToonLink, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonVerbergLink, ui_event_ButtonVerbergLink, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonWisselenVanModule, ui_event_ButtonWisselenVanModule, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonAanpassenVanDeStap, ui_event_ButtonAanpassenVanDeStap, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonResetAlarm, ui_event_ButtonResetAlarm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonEncoderknop, ui_event_ButtonEncoderknop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonKalibreerBeide2, ui_event_ButtonKalibreerBeide2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGoToHome2, ui_event_ButtonGoToHome2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonResetAlarm2, ui_event_ButtonResetAlarm2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonKalibreerBeide, ui_event_ButtonKalibreerBeide, LV_EVENT_ALL, NULL);

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_HeaderSettingsBackground = NULL;
    ui_HeaderSettings = NULL;
    ui_SettingLinkNaarProjectBackground = NULL;
    ui_LinkNaarProject = NULL;
    ui_ButtonToonLink = NULL;
    ui_TextButtonToonLink = NULL;
    ui_ButtonVerbergLink = NULL;
    ui_TextButtonVerbergLink = NULL;
    ui_SettingEncoderknopBackground = NULL;
    ui_EncoderknopRegelt = NULL;
    ui_ButtonWisselenVanModule = NULL;
    ui_TextButtonWisselenVanModule = NULL;
    ui_ButtonAanpassenVanDeStap = NULL;
    ui_TextButtonAanpassenVanDeStap = NULL;
    ui_ButtonResetAlarm = NULL;
    ui_TextButtonResetAlarm = NULL;
    ui_ButtonEncoderknop = NULL;
    ui_TextButtonEncoderknop = NULL;
    ui_ButtonKalibreerBeide2 = NULL;
    ui_TextButtonKalibreer2 = NULL;
    ui_ButtonGoToHome2 = NULL;
    ui_TextButtonGoToHome2 = NULL;
    ui_ButtonResetAlarm2 = NULL;
    ui_TextButtonResetAlarm2 = NULL;
    ui_HeaderFoutcode = NULL;
    ui_Foutcodes = NULL;
    ui_ButtonKalibreerBeide = NULL;
    ui_TextButtonKalibreer3 = NULL;
    ui_TextButtonKalibreerExtra = NULL;
    ui_LinkNaarProject2 = NULL;
    ui_TextLinkNaarProject = NULL;

}
