// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenHome.h"
#include "screens/ui_ScreenPresetselect.h"
#include "screens/ui_ScreenPresetedit.h"
#include "screens/ui_ScreenProgram.h"
#include "screens/ui_ScreenProgramEdit.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pimm_logo_png);    // assets/PIMM logo.png

// UI INIT
void ui_init(void);
void ui_destroy(void);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
