// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void pimm_select_module1(lv_event_t * e);
void pimm_select_both(lv_event_t * e);
void pimm_select_module2(lv_event_t * e);
void pimm_toggle_sync(lv_event_t * e);
void pimm_power_off(lv_event_t * e);
void pimm_select_preset1(lv_event_t * e);
void pimm_select_preset2(lv_event_t * e);
void pimm_select_preset3(lv_event_t * e);
void pimm_select_preset4(lv_event_t * e);
void pimm_apply_preset(lv_event_t * e);
void pimm_rename_preset(lv_event_t * e);
void pimm_preset_focus_textarea(lv_event_t * e);
void pimm_toggle_preset_sync(lv_event_t * e);
void pimm_save_presets(lv_event_t * e);
void pimm_clear_preset_field(lv_event_t * e);
void pimm_restore_preset(lv_event_t * e);
void pimm_program_prev_step(lv_event_t * e);
void pimm_program_next_step(lv_event_t * e);
void pimm_prgedit_select_m1(lv_event_t * e);
void pimm_prgedit_select_m2(lv_event_t * e);
void pimm_program_delete_step(lv_event_t * e);
void pimm_program_set_step(lv_event_t * e);
void pimm_program_add_step(lv_event_t * e);
void pimm_program_save(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
